* Beginning of Post-Modern
  :PROPERTIES:
  :CUSTOM_ID: beginning-of-post-modern
  :END:

** 9. Ch. 18: Barth, Bultmann, end of western civilization
   :PROPERTIES:
   :CUSTOM_ID: 9-ch-18-barth-bultmann-end-of-western-civilization
   :END:

*** Presentations
    :PROPERTIES:
    :CUSTOM_ID: presentations
    :END:

**** Leaving the 19th c. behind
     :PROPERTIES:
     :CUSTOM_ID: leaving-the-19th-c-behind
     :END:

***** Barth
      :PROPERTIES:
      :CUSTOM_ID: barth
      :END:

- rejection of cultural Christianity: Grace of Christ is supreme
- everything reflects biases and cultural assumptions
- attacked all human efforts to understand God

***** Anti-semitism interlude?
      :PROPERTIES:
      :CUSTOM_ID: anti-semitism-interlude
      :END:

- "God on Trial"
- Roots and implications
- God on trial trailer 1:37 min [[https://youtu.be/0W9uRPuo7hc]]
- complete: [[https://youtu.be/tD7v9phroGM]]
- [[https://youtu.be/5caAug5n8Zk]]

***** Bonhoeffer
      :PROPERTIES:
      :CUSTOM_ID: bonhoeffer
      :END:

- Cheap Grace
- Religionless Christianity
- trailer to pbs documentary: 1:21 [[https://youtu.be/Cd_gmkypPGk]]
- [[http://www.pbs.md/bonhoeffer/]]

***** Bultmann & Existentialism
      :PROPERTIES:
      :CUSTOM_ID: bultmann--existentialism
      :END:

- Search for historical truth is fruitless
- There is no "human nature" to find
- p. 257

***** American response
      :PROPERTIES:
      :CUSTOM_ID: american-response
      :END:

- Fundamentalism: Inerrancy
- Niebuhr: Social realist

**** From 19th - 20th c.
     :PROPERTIES:
     :CUSTOM_ID: from-19th---20th-c
     :END:

***** Existentialism and Fundamentalism
      :PROPERTIES:
      :CUSTOM_ID: existentialism-and-fundamentalism
      :END:

***** Existentialism's impact
      :PROPERTIES:
      :CUSTOM_ID: existentialisms-impact
      :END:

Bultmann's “left-wing” followers, like the American Schubert Ogden, have
concluded that Christianity concerns only the possibility of a new way
of existing.

***** American response
      :PROPERTIES:
      :CUSTOM_ID: american-response-1
      :END:

- Reinhold Niebuhr: Christian realism "Man's capacity for justice makes
  democracy possible; but man's inclination to injustice makes democracy
  necessary."

  #+BEGIN_HTML
    <p class="verse">
    God, grant me the serenity to accept the things I cannot change,<br />
    The courage to change the things I can,<br />
    And the wisdom to know the difference.<br />
    </p>
  #+END_HTML

  cf. [[https://en.wikipedia.md/wiki/Serenity_Prayer]]

***** Christ and culture
      :PROPERTIES:
      :CUSTOM_ID: christ-and-culture
      :END:

Richard Niebuhr: Christian ethicist: /Christ and Culture/

- *Christ against Culture:* For the exclusive Christian, history is the
  story of a rising church or - Christian culture and a dying pagan
  civilization.
- *Christ of Culture:* For the cultural Christian, history is the story
  of the Spirit's encounter with nature.
- *Christ above Culture:* For the synthesist, history is a period of
  preparation under law, reason, gospel, and church for an ultimate
  communion of the soul with God.
- *Christ and Culture in Paradox:* For the dualist, history is the time
  of struggle between faith and unbelief, a period between the giving of
  the promise of life and its fulfillment.
- *Christ Transforming Culture:* For the conversionist, history is the
  story of God's mighty deeds and humanity's response to them.

***** Evangelical
      :PROPERTIES:
      :CUSTOM_ID: evangelical
      :END:

- United States. Evangelical theology, with a renewed emphasis on the
  authority and often the literal inspiration of the Bible, also
  continues to be an important force in American theology, but it has
  generally reaffirmed the views Charles Hodge and Benjamin B. Warfield
  developed in the nineteenth century rather than producing new ideas.

***** Catholic development
      :PROPERTIES:
      :CUSTOM_ID: catholic-development
      :END:

1. Catholic focus

   1. Roman Catholic response

   - Rahner said that there is a fundamental mystery, a matter of
     religious faith, at the heart of all human understanding.
   - Vatican 2: Pilgrim people: define “the church” not as the hierarchy
     of pope and bishops but as the whole “pielgrim people of God.”

   #+BEGIN_QUOTE
     The joys and the hopes, the griefs and the anxieties of the men of
     this age, especially those who are poor or in any way afflicted,
     these are the joys and hopes, the griefs and anxieties of the
     followers of Christ.
   #+END_QUOTE

   [[http://www.cctwincities.md/document.doc?id=62]]

***** Roman Catholic response
      :PROPERTIES:
      :CUSTOM_ID: roman-catholic-response
      :END:

- Vatican 2: Pilgrim people
- Lonergan: It's all about the method
- Rahner: The mystery is beyond words

***** Theology and Freedom
      :PROPERTIES:
      :CUSTOM_ID: theology-and-freedom
      :END:

***** LIBERATION THEOLOGY
      :PROPERTIES:
      :CUSTOM_ID: liberation-theology
      :END:

- That very emphasis---liberating the captives---names the most
  important field of theology in the last half-century.
- Liberation theology first drew wide attention in the United States in
  connection with “black liberation.”
- James Cone's Black Theology and Black Power, published in 1969, made
  the blacks' liberation from their white oppressors its central
  theological theme and addressed whites with warnings rather than pleas
  for help.

***** Feminist criticism / liberation
      :PROPERTIES:
      :CUSTOM_ID: feminist-criticism--liberation
      :END:

- Looking beyond that, Rosemary Radford Ruether (a prolific theologian
  committed both to feminism and to Christianity) has written, All
  theologies of liberation, whether done in a black or a feminist or a
  Third World perspective, will be abortive of the liberation they seek,
  unless they finally go beyond the ... model of the oppressor and the
  oppressed.

***** THEOLOGY AND THE RELIGIONS
      :PROPERTIES:
      :CUSTOM_ID: theology-and-the-religions
      :END:

- “Yes, I am a syncretist. But so are you. I know that I am a
  syncretist, but you don't know you are a syncretist because you have
  hegemonic power.
- Other theologians of pluralism have been less insistent that multiple
  religions are different ways of saying the same thing. A Roman
  Catholic priest named Raimundo Pannikar, for example, born in Spain to
  a Hindu father and a Spanish mother, advocates a more strictly
  comparative approach.

*** Notes
    :PROPERTIES:
    :CUSTOM_ID: notes
    :END:

**** Old Presentations
     :PROPERTIES:
     :CUSTOM_ID: old-presentations
     :END:

***** 

***** as above
      :PROPERTIES:
      :CUSTOM_ID: as-above
      :END:

***** ch. 18, Barth, Bonhoeffer
      :PROPERTIES:
      :CUSTOM_ID: ch-18-barth-bonhoeffer
      :END:

***** into 20th c.
      :PROPERTIES:
      :CUSTOM_ID: into-20th-c
      :END:

**** Representative figures
     :PROPERTIES:
     :CUSTOM_ID: representative-figures
     :END:

***** Karl Barth
      :PROPERTIES:
      :CUSTOM_ID: karl-barth
      :END:

[[317-20thc-pt1]] / [[317-barth]] 317-barth

***** Albert Schweitzer
      :PROPERTIES:
      :CUSTOM_ID: albert-schweitzer
      :END:

***** Bohoeffer
      :PROPERTIES:
      :CUSTOM_ID: bohoeffer
      :END:

***** Niebuhr
      :PROPERTIES:
      :CUSTOM_ID: niebuhr
      :END:

***** Bultmann
      :PROPERTIES:
      :CUSTOM_ID: bultmann
      :END:

**** Outline: The end of western Christendom
     :PROPERTIES:
     :CUSTOM_ID: outline-the-end-of-western-christendom
     :END:

***** epigraph: Peter Berger re. Nazi's
      :PROPERTIES:
      :CUSTOM_ID: epigraph-peter-berger-re-nazis
      :END:

***** Barth & Bonhoeffer
      :PROPERTIES:
      :CUSTOM_ID: barth--bonhoeffer
      :END:

***** American developments
      :PROPERTIES:
      :CUSTOM_ID: american-developments
      :END:

***** Bultmann & Existentialism
      :PROPERTIES:
      :CUSTOM_ID: bultmann--existentialism-1
      :END:

****** Heidegger
       :PROPERTIES:
       :CUSTOM_ID: heidegger
       :END:

***** Roman Catholic Theology to Vatican II
      :PROPERTIES:
      :CUSTOM_ID: roman-catholic-theology-to-vatican-ii
      :END:

** 10. Ch. 19: Current scene
   :PROPERTIES:
   :CUSTOM_ID: 10-ch-19-current-scene
   :END:

*** Presentations
    :PROPERTIES:
    :CUSTOM_ID: presentations-1
    :END:

**** Theology And Recent Philosophies
     :PROPERTIES:
     :CUSTOM_ID: theology-and-recent-philosophies
     :END:

***** Wittgenstein
      :PROPERTIES:
      :CUSTOM_ID: wittgenstein
      :END:

- logical positivists demanded, “How can we design a scientific
  experiment to test whether or not God exists?

- later writings of the philosopher Ludwig Wittgenstein, they have
  recognized how many different ways language can be used meaningfully.

- Language has also been a preoccupation for French philosophers like
  Jacques Derrida and François Lyotard, and theologians have recently
  used their ideas to develop a “postmodern” theology

***** deconstruction
      :PROPERTIES:
      :CUSTOM_ID: deconstruction
      :END:

- Two world wars, the Holocaust, and increasing globalization make such
  “modern” views impossible to hold in a postmodern world. Derrida
  advocated the need for a postmodern “deconstruction” of knowledge

***** American response
      :PROPERTIES:
      :CUSTOM_ID: american-response-2
      :END:

- United States. Evangelical theology, with a renewed emphasis on the
  authority and often the literal inspiration of the Bible, also
  continues to be an important force in American theology, but it has
  generally reaffirmed the views Charles Hodge and Benjamin B. Warfield
  developed in the nineteenth century rather than producing new ideas.

***** Process theology
      :PROPERTIES:
      :CUSTOM_ID: process-theology
      :END:

- “process theology,” has developed here under the influence of Alfred
  North Whitehead.
- Process theology describes a God who is perfect in that he is
  perfectly related to everything, who lures actions by love rather than
  forcing them by power. “He is the poet of the world, with tender
  patience leading it by his vision of truth, beauty, and goodness.

***** Hope & Eschatology
      :PROPERTIES:
      :CUSTOM_ID: hope--eschatology
      :END:

- reaction to Bultmann: viz. place of *Old Testament* for Christian
  theology
- Schweitzer & others have shown the importance of *eschatology* for
  understanding New Testament
- Pannenberg: Christian theology must understand itself in the world we
  live in
- Dorothy Sölle: role of *suffering* in Theology

Notes:

OT use: p. 263/268. One contra Bultmann, one MLK re. liberation

Issue: use of OT in Christian theology

- pre-figuring NT
- superceded
- needing figurative interpretation

Wolfhart Pannenberg (2 October 1928 -- 4 September 2014) was a German
theologian. He has made a number of significant contributions to modern
theology, including his concept of *history as a form of revelation
centered on the Resurrection of Christ*, which has been widely debated
in both Protestant and Catholic theology, as well as by non-Christian
thinkers.

She wrote a large number of books, including /Theology for Skeptics:
Reflections on God/, /The Silent Cry: Mysticism and Resistance/ (2001)
and her autobiography /Against the Wind: Memoir of a Radical Christian/
(1999). In /Beyond Mere Obedience: Reflections on a Christian Ethic for
the Future/ she coined the term "Christofascist" to describe
fundamentalists. Perhaps her best-known work in English was /Suffering/,
which offers a critique of "Christian masochism" and "theological
sadism". Sölle's *critique is against the assumption that God is
all-powerful and the cause of suffering*; humans thus suffer for some
greater purpose. Instead, God suffers and is powerless alongside us.
Humans are to struggle together against oppression, sexism,
anti-Semitism, and other forms of authoritarianism.

***** THEOLOGY AND THE SECULAR
      :PROPERTIES:
      :CUSTOM_ID: theology-and-the-secular
      :END:

- theology engaging: sciences, biology, anthropology, arts,
- "Big enough God"
- Harvey Cox at Harvard saw a need for Christianity to engagement with
  secular disciplines as a real opportunity
- related to Bonhoeffer's "religionless Christianity"?

***** Theology & the Secular
      :PROPERTIES:
      :CUSTOM_ID: theology--the-secular
      :END:

- theology for church vs. for the secular world
- John Polkinghorne
- Ian Barbour
- Theology: image of "wheel" vs. "matrix"
- Harvey Cox: value in engaging the secular world (cf. Bonhoeffer)

Notes:

Relating God's action in the natural world to physics, biology, etc.

cf. esp. awareness of natural environment. Reading of Genesis 1.

Cox: avoid theology being a ghetto cut off from the world

***** Liberation Theology
      :PROPERTIES:
      :CUSTOM_ID: liberation-theology-1
      :END:

- Africa, Latin America: experience of being *oppressed*
- 1960's "black liberation" in US: parallels between Israel's slavery in
  Egypt & slavery in modern world
- MLK Jr. "Letter from Birmingham Jail" cp. "Barmen Declaration"
- James Cone: "being black is not a matter of skin color"
- Women's liberation:
- Recognizing that both oppressed and oppressor need "liberating"

Notes:

cp. the new "Reclaiming Jesus"

Nicaragua: teaching literacy with no books. Only at hand is bible.
Finding the meaning there.

***** Theology and Freedom
      :PROPERTIES:
      :CUSTOM_ID: theology-and-freedom-1
      :END:

1. Liberation
2. LIBERATION THEOLOGY

- That very emphasis---liberating the captives---names the most
  important field of theology in the last half-century.
- Liberation theology first drew wide attention in the United States in
  connection with “black liberation.”
- James Cone's Black Theology and Black Power, published in 1969, made
  the blacks' liberation from their white oppressors its central
  theological theme and addressed whites with warnings rather than pleas
  for help.

3. Feminist criticism / liberation

- Looking beyond that, Rosemary Radford Ruether (a prolific theologian
  committed both to feminism and to Christianity) has written, All
  theologies of liberation, whether done in a black or a feminist or a
  Third World perspective, will be abortive of the liberation they seek,
  unless they finally go beyond the ... model of the oppressor and the
  oppressed.

4. Theology and the Religions

   - “Yes, I am a syncretist. But so are you. I know that I am a
     syncretist, but you don't know you are a syncretist because you
     have hegemonic power.
   - Other theologians of pluralism have been less insistent that
     multiple religions are different ways of saying the same thing. A
     Roman Catholic priest named Raimundo Pannikar, for example, born in
     Spain to a Hindu father and a Spanish mother, advocates a more
     strictly comparative approach.

***** World of many religions
      :PROPERTIES:
      :CUSTOM_ID: world-of-many-religions
      :END:

- *"syncretism":* "the amalgamation or attempted amalgamation of
  different religions, cultures, or schools of thought" --; Christianity
  itself syncretistic?

- **pluralism*:* truth in other religions? (John Hick)

- Raimundo Pannikar --; center of Christian theology moving south?

Notes:

Raimon Panikkar Alemany (November 2, 1918 -- August 26, 2010; also known
as Raimundo Panikkar and Raymond Panikkar) was a Spanish Roman Catholic
priest and a proponent of inter-religious dialogue. As a scholar, he
specialized in *comparative religion*.

*** Pivot to a new century (This is largely in ch. 9 above)
    :PROPERTIES:
    :CUSTOM_ID: pivot-to-a-new-century-this-is-largely-in-ch-9-above
    :END:

- Reject the status of history

- Christian collusion with profound sin

  1. serfdom of women
  2. slavery
  3. anti-semitism

**** Barth
     :PROPERTIES:
     :CUSTOM_ID: barth-1
     :END:

- rejection of cultural Christianity: Grace of Christ is supreme
- everything reflects biases and cultural assumptions
- attacked all human efforts to understand God

**** Anti-semitism interlude?
     :PROPERTIES:
     :CUSTOM_ID: anti-semitism-interlude-1
     :END:

- "God on Trial"
- Roots and implications
- God on trial trailer 1:37 min [[https://youtu.be/0W9uRPuo7hc]]
- complete: [[https://youtu.be/tD7v9phroGM]]
- [[https://youtu.be/5caAug5n8Zk]]
- cp. American experience with slavery?

**** Moving toward the 20th c.
     :PROPERTIES:
     :CUSTOM_ID: moving-toward-the-20th-c
     :END:

***** Reactions
      :PROPERTIES:
      :CUSTOM_ID: reactions
      :END:

- Maurice: rejecting both liberal and conservative, rational and
  romantic
- Darwin: raising the question "how to understand God's action in
  history in light of modern science
- Ritschl, Harnack & Troeltsch
- Valuing science and history and *also* maintaining the "truth" of
  Christianity

***** Schweitzer
      :PROPERTIES:
      :CUSTOM_ID: schweitzer
      :END:

- Renaissance man: physician, musician, "saint"?, major theologian
- Jesus was fundamentally an apocalyptic itinerant preacher
- "Quest for the historical Jesus" continues to this day

***** Nietzsche
      :PROPERTIES:
      :CUSTOM_ID: nietzsche
      :END:

- reject the weakness, lowliness, and pity of Christianity
- reject the notion that history is "advancing" --; "truth" is simply
  whatever a society agrees to call "true"
- fascination with history that had seemed to hold such promise at the
  beginning of the century seemed to end in despair

**** Rejection of cultural Christianity
     :PROPERTIES:
     :CUSTOM_ID: rejection-of-cultural-christianity
     :END:

***** Bonhoeffer
      :PROPERTIES:
      :CUSTOM_ID: bonhoeffer-1
      :END:

- Cheap Grace
- Religionless Christianity
- trailer to pbs documentary: 1:21 [[https://youtu.be/Cd_gmkypPGk]]
- [[http://www.pbs.md/bonhoeffer/]]

***** Bultmann & Existentialism
      :PROPERTIES:
      :CUSTOM_ID: bultmann--existentialism-2
      :END:

- Search for historical truth is fruitless
- There is no "human nature" to find
- p. 257

**** Existentialism and Fundamentalism
     :PROPERTIES:
     :CUSTOM_ID: existentialism-and-fundamentalism-1
     :END:

***** Existentialism's impact
      :PROPERTIES:
      :CUSTOM_ID: existentialisms-impact-1
      :END:

Bultmann's “left-wing” followers, like the American Schubert Ogden, have
concluded that Christianity concerns only the possibility of a new way
of existing.

***** American response
      :PROPERTIES:
      :CUSTOM_ID: american-response-3
      :END:

***** Reinhold Niebuhr:
      :PROPERTIES:
      :CUSTOM_ID: reinhold-niebuhr
      :END:

Christian realism "Man's capacity for justice makes democracy possible;
but man's inclination to injustice makes democracy necessary."

#+BEGIN_HTML
     <p class="verse">
     God, grant me the serenity to accept the things I cannot change,<br />
     The courage to change the things I can,<br />
     And the wisdom to know the difference.<br />
     </p>
#+END_HTML

cf. [[https://en.wikipedia.md/wiki/Serenity_Prayer]]

***** Christ and culture
      :PROPERTIES:
      :CUSTOM_ID: christ-and-culture-1
      :END:

Richard Niebuhr: Christian ethicist: /Christ and Culture/

- *Christ against Culture:* For the exclusive Christian, history is the
  story of a rising church or - Christian culture and a dying pagan
  civilization.
- *Christ of Culture:* For the cultural Christian, history is the story
  of the Spirit's encounter with nature.
- *Christ above Culture:* For the synthesist, history is a period of
  preparation under law, reason, gospel, and church for an ultimate
  communion of the soul with God.
- *Christ and Culture in Paradox:* For the dualist, history is the time
  of struggle between faith and unbelief, a period between the giving of
  the promise of life and its fulfillment.
- *Christ Transforming Culture:* For the conversionist, history is the
  story of God's mighty deeds and humanity's response to them.

**** Evangelical & Catholic?
     :PROPERTIES:
     :CUSTOM_ID: evangelical--catholic
     :END:

***** Evangelical
      :PROPERTIES:
      :CUSTOM_ID: evangelical-1
      :END:

- United States. Evangelical theology, with a renewed emphasis on the
  authority and often the literal inspiration of the Bible, also
  continues to be an important force in American theology, but it has
  generally reaffirmed the views Charles Hodge and Benjamin B. Warfield
  developed in the nineteenth century rather than producing new ideas.

***** Roman Catholic response
      :PROPERTIES:
      :CUSTOM_ID: roman-catholic-response-1
      :END:

- Rahner said that there is a fundamental mystery, a matter of religious
  faith, at the heart of all human understanding.

- Vatican 2: Pilgrim people: define “the church” not as the hierarchy of
  pope and bishops but as the whole “pielgrim people of God.”

  #+BEGIN_QUOTE
    The joys and the hopes, the griefs and the anxieties of the men of
    this age, especially those who are poor or in any way afflicted,
    these are the joys and hopes, the griefs and anxieties of the
    followers of Christ.
  #+END_QUOTE

  [[http://www.cctwincities.md/document.doc?id=62]]

*** Notes
    :PROPERTIES:
    :CUSTOM_ID: notes-1
    :END:

**** Old Presentations
     :PROPERTIES:
     :CUSTOM_ID: old-presentations-1
     :END:

[[317-20thc-pt2]] 317-20thc-pt2

**** Figures
     :PROPERTIES:
     :CUSTOM_ID: figures
     :END:

***** Tillich
      :PROPERTIES:
      :CUSTOM_ID: tillich
      :END:

***** 2nd Vatican Council
      :PROPERTIES:
      :CUSTOM_ID: 2nd-vatican-council
      :END:

**** Tentative view: current scene
     :PROPERTIES:
     :CUSTOM_ID: tentative-view-current-scene
     :END:

***** Hope & eschatology
      :PROPERTIES:
      :CUSTOM_ID: hope--eschatology-1
      :END:

[[placher-20th]] placher-20th

***** Theology and recent philosophers
      :PROPERTIES:
      :CUSTOM_ID: theology-and-recent-philosophers
      :END:

***** Theology and the secular
      :PROPERTIES:
      :CUSTOM_ID: theology-and-the-secular-1
      :END:

***** Liberation theology
      :PROPERTIES:
      :CUSTOM_ID: liberation-theology-2
      :END:

***** Theology and the religions
      :PROPERTIES:
      :CUSTOM_ID: theology-and-the-religions-1
      :END:

*** Extras ?
    :PROPERTIES:
    :CUSTOM_ID: extras-
    :END:

**** Readings
     :PROPERTIES:
     :CUSTOM_ID: readings
     :END:

Theology, identity, and Liberation 1960-2010

- social upheavals of 1960's:

  - upward social mobility
  - increasing cross-cultural inter-actions
  - dismantling entrenched gender roles
  - race & class issues

notes:

- cf. my listening to Dom Helder Camara: to white peace activists
  (Clergy against the war) --; that his people didn't know if they would
  die of hunger the next day. Their priorities were different.
- identification with culture: doing church on Facebook?

**** Readings
     :PROPERTIES:
     :CUSTOM_ID: readings-1
     :END:

- Martin Luther King Jr.
- James H. Cone
- Delores Williams
- Rosemary Radford Ruether
- Gustavo Gutiérrez
- Leonardo Boff
- Ivan Petrella
- John Mbiti
- C.S. Song
- Evgeny Barabanov
- John Milbank

**** Readings
     :PROPERTIES:
     :CUSTOM_ID: readings-2
     :END:

- Eberhard Jüngel
- Sarah Coakley
- Jürgen Moltmann
- Wolfhart Pannenberg
- David Bentley Hart
- Mercy Amba Oduyoye
- Lesslie Newbigin
- John Polkinghorne
- Elizabeth Johnson

**** Identity
     :PROPERTIES:
     :CUSTOM_ID: identity
     :END:

Use of social sciences & philosophy

- to be black?
- woman?
- hispanic?

Too much reliance on social science (non-Christian disciplines)

**** Current Scene
     :PROPERTIES:
     :CUSTOM_ID: current-scene
     :END:

- from "white western males" to a global enterprise
- sources for reflection changing
- contemporary science is breath-takingly changing (exponentially)
- responses to suffering & death
- how many are the disciplines in the contemporary university

  - e.g. politics, economics,

Notes: cf. Bp from Aoteoroa re. the ocean

Perhaps brainstorm the disciplines in the room, or in the university

**** Note: Recent Philosophies
     :PROPERTIES:
     :CUSTOM_ID: note-recent-philosophies
     :END:

- logical postivism
- Wittgenstein:
- Karl Jaspers: Psychology --; "Axial Age"
- n.b. important contribution of e.g.: Freud, Jung, William James,
  Adler, Fowler, others
- Ethics: e.g. situational ethics, moving away from principled /
  universal ethics

Notes: Karl Theodor Jaspers (German: [ˈjaspɐs]; 23 February 1883 -- 26
February 1969) was a German-Swiss psychiatrist and philosopher who had a
strong influence on modern theology, psychiatry, and philosophy. After
being trained in and practicing psychiatry, Jaspers turned to
philosophical inquiry and attempted to discover an innovative
philosophical system. He was often viewed as a major exponent of
existentialism in Germany, though he did not accept the label.

--------------

Tractatus Logico-Philosophicus Quotes (showing 1-30 of 63) “Whereof one
cannot speak, thereof one must be silent.” ― Ludwig Wittgenstein,
Tractatus Logico-Philosophicus tags: philosophy, taoism

“Death is not an event in life: we do not live to experience death. If
we take eternity to mean not infinite temporal duration but
timelessness, then eternal life belongs to those who live in the
present. Our life has no end in the way in which our visual field has no
limits.” ― Ludwig Wittgenstein, Tractatus Logico-Philosophicus

We feel that even if all possible scientific questions be answered, the
problems of life have still not been touched at all.” ― Ludwig
Wittgenstein, Tractatus Logico-Philosophicus tags: life, philosophy,
science

For an answer which cannot be expressed the question too cannot be
expressed.

The riddle does not exist.

If a question can be put at all, then it can also be answered.” ― Ludwig
Wittgenstein, Tractatus Logico-Philosophicus

Ethics and aesthetics are one.” ― Ludwig Wittgenstein, Tractatus
Logico-Philosophicus

Language disguises the thought; so that from the external form of the
clothes one cannot infer the form of the thought they clothe, because
the external form of the clothes is constructed with quite another
object than to let the form of the body be recognized.” ― Ludwig
Wittgenstein, Tractatus Logico-Philosophicus tags: language

Language disguises thought.” ― Ludwig Wittgenstein, Tractatus
Logico-Philosophicus

**** Language
     :PROPERTIES:
     :CUSTOM_ID: language
     :END:

- later Wittgenstein: "Language games"
- Derrida: "postmodern": "incredulity toward metanarratives"
- 2 world wars, the Holocaust (Shoah), globalization
- "process theology" (Whitehead) --; ecology, systems theory, ...;

Notes:

postmodern as *suspicious of any single storyline dominating the whole
of world history* cf. Hegel

“The problems are solved, not by giving new information, but by
arranging what we have known since long.” ― Ludwig Wittgenstein,
Philosophical Investigations tags: information, knowledge, problems

Philosophy is a battle against the bewitchment of our intelligence by
means of language.” ― Ludwig Wittgenstein, Philosophical Investigations

A picture held us captive. And we could not get outside it, for it lay
in our language and language seemed to repeat it to us inexorably.” ―
Ludwig Wittgenstein, Philosophical Investigations tags: isolation,
language, philosophy, picture, solipsism

The face is the soul of the body.” ― Ludwig Wittgenstein, Philosophical
Investigations

If I have exhausted the justifications, I have reached bedrock and my
spade is turned. Then I am inclined to say: 'This is simply what I do.”
― Ludwig Wittgenstein, Philosophical Investigations

So in the end, when one is doing philosophy, one gets to the point where
one would like just to emit an inarticulate sound.” ― Ludwig
Wittgenstein, Philosophical Investigations tags: philosophy

Language is a labyrinth of paths. You approach from one side and know
your way about; you approach the same place from another side and no
longer know your way about.” ― Ludwig Wittgenstein, Philosophical
Investigations tags: language
