* Presentations
file:317-preliminary.md introductory
file:317-background.md 5 themes, philosophical issues
file:317-philosophical.md review basic themes, Reformation vocab
file:317-erasmus.md repeat + quote Erasmus
file:317-radical-reformation.md Radical Reformation
file:317-counter-governance.md Counter-reform, Calvin
file:counter-reformation.md
file:317-calvinism.md Calvinism
file:Calvin-pt1.md
file:317-reasoning.md Rationality
file:317-age-reason.md Age of reason
file:317-enlighten-city.md Enlightenment to city on a hill
file:enlightenment-city-revisit.md
file:enlightenment-18thc.md
file:city-on-hill.md
file:317-great-awakening.md bare bones, Covenant, Great awakening
file:317-romantic.md Romantic era
file:317-trust-history.md ch. 17, trust in history
file:placher-20th.md
file:end-of-history.md
file:317-barth.md ch. 18, Barth, Bonhoeffer
file:317-into20thc.md into 20th c.
file:317-early-20thc.md as above
file:317-20thc-pt1.md
file:317-20thc-pt2.md
* New Presentations 2021
** Introductions
** Background  
*** Preface
**** What is "post-liberal"
     - title of course is "modern" -- initial working definition -- more to come -- it is the period from the Reformation to the 19^{th}-20^{th} centuries
     - modern period is over and must be "transcended"
     - not foundational
     - not confessional
     - how we read the Bible
     - a whole series of Theologians: the purpose of this course is that  you would begin to develop some awareness of who these theologians were and are in our post-modern period
     - major emphasis on " *conversation*" (narrativity)
     - to enter the conversation will require some awareness of philosophy
     - in order to truly enter the post-modern conversation we must have had conversations with the major figures of the past (our readings)
*** Introduction
**** Limitations 

      - what do we know?
      - what is history, change
      - what is "modern"
      - what is "Christian thought"
**** Some clarifications
     - history of Christian theology not genral hx, intellectual hx, etc.
     - "theology" = "systematic reflection on one's faith"
     - need to select and leave things out
*****  Some basic themes
 N.B. that these are framed in the form of either/or, yin/yang, a continuum between 2 extremes. This itself may be a limitation of the "western" tradition.

 We will return to these throughout the course.

      1. Humanity and Divinity of Christ
      2. Reason and revelation
      3. Works and Grace
      4. Spirit and Structure
      5. Church and State
*** On the eve of the modern period
**** 14^{th} c.
    - overly complex theological debates leading to doubting or disgust with the established church etc.
    - shift from God to Human?
    - What going on in period? plague, decimation, /memento mori/
**** Define "realism" and "nominalism"
     - Figures: Aquinas, Duns Scotus, Bonaventure, William of Ockham
     - Ockham's "razor" -- having to do with what we can "know" (good eg. on p. 140)
**** Nominalism vs. Realism (philosophical concepts)
 - the really real vs. knowing the individual rather than the universal
 - cf. John Duns Scotus
 - William of Ockham: showing reason's limitations
 - Ockham's "razor"
**** 
 file:http://www.tournamentpokeredge.com/wp-content/uploads/2015/02/occam-300x179.jpeg
**** 
 file:https://yourspiritualquest.files.wordpress.com/2018/05/ockhams-razor.jpg?w=900
**** Possible critique?
 file:https://i2.wp.com/theethicalskeptic.com/wp-content/uploads/2019/11/simple-pathways.png?resize=552%2C290&ssl=1    
**** path to salvation
 - reflecting the particular, we contribute to the salvicfic effect (Pelagian?)
 - later Martin Luther was Augustinian trained as *nominalist*
 - Meister Eckhart (God's spark within us) n.b. 14th c. *mystical* traditions (/tradition where metaphysics is more controversial than sex/)
**** councils and rebels
 - Avignon etc. competing popes
 - church corruption
 - dissenters and reformers experienced as betrayers of sacred truth -- burning of John Hus (1410)
 - John Wycliffe in England (foundation for protest against church authority)
 - Nicholas of Cusa defended pope's authority from a mystic point of view
**** toward hunmanism and simple piety
**** rise of Renaissance
***** (art not theology lay at the heart of the movement)
  file:http://4.bp.blogspot.com/-QOR43_35H4c/URKBrTEcIUI/AAAAAAAAAv8/CRrAjAL2U50/s1600/Renaissance.jpg 
***** rise of /Modern Devotion/ "devotio moderna"
      - centered in what would become the Netherlands, ordinary Christians forming community to "devote themselves to prayer and charity"
      - "beginnings of a new kind of Christian ideal"

  file:https://i.ytimg.com/vi/jpi3cGzWsGk/maxresdefault.jpg
***** "nominalism had raised basic questions about the nature of the order (the world) we see around us."
** Early Reformation
*** 5 Themes
**** Humanity / Divinity of Christ
  - John 1  (NRSV) 1 In the beginning was the Word, and the Word was with God, and the Word was God. 2 He was in the beginning with God. 3 All things came into being through him, and without him not one thing came into being. What has come into being 4 in him was life, ...
  - Matthew 13:55 Is not this the carpenter’s son? Is not his mother called Mary? And are not his brothers James and Joseph and Simon and Judas?
**** Reformers and ... 
  - what is the role of free will?
  - does justification happen instantaneously or gradually?

**** Spirit and Structure
  - Romans 8:2 For the law of the Spirit of life in Christ Jesus has set you free from the law of sin and of death.
  - Clearly structure of some kind was important to the New Testament church, Timothy relates the importortance of bishops, Luke/Acts emphasizes the importance of 12 Apostles.
**** Reformers and ...
  - is Spirit primary? or Scripture?
  - If community is led by Spirit does it need to follow ordinary rules of society?
**** Reason and Revelation
     - Romans 16:25  Now to God who is able to strengthen you according to my gospel and the proclamation of Jesus Christ, according to the revelation of the mystery that was kept secret for long ages
     - Jesus himself was masterful in reasoning with religious leaders who sought to argue against him.
**** Reformers and ...
  - /sola scritura/ vs. scripture and tradition
  - is Scripture the only authority or the "highest" authority?
**** Works and Grace
  - 2 Timothy 1:9 who saved us and called us with a holy calling, not according to our works but according to his own purpose and grace. This grace was given to us in Christ Jesus before the ages began,
  - James epistle seems to praise good works
**** Reformers and ...
  - justification by grace alone, works are of no use
  - gradual sanctification manifest through works

**** Church and State
  - Romans 13 Let every person be subject to the governing authorities; for there is no authority except from God, and those authorities that exist have been instituted by God.
  - Jesus was executed because he didn't obey authorities.
**** Reformers and ...
  - Luther essentially conservative with regard to civil authorities
  - others understood the Reform agenda to be revolutionary
  - pacifism of Mennonites


*** Questions and issues
    - new worlds, discovery
    - cf. Michener pp on 1500's
    - "reform" implies what?
*** Reading from Michener's /The Source/
 Illustrating the wider context of this period.
**** Excerpts from Luther's "Freedom of a Christian"

  - https://sites.google.com/site/relg317f15/

  - http://richard-hooker.com/sites/worldcultures/REFORM/FREEDOM.HTM
**** 
  - A Christian man is the most free lord of all, and subject to none, a Christian man is the most dutiful servant of all, and subject to every one.
  - "faith has appeared to many to be an easy thing"
  - "Man is composed of a twofold nature, a spiritual and a bodily."
  - (recognizing that scriptural passages can be found to seem to support opposites perspectives)
  - outward signs (vestments etc.) "profit nothing"
  - "One thing, and one alone, is necessary for life, justification, and Christian liberty; and that is the most holy word of God, the Gospel of Christ."
**** 
  - this faith can reign only in the inward man
  - every Christian by faith if "lord of all things" but in "corporeal power" he is subject to the earthly powers
  - the "outward man" ... must not take his ease; ... exercise, fastings, etc.
  - enormous folly ... when a man seeks, without faith, to be justified and saved by works...
  - ceremonies are but "preparations for building or working" to be "laid aside."
  - "Thus, too, we do not contemn works and ceremonies -- nay, we set the highest value on them; but ..."


*** 1500's
 - epigram re. we are "becoming" 
 - Luther (in all his complexity) and his struggles
*** Luther
**** father of Reformation
  Who was this person who stands so huge at the beginning of our period?

  https://prezi.com/yfmiihckhjj0/martin-luther-reformation/

**** Luther against the world
  - near contemporary = Columbus discovering new world
  - as *nominalist* he taught that with help of grace we earn our own salvation
  - *Purgatory* as a concept and related *indulgences*
  - 95 theses
  - L. gained support from humanists (Renaissance) -- cf. Erasmus
  - Erasmus sought to clear away corruption and restore simple ethical Christianity
  - L.'s conservatism on social issues
  - Thomas Munzer (trust in Spirit) conflict with L. -- he saw the end times and 2nd Coming
** Reform Developments
*** Erasmus
 Several quotes to illustrate "Humanism"

 - cf. http://oll.libertyfund.md/people/desiderius-erasmus

*** Lutheran developments
 - cf. ch. 14 for Zwinglian developments
 - justification by faith (though we remain sinners) cf. P. Wismer's analogy re. looking at the board of writing but "seeing" a clean board
 - continued debate about the role of grace and our participation with it
 - increasingly "faith" meant an "assent to a set of propositions." p. 167

*** Zurich and Zwingli
 - Z. shared L.'s desire for reform, but different emphasis
 - Z. started with absolute authority of scripture
 - Z. partly allied with Erasmus in desire to cleanse the church
 - Z. and L. in different political environments (princedom vs. democracy)
 - infant baptism?
 - eucharist /consubstantiation/ vs. /symbolize/
*** radical reformation
 - an "odd collection of pacificsts and violent revolutionaries, eccentric individualists and tightly knit communities, biblical literalists and those who followed the inner voice of the Spirit"
 - anabaptists ("rebaptizers")

   * Radical Reformation
*** The Schleitheim Confession Of Faith, 1527
 - a People set apart (sect)
 - the "ban"
 - a "remembrance" for the holy people
 - the "sword" is for the world, not the holy people
*** Humanism
**** Erasmus
  Several quotes to illustrate "Humanism"

  - cf. http://oll.libertyfund.md/people/desiderius-erasmus
  - need for a philosopher of the kitchen
  - for peace and against war
*** Sacraments

**** 3 Competing Definitions
***** Trent
  - Transubstantiation
  - Universal = Christ, outward appearance = bread and wine
***** Luther 
  - Consubstantiation
  - by the power of God both Christ and bread and wine present
***** Zwingli
  - (mere) symbol 
  - Humanist focus on the human effects, language
**** Sacrament is ...
  "Outward and visible sign of an inward and invisible grace"
  - one substance (Christ) with "accidents" (manifestations, "outward appearance") of bread and wine
  - But the power of God cannot be so determined and measured
  - In view of these passages we are compelled to confess that the words: "This is my body," should not be understood naturally, but figuratively,
  - option: not to define the "presence" 
*** Counter Reformation
**** Council of Trent
  - p. 173 notion of "justification" which many thought as a kind of property people have or don't, -- L. "no righteousness of our own but only share in Christ's righteousness"
  - Trent set forth doctrinal statements on Scripture and tradition, original sin, justification, and the sacraments that have provided the basis of Catholic theology ever since," laid foundation for reform
**** 
    - Scripture and tradition equally
    - L. had said original sin destroyed will, Catholics sought compromise
    - Justification as a "process" not instantaneous as L. thought
    - Sacraments and reform: 7 sacraments, transubstantiation, sacrifice on altar repeated, purgatory and indulgences (but warned re. abuse)


**** Jesuits and mystics
  - Don Quixote and Loyola (Knight for Christ)
  - S.J. sending missionaries world wide, adapting to customs of people they met
  - Carmelites (John and Teresa)

**** Continuing debates
  - Jesuits at center of response to Protestantism
  - "Aquinas had taught that we talk about God "analogically"
  - Port Royal Jansenists -- rigorous piety and trust in grace as opposed to Jesuits whom they saw as "Pelagian"
  - Pascal: genius of age ... conversion "Fire, God of Abraham ..." trust in grace while being well trained in reason as mathematician
  - Pascal defense of Christianity, but ultimately Pope ruled against Jansenist radical trust in grace (not own will)
  - Fenelon, "Quietism", Mme. Guyon = claiming that usual rules don't apply because of special relationship with God

*** Counter-Reformation
**** 5 themes
***** Humanity and Divinity of Christ:
         1. how fit the Catholic humanists in this?
*****  Reason and revelation: (What is true? Path to salvation?)
         1. cf. bible and tradition vs. bible alone
*****     Works and Grace:
         1. maintaining a tension,
         2. cp. Contarini with similar exp. to Luther
**** 
***** Spirit and Structure: canons and "reforms" aimed at structure,
         1. cf. also the turmoil over Carmelites
*****     Church and State:
         1. nb that German Lutherans overthrew state authority, tradition that state followed ruler,
         2. Rome pretensions to the Roman Empire (left over from high middle ages synthesis)

*** Gods-governance
**** Geneva
     - Europe being divided up
     - Radical reformation in pockets
     - Calvin inherited what Zwingli had begun
     - looked on as "the Protestant Rome"
**** Calvin
  file:../img/john-calvin.jpg
***** 								    
  https://prezi.com/ympfwolg3_no/john-calvin-the-greatest-exegete-of-the-reformation/
**** Catholic point of view 
  http://www.newadvent.md/cathen/03195b.htm catholic point of view
**** Emphasis
     - where Luther's emphasis on grace and justification
     - Calvin on covenant (in the lineage of Abraham)
     - the government of society bound up with notion of covenant
     - a "civil" use of law as well as "theological" (188)
****  questions/focus
         - "reform" as in "reformed life"
         - organizing society, community
         - what is community?
         - 39 articles
         - "Puritans" 
**** epithoughts
  - "Calvinist in polity" -- huge influence on English world
  - Knox and Calvin and the "reformed" tradition
  - Calvin retreating from France to Geneva
  - reading Calvin elicits not an emotional response but a cumulative one from the systematic presentation p 188
**** 
  - response to (free) grace is a *reformed* life (thus the name)
  - in contrast to Luther's distinction between law and gospel, Calvin thought we stood in the same convenant as Abraham (189)
  - "Reflections on how we come to be saved led to the doctrine of predestination (189 ff.)
  - https://en.wikipedia.md/wiki/The_Private_Memoirs_and_Confessions_of_a_Justified_Sinner
  - theology of sacraments: cf. *Martin Bucer* (large influence)
    - sought position between Luther and Zwingli

**** Include for Wed. readings
  - Westminster confession
  - 39 articles
***** Cp these two influences from Reformed tradition

***** 

** Calvinism
*** Overview
****  questions/focus
      - "reform" as in "reformed life"
      - organizing society, community
      - what is community?
      - 39 articles
      - "Puritans" 
*** Calvinism
**** Calvinism
***** Discipline of the community
  - (191) Community maintain discipline by regulating who come to communion
  - (191) organization of community (Geneva) ministers, teachers, elders, deacons ... "presbytery"
**** Calvinism
***** Church and State
  - (192) Calvin allowing for working against civil authority when they betray the faith
  - John Knox in Scotland "seized" on those principles in his energy opposing the English
  - (193) France, Scotland, then England Calvinists thought about how to oppose an unjust society
  - Scotland corrupt church 193, thus as in France political conditions drove Calvin's followers
**** Calvinism
***** "Orthodoxy" 
  - in Amsterdam with Arminius -- in move against him, the church solidified its "orthodoxy" and *thus froze positions that earlier had been nuanced*
  - p. 194 table of *5 basic principles of Calvinist orthodoxy*
  - reading Calvin elicits not an emotional response but a cumulative one from the systematic presentation p 188
**** Calvinism
***** now reform of the person not of the church
  - response to (free) grace is a *reformed* life (thus the name)
***** Predestination 
  - clearly we are not saved by good works, therefore it has to be God's decision
  - "Reflections on how we come to be saved led to the doctrine of predestination (189 ff.)
  - single? double?
  - https://en.wikipedia.md/wiki/The_Private_Memoirs_and_Confessions_of_a_Justified_Sinner

**** epithoughts
  - "Calvinist in polity" -- huge influence on English world
  - Knox and Calvin and the "reformed" tradition 

*** Calvin
  #+ATTR_REVEAL: :frag (appear)
  - clear & systematic mind at work
  - overpowering sense of God's glory
  - Plato: we sin out of ignorance. Calvin: we are ignorant because of sin
  - not so much Luther's law & Gospel / standing in a continuous *covenant* from Abraham
  - *predestination*
  - obedience to constituted authority

  #+BEGIN_NOTES
  Notes:

  Compare Luther & Calvin
  - Calvin Luther built on his personal conversion
    - Calvin was private and rarely personal, rather logical
  - Luther sin and need for justification
    - Calvin God's glory and power
  - Law and gospel
    - vs Covenant (Abraham)
  - Calvin: God’s grace alone saves us, but in gratitude we then try to do God’s will. Sanctification before justification
  - Being saved by God's grace alone leads to a doctrine of predestination Surely it is not by good works but God's doing completely
  - Contrary to Luther and Zwingli he preferred to be vague about nature of presence in Eucharist
  - Regulate morality? Punish those who don't prove to be reformed? Church maintains discipline?
  #+END_NOTES
**** Sacraments
  #+ATTR_REVEAL: :frag (appear)
  - importance of Martin Bucer as a bridge figure
  - insisting on Christ's presence (not a particular understanding)
  - the church regulating its own life (discipline)
  - normalcy of church/state overlap
*** Knox & Arminius
  #+ATTR_REVEAL: :frag (appear)
  - possibility? necessity? to rebel against authority that demands betrayal of faith
  - prophets to denounce injustice & call to action (Knox in Scotland)
  - Arminians argued that one could refuse grace -- in opposition to predestination of Calvinism (cf. p. 194)

  #+BEGIN_NOTES
  Notes:

  Note how when one focuses on just one truth, the overall whole gets distorted.

  Compare touching an elephant blind-folded
  #+END_NOTES
*** Reformation in England
  #+ATTR_REVEAL: :frag (appear)
  - http://sermons-fr-hathaway.blogspot.com/2017/10/anglican-talkmd.html for a talk I gave at the Oratory last fall
  - divorce? leading to separation from Pope's authority
  - Lutheran, Calvinist, Catholic
  - Thomas Cranmer & *Book of Common Prayer
  - 39 articles allowing for various readings
  - Richard Hooker: "thoughtful & moderate"
*** From Puritans to Quakers
  #+ATTR_REVEAL: :frag (appear)
  - Puritan party reacting to the conservative (i.e. not-sufficiently-reformed aspects of Elizabethan/Hooker compromise
  - all practice and belief must stem from New Testament
  - material success a sign of Grace?
  - voice of C of E: William Laud, John Donne, Lancelot Andrewes
  - Hooker argued that "tradition" has an important part to play in authority of the Church
  - authority reside in Scripture alone? or
  - in inner *experience*? -- Society of Friends (Quakers)

** Beyond Geneva
*** Bucer 
 - centrale figure of Reformation? 190
 - sought to avoid being explicit about sacraments (Luth/Zwingli)
 - stands out in the figures for his tolerance
 - theology of sacraments: cf. *Martin Bucer* (large influence)
   - sought position between Luther and Zwingli
*** Knox
 - connected the struggle of Scotland against England with Reformed theology
 - what is the role of faithful viz a viz oppressive society?
 - synod of Dort (5 principles) "uncompromising" 194
*** England
 - author disputes that Henry VIII "started" Anglican church
 - tradition of reform went back a century or more
 - Thomas Cranmer as Archbishop was the prime mover --
*** 
 - particularly in focus on worship and /The Book of Common Prayer/ (together with the later emerging /King James Bible/)
 - /Lex orandi, lex credendi/ is a fundamental character of Anglicanism (relation between worship and belief)

 - "Anglican (195) could hold any theology from near Catholic to Calvinist"

*** From Puritans to Quakers
 - Puritans to "purify" the church -- particularly with regard to worship (only scripture)
 - "purifying" church, worked hard and saved their money
 - as "character" working hard (capitalism, spirit of U.S.) -- cf. because of impact on US
 - Puritans and Capitalism (Weber)
*** 
 - Anglicans who reacted to Puritans: John Donne, William Laud, Lancelot Andrewes, *Richard Hooker* and the /via media/
 - (p. 197) "Hooker did not accept the Roman Catholic position that tradition has an authority independent of Scripture, but he did use it as a reliable guide to the interpretation of Scripture, while the Puritans wanted to read their Bibles unencumbered by traditional assumptions."
 - Oliver Cromwell and again the mixing of politics and religion

 - moderate and radical Puritans -- radical appealing to individual experience (of Spirit) cf. Quakers (George Fox)

*** Compare Westminster & 39 articles


** Enlightenment
*** Rationality 
 #+ATTR_BEAMER: :overlay +-
 - History of a metaphor
 - Arguments for God: /a priori/ and /empirical/
 - Calvin's systematic development of the faith position *sovereignty of God*
 - Quakers and Nonconformists: where is highest authority placed?
 - Descartes: from scientific method to rational conclusions
*** Religion and the Age of Reason
*** 
 file:./img/sf-quakes.jpg
*** 
 file:./img/sfeq06_01.jpg
*** 
 file:./img/lisbon-burning.jpeg
*** 
*** 
 file:./img/Lisbon-earthquake-1755.jpg
*** Earthquakes and God's will
    - a tale of 2 earthquakes
    - he found the evidence for his belief in nature rather than in the Bible; he doubted a good bit of traditional doctrine—and he didn’t treat religion all that seriously.
    - Revivals but at heart a move from God to human beings

*** From God-centered to Human-centered

    - 5 catalysts for change
    - at the very time of success in discovery and technology, reason seemed to reach its end of life
    - changing metaphor from Anselm to Descartes
*** Religion of Reason
    - Cartesian coordinates
    - can a religion be built on Doubt?
    - No man shall ever be kept out of Heaven … if he had but an honest and good heart, that was ready to comply with Christ’s commandments
    - God is more inward to us than our very souls
*** Descartes to Newton
    - Newton: God’s "immensity" stretching infinitely in all directions and unchanged for all eternity (cp. changing metaphor)
    - while retaining religion, it is no stripped of the "supernatural"
    - Church of England would keep its theology vague enough to include as many groups as possible and tolerate the presence of some dissenting groups like Anabaptists and Quakers, though not Catholics
*** Locke and Deists
    - Nearly all the attitudes of the time came together in John Locke
    - https://www.youtube.com/watch?v=kItXvJLnTtk 
    - Many Deists brought to bear on the biblical miracle stories all the prestige of the scientific discovery of laws
    - Deists distrusted appeals to authority and the miraculous, but they also turned away from anything beyond natural religion in part for moral reasons.

*** Pietists and Methodists

     - "*Enthusiasm*" was a dirty word in the eighteenth century.
     - story begins in Germany, where Lutheran orthodoxy had increasingly defined faith as assent to a set of doctrines
     - Lutherans suspect any call to moral improvement as a move toward works-righteousness.
     - Methodism with a "method" for holiness
     - Wesley and Whitefield changed the shape of popular religion in England and North America, but they made little impact on the attitudes among most intellectuals

*** The end of Reason

    - Hume
    - Rousseau
    - Kant

*** Religion and the Age of Reason
****  
     :PROPERTIES:
     :reveal_background: http://www.sciencephoto.com/image/167272/large/E3700104-1755_Lisbon_earthquake-SPL.jpg
     :reveal_background_size: 1100px
     :reveal_background_trans: slide
     :END:      



  #+BEGIN_NOTES
  http://www.sciencephoto.com/image/167272/large/E3700104-1755_Lisbon_earthquake-SPL.jpg
  https://lifeafter40.net/wp-content/uploads/2014/12/lisbon-burning-768x518.jpeg

  http://cdn.history.com/sites/2/2016/04/Post-and-Grant-Avenue.-Look-E.jpeg
  San Francisco earthquake 1906
  lead to the rise of Pentecostalism
  preaching at Azusa, CA

  https://lifeafter40.net/the-1755-lisbon-earthquake-the-start-of-atheism/
  For an account of how this gave birth to "atheism" -- read to get a feel for it

  file:./img/sf-quakes.jpg
  file:./img/sfeq06_01.jpg
  file:./img/lisbon-burning.jpeg
  file:./img/Lisbon-earthquake-1755.jpg
  #+END_NOTES

**** 
     :PROPERTIES:
     :reveal_background: https://lifeafter40.net/wp-content/uploads/2014/12/lisbon-burning-768x518.jpeg
     :reveal_background_size: 1100px
     :reveal_background_trans: slide
     :END:      

**** 
     :PROPERTIES:
     :reveal_background: http://cdn.history.com/sites/2/2016/04/Post-and-Grant-Avenue.-Look-E.jpeg
     :reveal_background_size: 1100px
     :reveal_background_trans: slide
     :END:      



**** Earthquakes and God's will
  Voltaire
  #+ATTR_REVEAL: :frag (appear)
     - a tale of 2 earthquakes
     - he found the evidence for his belief in nature rather than in the Bible; he doubted a good bit of traditional doctrine—and he didn’t treat religion all that seriously.
     - Revivals but at heart a move from God to human beings
  #+BEGIN_NOTES
  Do we explain these by reference to God? No? We are inheritors of Enlightenment.

  p. 203 it is the *shifting of place* re. God and world -- what is important
  #+END_NOTES
**** From God-centered to Human-centered
     - 5 catalysts for change (204)
  #+ATTR_REVEAL: :frag (appear)
       1. wars of religion
       2. Europe divided
       3. philosophical attitudes encouraged questioning tradition
       4. science seemed to being moving from one accomplishment to another ...
       5. nationalism taking root, centralizing power
**** 
     - at the very time of success in discovery and technology, reason seemed to reach its end of life
*** Descartes to Newton
**** Newton on religion
  #+ATTR_REVEAL: :frag (appear)
     - Newton: God’s "immensity" stretching infinitely in all directions and unchanged for all eternity (cp. changing metaphor) (cp. Borges)
     - what was most important about religion was its morality  -- cf. Jefferson's approach (206)
     - while retaining religion, it is no stripped of the "supernatural"
     - "natural religion" (206)
     - Church of England would keep its theology vague enough to include as many groups as possible and tolerate the presence of some dissenting groups like Anabaptists and Quakers, though not Catholics
     #+BEGIN_NOTES
     cf. 3 parts of Anglican: hi, lo, broad
     #+END_NOTES
**** Borges
   Universal history is the history of a handful of metaphors
      - changing metaphor from Anselm to Descartes

   #+BEGIN_NOTES
   read from /Labyrinths/ "The fearful sphere of Pascal"
   #+END_NOTES

***** Locke and Deists
  #+ATTR_REVEAL: :frag (appear)
      - Nearly all the attitudes of the time came together in John Locke (207)
      - https://www.youtube.com/watch?v=kItXvJLnTtk 
      - Many Deists brought to bear on the biblical miracle stories all the prestige of the scientific discovery of laws (209)
      - Deists distrusted appeals to authority and the miraculous, but they also turned away from anything beyond natural religion in part for moral reasons.

***** Religion of Reason

   Descartes argued that knowledge would come only from doubting everything
  #+ATTR_REVEAL: :frag (appear)
      - can a religion be built on Doubt?
      - No man shall ever be kept out of Heaven … if he had but an honest and good heart, that was ready to comply with Christ’s commandments (205)
      - God is more inward to us than our very souls (205)

***** Pietists and Methodists
  #+ATTR_REVEAL: :frag (appear)
       - "*Enthusiasm*" was a dirty word in the eighteenth century. (210)
       - story begins in Germany, where Lutheran orthodoxy had increasingly defined faith as assent to a set of doctrines
       - Lutherans suspect any call to moral improvement as a move toward works-righteousness.
       - rise of *Pietism* (210)
       - Moravians and J. Wesley intersect (211)
       - Methodism with a "method" for holiness
       - Wesley and Whitefield changed the shape of popular religion in England and North America, but they made little impact on the attitudes among most intellectuals
       #+BEGIN_NOTES
       Read Wesley quote of his conversion p. 211

   nb. that for Wesley, too, morality was more important than doctrine
       #+END_NOTES

*** The end of Age of Reason

**** Hume
  #+ATTR_REVEAL: :frag (appear)
  - skeptic of scientific inference producing absolute knowledge
  - apply skepticism to argument from order; miracles; and others ...

**** Rousseau
  #+ATTR_REVEAL: :frag (appear)
  - doubting even *civilization* -- cf. /Emile/ raised as a *natural child*
  - follow self & respect others (214)
  - Lessing: story of 3 rings (214)

  #+BEGIN_NOTES
  see how we identify with the motto of Rousseau above
  #+END_NOTES

**** Kant
  #+ATTR_REVEAL: :frag (appear)
  - seeking necessity of religion apart from historical evidence
  - Pietist upbringing
  - his arguments *begin with ethics* -- /universal imperative/
  - like much of enlightenment thinkers: accepting God but nothing to do with most *doctrine*
  - summary (217)

  #+BEGIN_NOTES
  we ought to do the thing that we could make a universal law
  #+END_NOTES


** American Suite
*** The city on a hill
 - the *idea* of *denomination* really developed in the US
 - bewildering variety of developments in US (219)
*** 
 #+attr_html: :width 240px  
 file:./img/city-on-hill-01.jpg
***  
 #+attr_html: :width 240px  
 file:./img/winthrop.jpg
*** 
 #+attr_html: :width 240px  
 file:./img/calvin-resolutions.jpg
*** 
 #+attr_html: :width 240px  
 file:./img/4-prepare-for-action-1-peter-11316-50-728.jpg
*** 
 #+attr_html: :width 240px  
 file:./img/resolution-edwards.jpg
*** 
 #+attr_html: :width 240px  
 file:./img/resolved-to-live.jpg
*** 
 #+attr_html: :width 240px  
 file:./img/Masscolony.png
*** Key figures
 - Wesley & Whitefield
 - John Winthrop
 - Thomas Hooker
 - John Cotton
 - Solomon Stoddard
 - Jonathan Edwards
   - "Great Awakening"
*** (part 2) 
**** Rational Religion 
     - Jefferson & Franklin
     - William Ellery CHanning
**** Revivals
     - Lyman Beecher
     - Charles Finney

**** Revivals (cont)

    - Ann Lee & Quakers
    - Oneida community
    - Latter Day Saints
    - Seventh Day Adventists
**** Romanticism in America
     - Unitarians
       - William Ellery Channing
     - Transcendentalists
       - Ralph Waldo Emerson
     - Nevin & Schaff (Transform humanity)
     - Horace Bushnell (Attacking individualism)
**** Slavery & Black religion
     - Bushnell
     - Evangelicals in England, Quakers in America
     - the unfulfilled dream of Puritan America
*** 

*** Covenant
*** Great Awakening
** History dominant
*** Trust in History, progress, rational.
 The 19th c. began with a reaction against the perceived sterile rationalism of the
 Enlightenment and a trust that History itself was moving forward, upward, and in a better
 direction. Progress was inevitably being made through a kind of invisible Hegelian god­like
 hand. What evidence do you see, for and against the progress of history?
*** "Genius"
 The text notes that "A new spirit of nationalism created new interest in various national
 traditions ­­ the brothers Grimm scoured the countryside for old folktales, composers
 incorporated folk tunes in their symphonies." The previous chapter was titled "City on a Hill"
 and seemed to focus on the particular "genius" of the American experiment. Discuss the
 pros and cons of the "new spirit of nationalism" referenced in the 17th chapter.
*** Church and society (culture)
 /Christianity is radically not like society/
 *or*
 /Christianity is faith expressed through a society/

 - The 19th c. wrestled with these statements, both of which seem to be true in some respects.
 Where do we see them being reconciled in today's world?
*** Revelation
 Between the statement "The Bible is the very Word of God"
 and the statement
 "The Bible is an example of many kinds of literature, myth, preaching all mixed together but
 very much a human product"
 there is a great gulf.
 What would a middle ground look like?
 * Romantic era
*** Romantic period
 - appreciation of emotion and intuition
 - recovery and emphasis on national traditions (folklore)
 - over and against "natural religion"
*** Schleiermacher
 - persuade sophisticated friends not to reject religion
 - "every event is a miracle" "every intuition and every original feeling" is a revelation
 - religion based "entirely on the inner experience of the believer"
*** Coleridge
 - reject the tendency of 18th c. theology to base Christianity on argument
 - "factual accuracy of the Bible does not much matter, for it can give us Truth in the way a great poem can"
 - religion is good for the nation?
*** Hegel and reaction to him
**** Hegel
  - importance of HX,
  - each epoch has its own genius
  - learn from ideas you don't like e.g. "nationalism"
  - progress is messy
  - 3 moves: "dialectic"
  - art has a purpose (no to "art for art's sake"
  - institutions needed
  - growth will be painful
**** "anti-hegelians"
*****  Feuerbach
  - humans invent "God"
  - trivial?
***** Strauss
  - Gospels consist of "myths"
  - "to treat the Gospels as historically accurate would be to take metaphors and images as literal truth."
***** Marx
  - the philosophers have only /interpreted/ the world, in various ways; the point, however, is to /change it/.
**** S. Kierkegaard
  - furious production of books
  - /Either/Or/ & /Fear and Trebling/: give up our sentimental notions
  - enemies: the smug, bourgeousie
  - new ideas re. "love" that he mocked
  - "impossible choices"
  - Life lived forward but understood backwards
  - "leap of faith" in faith
  - 3 approaches to religion
    - aesthetic (beautiful)
    - ethical (rational)
    - religious (absurd)
*** State religion
**** Roman Catholic
  - 19th c. appreciation of middle ages
  - Napoleon's treaty with the Pope -- compromising the state? or the church?
  - Piux IX proclaiming /Immaculate Conception/ -- Pope "infallible"
  - Leo XIII speaking on society sounds like a socialist
  - but reacting to the age -- he condemned "modernists"
**** Church of England
  - had a set of virtues and faults opposite to those of Rome
  - "established" church
  - Newman: England would improve "were it vastly more superstitious, more bigoted, more gloomy, more fierce in its religion, than at present it shows itself to be."
**** Newman 
  - mistrust state control -- but also "liberal" sense that one could be indifferent to doctrine
  - "development" of doctrine
  - many truths we cannot prove (England an island?)
*** Moving toward the 20th c.
**** Reactions
     - Maurice: rejecting both liberal and conservative, rational and romantic
     - Darwin: raising the question "how to understand God's action in history in light of modern science
     - Ritschl, Harnack & Troeltsch
     - Valuing science and history and *also* maintaining the "truth" of Christianity
**** Schweitzer
     - Renaissance man: physician, musician, "saint"?, major theologian
     - Jesus was fundamentally an apocalyptic itinerant preacher
     - "Quest for the historical Jesus" continues to this day
**** Nietzsche
     - reject the weakness, lowliness, and pity of Christianity
     - reject the notion that history is "advancing" -- "truth" is simply whatever a society agrees to call "true"
***** fascination with history
  that had seemed to hold such promise at the beginning of the century seemed to end in despair


** "End" of history
*** Hope & Eschatology
  - reaction to Bultmann: viz. place of *Old Testament* for Christian theology
  - Schweitzer & others have shown the importance of *eschatology* for understanding New Testament
  - Pannenberg: Christian theology must understand itself in the world we live in
  - Dorothy Sölle: role of *suffering* in Theology
  #+BEGIN_NOTES
  Notes:

  OT use: p. 263/268.  One contra Bultmann, one MLK re. liberation

  Issue: use of OT in Christian theology
  - pre-figuring NT
  - superceded
  - needing figurative interpretation

  Wolfhart Pannenberg (2 October 1928 – 4 September 2014) was a German theologian. He has made a number of significant contributions to modern theology, including his concept of *history as a form of revelation centered on the Resurrection of Christ*, which has been widely debated in both Protestant and Catholic theology, as well as by non-Christian thinkers.

  She wrote a large number of books, including /Theology for Skeptics: Reflections on God/, /The Silent Cry: Mysticism and Resistance/ (2001) and her autobiography /Against the Wind: Memoir of a Radical Christian/ (1999). In /Beyond Mere Obedience: Reflections on a Christian Ethic for the Future/ she coined the term "Christofascist" to describe fundamentalists. Perhaps her best-known work in English was /Suffering/, which offers a critique of "Christian masochism" and "theological sadism". Sölle's *critique is against the assumption that God is all-powerful and the cause of suffering*; humans thus suffer for some greater purpose. Instead, God suffers and is powerless alongside us. Humans are to struggle together against oppression, sexism, anti-Semitism, and other forms of authoritarianism.
  #+END_NOTES
*** Philosophy
**** Recent Philosophies

  - logical postivism
  - Wittgenstein:
  - Karl Jaspers: Psychology -- "Axial Age"
  - n.b. important contribution of e.g.: Freud, Jung, William James, Adler, Fowler, others
  - Ethics: e.g. situational ethics, moving away from principled / universal ethics
  #+BEGIN_NOTES
  Notes:
  Karl Theodor Jaspers (German: [ˈjaspɐs]; 23 February 1883 – 26 February 1969) was a German-Swiss psychiatrist and philosopher who had a strong influence on modern theology, psychiatry, and philosophy. After being trained in and practicing psychiatry, Jaspers turned to philosophical inquiry and attempted to discover an innovative philosophical system. He was often viewed as a major exponent of existentialism in Germany, though he did not accept the label.

  ---------------

  Tractatus Logico-Philosophicus Quotes (showing 1-30 of 63)
  “Whereof one cannot speak, thereof one must be silent.”
  ― Ludwig Wittgenstein, Tractatus Logico-Philosophicus
  tags: philosophy, taoism

  “Death is not an event in life: we do not live to experience death. If we take eternity to mean not infinite temporal duration but timelessness, then eternal life belongs to those who live in the present. Our life has no end in the way in which our visual field has no limits.”
  ― Ludwig Wittgenstein, Tractatus Logico-Philosophicus

  We feel that even if all possible scientific questions be answered, the problems of life have still not been touched at all.”
  ― Ludwig Wittgenstein, Tractatus Logico-Philosophicus
  tags: life, philosophy, science

  For an answer which cannot be expressed the question too cannot be expressed.

  The riddle does not exist.

  If a question can be put at all, then it can also be answered.”
  ― Ludwig Wittgenstein, Tractatus Logico-Philosophicus

  Ethics and aesthetics are one.”
  ― Ludwig Wittgenstein, Tractatus Logico-Philosophicus

  Language disguises the thought; so that from the external form of the clothes one cannot infer the form of the thought they clothe, because the external form of the clothes is constructed with quite another object than to let the form of the body be recognized.”
  ― Ludwig Wittgenstein, Tractatus Logico-Philosophicus
  tags: language

  Language disguises thought.”
  ― Ludwig Wittgenstein, Tractatus Logico-Philosophicus 
  #+END_NOTES
**** Language
  - later Wittgenstein: "Language games"
  - Derrida: "postmodern": "incredulity toward metanarratives"
  - 2 world wars, the Holocaust (Shoah), globalization
  - "process theology" (Whitehead) -- ecology, systems theory, ...

  #+BEGIN_NOTES
  Notes:

  postmodern as *suspicious of any single storyline dominating the whole of world history* cf. Hegel


  “The problems are solved, not by giving new information, but by arranging what we have known since long.”
  ― Ludwig Wittgenstein, Philosophical Investigations
  tags: information, knowledge, problems

  Philosophy is a battle against the bewitchment of our intelligence by means of language.”
  ― Ludwig Wittgenstein, Philosophical Investigations

  A picture held us captive. And we could not get outside it, for it lay in our language and language seemed to repeat it to us inexorably.”
  ― Ludwig Wittgenstein, Philosophical Investigations
  tags: isolation, language, philosophy, picture, solipsism

  The face is the soul of the body.”
  ― Ludwig Wittgenstein, Philosophical Investigations

  If I have exhausted the justifications, I have reached bedrock and my spade is turned. Then I am inclined to say: 'This is simply what I do.”
  ― Ludwig Wittgenstein, Philosophical Investigations

  So in the end, when one is doing philosophy, one gets to the point where one would like just to emit an inarticulate sound.”
  ― Ludwig Wittgenstein, Philosophical Investigations
  tags: philosophy

  Language is a labyrinth of paths. You approach from one side and know your way about; you approach the same place from another side and no longer know your way about.”
  ― Ludwig Wittgenstein, Philosophical Investigations
  tags: language
  #+END_NOTES

*** Theology & the Secular
  - theology for church vs. for the secular world
  - John Polkinghorne
  - Ian Barbour
  - Theology: image of "wheel" vs. "matrix"
  - Harvey Cox: value in engaging the secular world (cf. Bonhoeffer)
  #+BEGIN_NOTES
  Notes:

  Relating God's action in the natural world to physics, biology, etc.

  cf. esp. awareness of natural environment. Reading of Genesis 1.

  Cox: avoid theology being a ghetto cut off from the world
  #+END_NOTES
*** Liberation Theology
  - Africa, Latin America: experience of being *oppressed*
  - 1960's "black liberation" in US: parallels between Israel's slavery in Egypt & slavery in modern world
  - MLK Jr. "Letter from Birmingham Jail" cp. "Barmen Declaration"
  - James Cone: "being black is not a matter of skin color"
  - Women's liberation:
  - Recognizing that both oppressed and oppressor need "liberating"
  #+BEGIN_NOTES
  Notes:

  cp. the new "Reclaiming Jesus"

  Nicaragua: teaching literacy with no books. Only at hand is bible. Finding the meaning there.
  #+END_NOTES
*** World of many religions
  - "syncretism" :: "the amalgamation or attempted amalgamation of different religions, cultures, or schools of thought" -- Christianity itself syncretistic?
  - *pluralism* :: truth in other religions? (John Hick)


  - Raimundo Pannikar -- center of Christian theology moving south?
  #+BEGIN_NOTES
  Notes:

  Raimon Panikkar Alemany (November 2, 1918 – August 26, 2010; also known as Raimundo Panikkar and Raymond Panikkar) was a Spanish Roman Catholic priest and a proponent of inter-religious dialogue. As a scholar, he specialized in *comparative religion*.
  #+END_NOTES
*** Readings 
  Theology, identity, and Liberation 1960-2010

  - social upheavals of 1960's:
    - upward social mobility
    - increasing cross-cultural inter-actions
    - dismantling entrenched gender roles
    - race & class issues

  #+BEGIN_NOTES
  notes:

  - cf. my listening to Dom Helder Camara: to white peace activists (Clergy against the war) -- that his people didn't know if they would die of hunger the next day. Their priorities were different.
  - identification with culture: doing church on Facebook?
  #+END_NOTES
**** Identity
  Use of social sciences & philosophy

  - to be black?
  - woman?
  - hispanic?

  Too much reliance on social science (non-Christian disciplines)
**** Readings
     - Martin Luther King Jr.
     - James H. Cone
     - Delores Williams
     - Rosemary Radford Ruether
     - Gustavo Gutiérrez
     - Leonardo Boff
     - Ivan Petrella
     - John Mbiti
     - C.S. Song
     - Evgeny Barabanov
     - John Milbank
*** Current Scene
  - from "white western males" to a global enterprise
  - sources for reflection changing
  - contemporary science is breath-takingly changing (exponentially)
  - responses to suffering & death
  - how many are the disciplines in the contemporary university
    - e.g. politics, economics, 
  #+BEGIN_NOTES
  Notes:
  cf. Bp from Aoteoroa re. the ocean

  Perhaps brainstorm the disciplines in the room, or in the university
  #+END_NOTES
**** Readings
     - Eberhard Jüngel
     - Sarah Coakley
     - Jürgen Moltmann
     - Wolfhart Pannenberg
     - David Bentley Hart
     - Mercy Amba Oduyoye
     - Lesslie Newbigin
     - John Polkinghorne
     - Elizabeth Johnson

*** Building Foundations
    :PROPERTIES:
    :reveal_background: https://thefunambulistdotnet.files.wordpress.com/2010/12/undergroundbydavidmacaulay001.jpg
    :reveal_background_size: 1100px
    :reveal_background_trans: slide
    :END:

**** Europe Rejecting the Enlightenment

  - Different course from that taken in America
  #+BEGIN_NOTES
  Note:
  How did America move past the Enlightenment? 

  Locke etc. -- Deism
  Great Awakening --  embracing "enthusiasm", conversion over "natural theology"
  Unitarians, Emerson, 
  Slavery?
  #+END_NOTES
**** Placement along various continua

  - Traditional <---> Progressive
  - Catholic <---> Protestant
  - Open to Science <---> Reactive or rejecting
  - Religious language as literal <---> Figurative

**** Definitions

  - Romanticism: p.233 /change is not always for the best, appreciate national traditions, value feeling over scientific analysis/
  - *Not* "natural theology": p. 205 /the basic truths about the existence of God and human morality known to good people in all societies/ 

**** New awareness of History

  - Rise of historical criticism since Renaissance
  - Skepticism of *knowing* with certainty (Spinoza, Hume, Kant, rise of scientific method)

  #+BEGIN_NOTES
  Note:
  From my youth I would reflect that no one in all of human history could think the thoughts I do, imagine what I imagine. I somehow looked toward Africa, reflecting that my vantage point was toward Africa not the other way round. That I had learned the things I learned in school -- from my ancestors -- that I thought in an English way, not French or Albanian or whatever.

  Moreover, the experience of History class in High School. Historical knowledge is never knowledge *with certainty*. 
  #+END_NOTES

*** 2 Romantics

**** Schleiermacher
  - religion as a *feeling* not *thought* "feeling of absolute dependence"
  - every event is a miracle, a "sign"
  - revelation is "every original and new communication of the Universe to man"
  - embrace the "genius" of one's own tradition
**** Coleridge
  - *tradition* is not conservatism but interpreting Christianity in terms of Romanticism
  - "factual accuracy of the Bible does not matter" but whether it *finds me*
*** Hegel

**** Structure of Reality & How we can know it
  - everything we see and experience is bound by historical setting
  - thus: *How can we know anything with certainty?*
  - triadic structure of reality p. 237
  - http://www.openculture.com/2015/08/the-half-hour-hegel.html
****  https://www.youtube.com/watch?v=q54VyCpXDH8&feature=youtu.be 
     :PROPERTIES:
     :reveal_background: http://www.cam.ac.uk/sites/www.cam.ac.uk/files/styles/content-580x288/public/news/research/news/120905-georg-wilhelm-friedrich-hegel-wikimedia-commons.jpg?itok=1upCC102
     :reveal_background_size: 1100px
     :reveal_background_trans: slide
     :END:
**** David Strauss
  - until Strauss, miracles either
    1. happened as described (literal) or
    2. some "rational" explanation or
    3. "fraud"
  - Strauss proposed that they consisted of "myth" (religious language that conveys sacred truth)
**** Ludwig Feuerbach
  - "theology is anthropology"
  - many college freshman can say, "God is just a projection of the human imagination." (a function of low-level thinking? or pervasiveness of Feuerbach's position)
**** Søren Kierkegaard
  - writing in pseudonyms to make the point that we always only know from a certain perspective
  - "We understand backwards, but we must live forwards."

  #+BEGIN_NOTES
  Note:
  Thus Abraham responding to God's command to sacrifice Isaac as seen from an ethical perspective was utterly depraved, justification for *murder*. "Only faith can offer a different interpretation... Faith goes beyond the universal categories of ethics to make the individual matter again. Only through *absurdity* ... belief in *paradox*. Anything else made faith to be *trivial*. "Only paradox can be grasped with passion." (p. 240)

  Use the image of "leap of faith" in a dancer. Throughout one is only becoming or reflecting where one has been. Only at one unspeakable moment is one in *being*. 

  The aesthetic perspective seeks to understand *love*. Thus is personal. Personal <-> Universal <-> Personal again
  #+END_NOTES
**** Development of Religious Person 
  - *aesthetic* stage
  - *ethical* stage
  - *religious* stage
    - The "Knight of Faith"


**** 
     :PROPERTIES:
     :reveal_background: http://blog.jaluo.com/wp-content/uploads/2012/05/19/unst_fa_2da_files/image006.jpg
     :reveal_background_size: 1100px
     :reveal_background_trans: slide
     :END:

*** Roman Catholic Reaction
  - interplay of Church/State authority (Papacy reluctant to abandon)
  - condemnation of "modernism" (/Syllabus of Errors/)
  - *immaculate conception* as dogma by means of *papal infallibility*
  - Leo XIII & Catholic social justice concerns
*** English Response
**** John H. Newman
  - recognizing that the Protestant claim to return to apostolic origins was fraught with historical perspectives (Hegel)
    - doctrine had developed from the very beginning of the church
  - "England would improve "were it vastly more superstitious, more bigoted, more gloomy, more fierce in its religion ..." p. 242
**** Frederick Maurice
  - high church / evangelical wing
  - rejecting both Maurice sought a 3rd alternative, identifying with the working class, argued for a gospel that could be embraced by *all*
  - Darwin / Huxley couldn't explain "the philosophical and theological implications of these new scientific conclusions."
*** Liberal Theology

  - Albrecht Ritschl
  - Friedrich Nietzsche

  - Adolf Harnack

  - Ernst Troeltsch

  #+BEGIN_NOTES
  Note:
  Ritschl tied Christianity closely to the culture of his time, moving away from metaphysical theories (cp. Maurice re. attacking emphasis on justification and conversion.

  Harnack was his student. History of Christian doctrine -- corruption of Christ's original teaching through Greek influences.

  History of religions theologicans like E. Troeltsch concluded Christianity emerged gradually out of a context of Jewish and middle eastern religions.

  Johannes Weiss and Albert Schweitzer argued that Jesus context had been *apocalypticism* -- expectation that a cataclysm was approaching and a *new age* would be ushered in.

  Nietzsche: argued that the influence of Christianity had been *negative*! We are not moving towards *truth* but truth is simply whatever a society agrees to call "true".

  Fascination with *history* ending in *despair*?
  #+END_NOTES
*** Chapter 18
*** Barth
    - rejection of cultural Christianity: Grace of Christ is supreme
    - everything reflects biases and cultural assumptions
    - attacked all human efforts to understand God
*** Anti-semitism interlude?
    - "God on Trial"
    - Roots and implications
    - God on trial trailer 1:37 min https://youtu.be/0W9uRPuo7hc
    - complete: https://youtu.be/tD7v9phroGM
    - https://youtu.be/5caAug5n8Zk
*** Bonhoeffer
    - Cheap Grace
    - Religionless Christianity
    - trailer to pbs documentary: 1:21 https://youtu.be/Cd_gmkypPGk
    - http://www.pbs.md/bonhoeffer/
*** Bultmaann & Existentialism
    - Search for historical truth is fruitless
    - There is no "human nature" to find
    - p. 257
*** American response
 - Fundamentalism: Inerrancy
 - Niebuhr: Social realist
*** Roman Catholic response
 - Vatican 2: Pilgrim people
 - Lonergan: It's all about the method
 - Rahner: The mystery is beyond words
*** From 19th - 20th c.
**** Existentialism and Fundamentalism
***** Existentialism's impact
  Bultmann’s “left-wing” followers, like the American Schubert Ogden, have concluded that Christianity concerns only the possibility of a new way of 
  existing.
***** American responsen
  - Reinhold Niebuhr: Christian realism "Man's capacity for justice makes democracy possible; but man's inclination to injustice makes democracy necessary."
  #+BEGIN_VERSE
  God, grant me the serenity to accept the things I cannot change,
  The courage to change the things I can,
  And the wisdom to know the difference.
  #+END_VERSE
  cf. https://en.wikipedia.md/wiki/Serenity_Prayer
***** Christ and culture
  Richard Niebuhr: Christian ethicist: /Christ and Culture/
  - Christ against Culture :: For the exclusive Christian, history is the story of a rising church or - Christian culture and a dying pagan civilization.
  - Christ of Culture :: For the cultural Christian, history is the story of the Spirit’s encounter with nature.
  - Christ above Culture :: For the synthesist, history is a period of preparation under law, reason, gospel, and church for an ultimate communion of the soul with God.
  - Christ and Culture in Paradox :: For the dualist, history is the time of struggle between faith and unbelief, a period between the giving of the promise of life and its fulfillment.
  - Christ Transforming Culture :: For the conversionist, history is the story of God’s mighty deeds and humanity’s response to them.

***** Evangelical
    - United States. Evangelical theology, with a renewed emphasis on the authority and often the literal inspiration of the Bible, also continues to be an important force in American theology, but it has generally reaffirmed the views Charles Hodge and Benjamin B. Warfield developed in the nineteenth century rather than producing new ideas.
*** Catholic development
**** Catholic focus
***** Roman Catholic response

  - Rahner said that there is a fundamental mystery, a matter of religious faith, at the heart of all human understanding.
  - Vatican 2: Pilgrim people: define “the church” not as the hierarchy of pope and bishops but as the whole “pielgrim people of God.”
  #+BEGIN_QUOTE
  The joys and the hopes, the griefs and the anxieties of the men of this age, especially those who are poor or in any way afflicted, these are the joys and hopes, the griefs and anxieties of the followers of Christ. 
  #+END_QUOTE
  http://www.cctwincities.md/document.doc?id=62

*** Theology engages Philosophy (again)
**** Recent philosophies
***** THEOLOGY AND RECENT PHILOSOPHIES
  - logical positivists demanded, “How can we design a scientific experiment to test whether or not God exists?
  - later writings of the philosopher Ludwig Wittgenstein, they have recognized how many different ways language can be used meaningfully.
  - Language has also been a preoccupation for French philosophers like Jacques Derrida and François Lyotard, and theologians have recently used their ideas to develop a “postmodern” theology
***** deconstruction
  - Two world wars, the Holocaust, and increasing globalization make such “modern” views impossible to hold in a postmodern world. Derrida advocated the need for a postmodern “deconstruction” of knowledge
***** American response


      - United States. Evangelical theology, with a renewed emphasis on the authority and often the literal inspiration of the Bible, also continues to be an important force in American theology, but it has generally reaffirmed the views Charles Hodge and Benjamin B. Warfield developed in the nineteenth century rather than producing new ideas.
***** Process theology
  - “process theology,” has developed here under the influence of Alfred North Whitehead.
  - Process theology describes a God who is perfect in that he is perfectly related to everything, who lures actions by love rather than forcing them by power. “He is the poet of the world, with tender patience leading it by his vision of truth, beauty, and goodness.
*** Theology engages the world
**** Theology and the world
***** THEOLOGY AND THE SECULAR
  - theology engaging: sciences, biology, anthropology, arts,
  - "Big enough God"
  - Harvey Cox at Harvard saw a need for Christianity to engagement with secular disciplines as a real opportunity
  - related to Bonhoeffer's "religionless Christianity"?

*** Theology and Freedom
**** Liberation
***** LIBERATION THEOLOGY
  - That very emphasis—liberating the captives—names the most important field of theology in the last half-century.
  - Liberation theology first drew wide attention in the United States in connection with “black liberation.”
  - James Cone’s Black Theology and Black Power, published in 1969, made the blacks’ liberation from their white oppressors its central theological theme and addressed whites with warnings rather than pleas for help.
***** Feminist criticism / liberation
  - Looking beyond that, Rosemary Radford Ruether (a prolific theologian committed both to feminism and to Christianity) has written, All theologies of liberation, whether done in a black or a feminist or a Third World perspective, will be abortive of the liberation they seek, unless they finally go beyond the … model of the oppressor and the oppressed.

***** THEOLOGY AND THE RELIGIONS

  - “Yes, I am a syncretist. But so are you. I know that I am a syncretist, but you don’t know you are a syncretist because you have hegemonic power.
  - Other theologians of pluralism have been less insistent that multiple religions are different ways of saying the same thing. A Roman Catholic priest named Raimundo Pannikar, for example, born in Spain to a Hindu father and a Spanish mother, advocates a more strictly comparative approach.

***** 
*** Pivot to a new century 
  - Reject the status of history
  - Christian collusion with profound sin
    1. serfdom of women
    2. slavery
    3. anti-semitism
**** Barth
     - rejection of cultural Christianity: Grace of Christ is supreme
     - everything reflects biases and cultural assumptions
     - attacked all human efforts to understand God
**** Anti-semitism interlude?
     - "God on Trial"
     - Roots and implications
     - God on trial trailer 1:37 min https://youtu.be/0W9uRPuo7hc
     - complete: https://youtu.be/tD7v9phroGM
     - https://youtu.be/5caAug5n8Zk
     - cp. American experience with slavery?
*** Rejection of cultural Christianity

**** Bonhoeffer
     - Cheap Grace
     - Religionless Christianity
     - trailer to pbs documentary: 1:21 https://youtu.be/Cd_gmkypPGk
     - http://www.pbs.md/bonhoeffer/
**** Bultmann & Existentialism
     - Search for historical truth is fruitless
     - There is no "human nature" to find
     - p. 257
*** Existentialism and Fundamentalism
**** Existentialism's impact
  Bultmann’s “left-wing” followers, like the American Schubert Ogden, have concluded that Christianity concerns only the possibility of a new way of 
  existing.
**** American response
  - Reinhold Niebuhr: Christian realism "Man's capacity for justice makes democracy possible; but man's inclination to injustice makes democracy necessary."
  #+BEGIN_VERSE
  God, grant me the serenity to accept the things I cannot change,
  The courage to change the things I can,
  And the wisdom to know the difference.
  #+END_VERSE
  cf. https://en.wikipedia.md/wiki/Serenity_Prayer
**** Christ and culture
  Richard Niebuhr: Christian ethicist: /Christ and Culture/

  #+ATTR_REVEAL: :frag (appear)
  - Christ against Culture :: For the exclusive Christian, history is the story of a rising church or - Christian culture and a dying pagan civilization.
  - Christ of Culture :: For the cultural Christian, history is the story of the Spirit’s encounter with nature.
  - Christ above Culture :: For the synthesist, history is a period of preparation under law, reason, gospel, and church for an ultimate communion of the soul with God.

  #+REVEAL: split
  - Christ and Culture in Paradox :: For the dualist, history is the time of struggle between faith and unbelief, a period between the giving of the promise of life and its fulfillment.

  #+ATTR_REVEAL: :frag (appear)
  - Christ Transforming Culture :: For the conversionist, history is the story of God’s mighty deeds and humanity’s response to them.

*** Evangelical & Catholic?
**** Evangelical

    - United States. Evangelical theology, with a renewed emphasis on the authority and often the literal inspiration of the Bible, also continues to be an important force in American theology, but it has generally reaffirmed the views Charles Hodge and Benjamin B. Warfield developed in the nineteenth century rather than producing new ideas.

**** Roman Catholic response

  - Rahner said that there is a fundamental mystery, a matter of religious faith, at the heart of all human understanding.
  #+ATTR_REVEAL: :frag (appear)
  - Vatican 2: Pilgrim people: define “the church” not as the hierarchy of pope and bishops but as the whole “pielgrim people of God.”
  #+BEGIN_QUOTE
  The joys and the hopes, the griefs and the anxieties of the men of this age, especially those who are poor or in any way afflicted, these are the joys and hopes, the griefs and anxieties of the followers of Christ. 
  #+END_QUOTE
  http://www.cctwincities.md/document.doc?id=62

*** Engagement of Religion

**** Theology engages Philosophy --again
***** Recent philosophies
***** THEOLOGY AND RECENT PHILOSOPHIES
  - logical positivists demanded, “How can we design a scientific experiment to test whether or not God exists?
  #+ATTR_REVEAL: :frag (appear)
  - later writings of the philosopher Ludwig Wittgenstein, they have recognized how many different ways language can be used meaningfully.
  - Language has also been a preoccupation for French philosophers like Jacques Derrida and François Lyotard, and theologians have recently used their ideas to develop a “postmodern” theology
***** deconstruction
  - Two world wars, the Holocaust, and increasing globalization make such “modern” views impossible to hold in a postmodern world. Derrida advocated the need for a postmodern “deconstruction” of knowledge
***** American response


      - United States. Evangelical theology, with a renewed emphasis on the authority and often the literal inspiration of the Bible, also continues to be an important force in American theology, but it has generally reaffirmed the views Charles Hodge and Benjamin B. Warfield developed in the nineteenth century rather than producing new ideas.
***** Process theology
  - “process theology,” has developed here under the influence of Alfred North Whitehead.
  - Process theology describes a God who is perfect in that he is perfectly related to everything, who lures actions by love rather than forcing them by power. “He is the poet of the world, with tender patience leading it by his vision of truth, beauty, and goodness.
**** Theology engages the world
***** Theology and the world
***** THEOLOGY AND THE SECULAR
  - theology engaging: sciences, biology, anthropology, arts,
  #+ATTR_REVEAL: :frag (appear)
  - "Big enough God"
  - Harvey Cox at Harvard saw a need for Christianity to engagement with secular disciplines as a real opportunity
  - related to Bonhoeffer's "religionless Christianity"?

**** Theology and Freedom
***** Liberation
***** LIBERATION THEOLOGY
  - That very emphasis—liberating the captives—names the most important field of theology in the last half-century.
  #+ATTR_REVEAL: :frag (appear)
  - Liberation theology first drew wide attention in the United States in connection with “black liberation.”
  - James Cone’s Black Theology and Black Power, published in 1969, made the blacks’ liberation from their white oppressors its central theological theme and addressed whites with warnings rather than pleas for help.
***** Feminist criticism / liberation
  - Looking beyond that, Rosemary Radford Ruether (a prolific theologian committed both to feminism and to Christianity) has written, All theologies of liberation, whether done in a black or a feminist or a Third World perspective, will be abortive of the liberation they seek, unless they finally go beyond the … model of the oppressor and the oppressed.

**** Theology and the Religions

  - “Yes, I am a syncretist. But so are you. I know that I am a syncretist, but you don’t know you are a syncretist because you have hegemonic power.
  #+ATTR_REVEAL: :frag (appear)
  - Other theologians of pluralism have been less insistent that multiple religions are different ways of saying the same thing. A Roman Catholic priest named Raimundo Pannikar, for example, born in Spain to a Hindu father and a Spanish mother, advocates a more strictly comparative approach.
 


