#+Title: Theology and New Philosophies
#+Date: Spring 2021 
#+Email: hathawayd@winthrop.edu
 #+OPTIONS: reveal_width:1000 reveal_height:800 
 #+REVEAL_MARGIN: 0.1
 #+REVEAL_MIN_SCALE: 0.5
 #+REVEAL_MAX_SCALE: 2
 #+REVEAL_HLEVEL: 1h
 #+OPTIONS: toc:1 num:nil
 #+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
 #+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
 #+REVEAL_PLUGINS: (markdown notes menu)
 #+REVEAL_THEME: beige
#+REVEAL_ROOT: ../../reveal.js/

* Theology And Recent Philosophies
  :PROPERTIES:
  :CUSTOM_ID: theology-and-recent-philosophies
  :END:

** Wittgenstein
   :PROPERTIES:
   :CUSTOM_ID: wittgenstein
   :END:

 - logical positivists demanded, “How can we design a scientific experiment to test whether or not God exists?
 - later writings of the philosopher Ludwig Wittgenstein, they have recognized how many different ways language can be used meaningfully.
 - Language has also been a preoccupation for French philosophers like Jacques Derrida and François Lyotard, and theologians have recently used their ideas to develop a “postmodern” theology

** deconstruction
   :PROPERTIES:
   :CUSTOM_ID: deconstruction
   :END:

 - Two world wars, the Holocaust, and increasing globalization make such “modern” views impossible to hold in a postmodern world. Derrida advocated the need for a postmodern “deconstruction” of knowledge

* American response
  :PROPERTIES:
  :CUSTOM_ID: american-response
  :END:

- United States. Evangelical theology, with a renewed emphasis on the authority and often the literal inspiration of the Bible, also continues to be an important force in American theology, but it has generally reaffirmed the views Charles Hodge and Benjamin B. Warfield developed in the nineteenth century rather than producing new ideas.

** Process theology
   :PROPERTIES:
   :CUSTOM_ID: process-theology
   :END:

 - “process theology,” has developed here under the influence of Alfred North Whitehead.
 - Process theology describes a God who is perfect in that he is perfectly related to everything, who lures actions by love rather than forcing them by power. “He is the poet of the world, with tender patience leading it by his vision of truth, beauty, and goodness.

* Hope & Eschatology
  :PROPERTIES:
  :CUSTOM_ID: hope--eschatology
  :END:

- reaction to Bultmann: viz. place of *Old Testament* for Christian theology
- Schweitzer & others have shown the importance of *eschatology* for understanding New Testament
- Pannenberg: Christian theology must understand itself in the world we live in
- Dorothy Sölle: role of *suffering* in Theology
#+BEGIN_NOTES

Notes:

OT use: p. 263/268. One contra Bultmann, one MLK re. liberation

Issue: use of OT in Christian theology

- pre-figuring NT
- superceded
- needing figurative interpretation

Wolfhart Pannenberg (2 October 1928 -- 4 September 2014) was a German theologian. He has made a number of significant contributions to modern theology, including his concept of *history as a form of revelation centered on the Resurrection of Christ*, which has been widely debated in both Protestant and Catholic theology, as well as by non-Christian thinkers.

She wrote a large number of books, including /Theology for Skeptics: Reflections on God/, /The Silent Cry: Mysticism and Resistance/ (2001) and her autobiography /Against the Wind: Memoir of a Radical Christian/ (1999). In /Beyond Mere Obedience: Reflections on a Christian Ethic for the Future/ she coined the term "Christofascist" to describe fundamentalists. Perhaps her best-known work in English was /Suffering/, which offers a critique of "Christian masochism" and "theological sadism". Sölle's *critique is against the assumption that God is all-powerful and the cause of suffering*; humans thus suffer for some greater purpose. Instead, God suffers and is powerless alongside us. Humans are to struggle together against oppression, sexism, anti-Semitism, and other forms of authoritarianism.

#+END_NOTES
* Liberation Theology
  :PROPERTIES:
  :CUSTOM_ID: liberation-theology
  :END:

- Africa, Latin America: experience of being *oppressed*
- 1960's "black liberation" in US: parallels between Israel's slavery in Egypt & slavery in modern world
- MLK Jr. "Letter from Birmingham Jail" cp. "Barmen Declaration"
- James Cone: "being black is not a matter of skin color"
- Women's liberation:
- Recognizing that both oppressed and oppressor need "liberating"
#+BEGIN_NOTES

Notes:

cp. the new "Reclaiming Jesus"

Nicaragua: teaching literacy with no books. Only at hand is bible.
Finding the meaning there.

#+END_NOTES
** Theology and Freedom
   :PROPERTIES:
   :CUSTOM_ID: theology-and-freedom
   :END:

 1. Liberation
 2. LIBERATION THEOLOGY

 - That very emphasis---liberating the captives---names the most important field of theology in the last half-century.
 - Liberation theology first drew wide attention in the United States in connection with “black liberation.”
 - James Cone's Black Theology and Black Power, published in 1969, made the blacks' liberation from their white oppressors its central theological theme and addressed whites with warnings rather than pleas for help.

*** Feminist criticism / liberation

 - Looking beyond that, Rosemary Radford Ruether (a prolific theologian committed both to feminism and to Christianity) has written,

#+begin_quote
 All theologies of liberation, whether done in a black or a feminist or a Third World perspective, will be abortive of the liberation they seek, unless they finally go beyond the ... model of the oppressor and the oppressed.
#+end_quote

*** Theology and the Religions

    - “Yes, I am a syncretist. But so are you. I know that I am a syncretist, but you don't know you are a syncretist because you have hegemonic power.
    - Other theologians of pluralism have been less insistent that multiple religions are different ways of saying the same thing. A Roman Catholic priest named Raimundo Pannikar, for example, born in Spain to a Hindu father and a Spanish mother, advocates a more strictly comparative approach.

*** THEOLOGY AND THE SECULAR
    :PROPERTIES:
    :CUSTOM_ID: theology-and-the-secular
    :END:

  - theology engaging: sciences, biology, anthropology, arts,
  - "Big enough God"
  - Harvey Cox at Harvard saw a need for Christianity to engagement with secular disciplines as a real opportunity
  - related to Bonhoeffer's "religionless Christianity"?

*** Theology & the Secular
    :PROPERTIES:
    :CUSTOM_ID: theology--the-secular
    :END:

  - theology for church vs. for the secular world
  - John Polkinghorne
  - Ian Barbour
  - Theology: image of "wheel" vs. "matrix"
  - Harvey Cox: value in engaging the secular world (cf. Bonhoeffer)
 #+BEGIN_NOTES

  Notes:

  Relating God's action in the natural world to physics, biology, etc.

  cf. esp. awareness of natural environment. Reading of Genesis 1.

  Cox: avoid theology being a ghetto cut off from the world

 #+END_NOTES
** World of many religions
   :PROPERTIES:
   :CUSTOM_ID: world-of-many-religions
   :END:

 - *"syncretism":* "the amalgamation or attempted amalgamation of different religions, cultures, or schools of thought" --; Christianity itself syncretistic?
 - **pluralism*:* truth in other religions? (John Hick)
 - Raimundo Pannikar --; center of Christian theology moving south?
#+BEGIN_NOTES

 Notes:

 Raimon Panikkar Alemany (November 2, 1918 -- August 26, 2010; also known as Raimundo Panikkar and Raymond Panikkar) was a Spanish Roman Catholic priest and a proponent of inter-religious dialogue. As a scholar, he specialized in *comparative religion*.


#+END_NOTES
