#+Title:Responses
#+Date: Spring 2021 
#+Email: hathawayd@winthrop.edu
 #+OPTIONS: reveal_width:1000 reveal_height:800 
 #+REVEAL_MARGIN: 0.1
 #+REVEAL_MIN_SCALE: 0.5
 #+REVEAL_MAX_SCALE: 2
 #+REVEAL_HLEVEL: 1h
 #+OPTIONS: toc:1 num:nil
 #+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
 #+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
 #+REVEAL_PLUGINS: (markdown notes menu)
 #+REVEAL_THEME: beige
#+REVEAL_ROOT: ../../reveal.js/
* Roman Catholic Reaction
  :PROPERTIES:
  :CUSTOM_ID: roman-catholic-reaction
  :END:

- interplay of Church/State authority (Papacy reluctant to abandon)
- condemnation of "modernism" (/Syllabus of Errors/)
- *immaculate conception* as dogma by means of *papal infallibility*
- Leo XIII & Catholic social justice concerns


* English Response
  :PROPERTIES:
  :CUSTOM_ID: english-response
  :END:

** John H. Newman
   :PROPERTIES:
   :CUSTOM_ID: john-h-newman
   :END:

- recognizing that the Protestant claim to return to apostolic origins was fraught with historical perspectives (Hegel)
  - doctrine had developed from the very beginning of the church
- "England would improve "were it vastly more superstitious, more bigoted, more gloomy, more fierce in its religion ..." p. 242

** Frederick Maurice
   :PROPERTIES:
   :CUSTOM_ID: frederick-maurice
   :END:

- high church / evangelical wing
- rejecting both Maurice sought a 3rd alternative, identifying with the working class, argued for a gospel that could be embraced by *all*
- Darwin / Huxley couldn't explain "the philosophical and theological implications of these new scientific conclusions."

* Liberal Theology
  :PROPERTIES:
  :CUSTOM_ID: liberal-theology
  :END:

- Albrecht Ritschl
- Friedrich Nietzsche
- Adolf Harnack
- Ernst Troeltsch

#+BEGIN_NOTES

::: {.NOTES} Note: Ritschl tied Christianity closely to the culture of
his time, moving away from metaphysical theories (cp. Maurice re.
attacking emphasis on justification and conversion.

Harnack was his student. History of Christian doctrine -- corruption of
Christ's original teaching through Greek influences.

History of religions theologicans like E. Troeltsch concluded
Christianity emerged gradually out of a context of Jewish and middle
eastern religions.

Johannes Weiss and Albert Schweitzer argued that Jesus context had been
*apocalypticism* -- expectation that a cataclysm was approaching and a
*new age* would be ushered in.

Nietzsche: argued that the influence of Christianity had been
*negative*! We are not moving towards *truth* but truth is simply
whatever a society agrees to call "true".

Fascination with *history* ending in *despair*? :::

#+END_NOTES

