#+Title: Philosophical Issues: Erasmus
#+Date: Spring 2021 
#+Email: hathawayd@winthrop.edu
 #+OPTIONS: reveal_width:1000 reveal_height:800 
 #+REVEAL_MARGIN: 0.1
 #+REVEAL_MIN_SCALE: 0.5
 #+REVEAL_MAX_SCALE: 2
 #+REVEAL_HLEVEL: 1h
 #+OPTIONS: toc:1 num:nil
 #+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
 #+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
 #+REVEAL_PLUGINS: (markdown notes menu)
 #+REVEAL_THEME: beige
#+REVEAL_ROOT: ../../reveal.js/


* 5 Themes
** Humanity / Divinity of Christ
- John 1  (NRSV) 1 In the beginning was the Word, and the Word was with God, and the Word was God. 2 He was in the beginning with God. 3 All things came into being through him, and without him not one thing came into being. What has come into being 4 in him was life, ...
- Matthew 13:55 Is not this the carpenter’s son? Is not his mother called Mary? And are not his brothers James and Joseph and Simon and Judas?
** Reformers and ... 
- what is the role of free will?
- does justification happen instantaneously or gradually?

** Spirit and Structure
- Romans 8:2 For the law of the Spirit of life in Christ Jesus has set you free from the law of sin and of death.
- Clearly structure of some kind was important to the New Testament church, Timothy relates the importortance of bishops, Luke/Acts emphasizes the importance of 12 Apostles.
** Reformers and ...
- is Spirit primary? or Scripture?
- If community is led by Spirit does it need to follow ordinary rules of society?
** Reason and Revelation
   - Romans 16:25  Now to God who is able to strengthen you according to my gospel and the proclamation of Jesus Christ, according to the revelation of the mystery that was kept secret for long ages
   - Jesus himself was masterful in reasoning with religious leaders who sought to argue against him.
** Reformers and ...
- /sola scritura/ vs. scripture and tradition
- is Scripture the only authority or the "highest" authority?
** Works and Grace
- 2 Timothy 1:9 who saved us and called us with a holy calling, not according to our works but according to his own purpose and grace. This grace was given to us in Christ Jesus before the ages began,
- James epistle seems to praise good works
** Reformers and ...
- justification by grace alone, works are of no use
- gradual sanctification manifest through works

** Church and State
- Romans 13 Let every person be subject to the governing authorities; for there is no authority except from God, and those authorities that exist have been instituted by God.
- Jesus was executed because he didn't obey authorities.
** Reformers and ...
- Luther essentially conservative with regard to civil authorities
- others understood the Reform agenda to be revolutionary
- pacifism of Mennonites


* Luther
** Luther, father of Reformation
Who was this person who stands so huge at the beginning of our period?

https://prezi.com/yfmiihckhjj0/martin-luther-reformation/

** Reading from Michener's /The Source/
Illustrating the wider context of this period.
** Excerpts from Luther's "Freedom of a Christian"

- https://sites.google.com/site/relg317f15/

- http://richard-hooker.com/sites/worldcultures/REFORM/FREEDOM.HTM
** 
- A Christian man is the most free lord of all, and subject to none, a Christian man is the most dutiful servant of all, and subject to every one.
- "faith has appeared to many to be an easy thing"
- "Man is composed of a twofold nature, a spiritual and a bodily."
- (recognizing that scriptural passages can be found to seem to support opposites perspectives)
- outward signs (vestments etc.) "profit nothing"
- "One thing, and one alone, is necessary for life, justification, and Christian liberty; and that is the most holy word of God, the Gospel of Christ."
** 
- this faith can reign only in the inward man
- every Christian by faith if "lord of all things" but in "corporeal power" he is subject to the earthly powers
- the "outward man" ... must not take his ease; ... exercise, fastings, etc.
- enormous folly ... when a man seeks, without faith, to be justified and saved by works...
- ceremonies are but "preparations for building or working" to be "laid aside."
- "Thus, too, we do not contemn works and ceremonies -- nay, we set the highest value on them; but ..."

* Excerpts from presentations
** 
- One of the major things I learned while reading this chapter is that Luther was resposible for many of the critical changes in the church. Specifically, his emphasis on faith. Luther stressed the fact that faith because of the many instances of corruption in the Catholic church.

- The debate over the Spirit or Holy Spirit was really interesting to me. Andreas Bodenstein von Carlstadt, a colleague of Luther, "thought that the voice of the Holy Spirit could speak directly to any Christian" (p. 158), in which Luther thought this was not a good idea, since Luther believed that Scripture was more important.


** 
- Thomas Muntzer also believed that the Spirit was more important than Scriptures, claiming that "the Spirit could speak even to those who lacked the education needed for biblical scholarship" (p. 158). 

- I found it surprising how discouraging Luther was towards political rebellion. I mean, I disagree with his ideals of people living for simplicity of the common good. If there is not change present, then corruption continues. I would think Luther would want reformation of the corruption of the church intertwined with the political system. 
** 
- It wasn't as surprising as it was interesting to discover the origin of Mennonites (or the Amish as I thought). It is weird to think that something as simple as adult baptism really separated Christians. I could really see the importance of scripture as the highest authority because people have their own views on how to interpret scripture. Luther seemed as if he wanted to take it literally, but he holds many contradictions to this. "
** 
- Luther addresses in the excerpt that everyone has a priesthood but not everyone can perform ceromonies Are the ceromonies he is speaking of sacraments, like baptism and communion? If so, what does he mean by that?

- Being saved by faith alone surprised me because I was taught that faith means: "a strong belief in God or in the doctrines of a religion, based on spiritual apprehension rather than proof." And my youth pastor used to say that he has no faith the bible is real, he knows it. 
** 
- Luther did not expect his beliefs about the authority of scripture to be viewed as rebellious and heretical! It was also viewed as quite shocking that he got married.

- Humanists were mentioned in this chapter, but I struggled to fully comprehend what they believed and how it differed from the Orthodox Church (as well as Luther's teachings).
** 
- Luther changed the entire christian theology by standing his ground and calling out the wrong doings of the church. I also found it important when Luther stated that even without the bible one can come to know Christianity on a spiritual level just as those who wrote the bible did before them. 

- If a person does not know God and is of a certain age we consider them to be saved still if they die young. This theory of Luthers would imply that anyone can know God without proper exposure and therefore could potentially distroy the original belief. 
** 
- Luther's revolution was accidental, -- Grebel and friends rebaptism of one another after deciding that infant baptisms are invalid."

- I was surprised that such a thing as Christian mysticism exists. Eckhart's theory risked blurring the distinction between God and His creatures, so that humans could be considered divine through their connection with God. This reminded me of the Hindu philosophy that all individual souls are one united, divine being.
* Resources
** Erasmus
Several quotes to illustrate "Humanism"

- cf. http://oll.libertyfund.org/people/desiderius-erasmus
