#+Author: Dale Hathaway
#+Title: 20th c. part 1
#+Date: 2018-03-27 Tue
#+Email: hathawayd@winthrop.edu
 #+OPTIONS: reveal_width:1000 reveal_height:800 
 #+REVEAL_MARGIN: 0.1
 #+REVEAL_MIN_SCALE: 0.5
 #+REVEAL_MAX_SCALE: 2
 #+REVEAL_HLEVEL: 1
 #+OPTIONS: toc:1 num:nil
 #+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
 #+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
 #+REVEAL_PLUGINS: (markdown notes)
 #+REVEAL_THEME: beige
#+REVEAL_ROOT: ../../reveal.js/


* Pivot to a new century 
- Reject the status of history
- Christian collusion with profound sin
  1. serfdom of women
  2. slavery
  3. anti-semitism
** Barth
   - rejection of cultural Christianity: Grace of Christ is supreme
   - everything reflects biases and cultural assumptions
   - attacked all human efforts to understand God
** Anti-semitism interlude?
   - "God on Trial"
   - Roots and implications
   - God on trial trailer 1:37 min https://youtu.be/0W9uRPuo7hc
   - complete: https://youtu.be/tD7v9phroGM
   - https://youtu.be/5caAug5n8Zk
   - cp. American experience with slavery?
* Rejection of cultural Christianity

** Bonhoeffer
   - Cheap Grace
   - Religionless Christianity
   - trailer to pbs documentary: 1:21 https://youtu.be/Cd_gmkypPGk
   - http://www.pbs.org/bonhoeffer/
** Bultmann & Existentialism
   - Search for historical truth is fruitless
   - There is no "human nature" to find
   - p. 257
* Existentialism and Fundamentalism
** Existentialism's impact
Bultmann’s “left-wing” followers, like the American Schubert Ogden, have concluded that Christianity concerns only the possibility of a new way of 
existing.
** American response
- Reinhold Niebuhr: Christian realism "Man's capacity for justice makes democracy possible; but man's inclination to injustice makes democracy necessary."
#+BEGIN_VERSE
God, grant me the serenity to accept the things I cannot change,
The courage to change the things I can,
And the wisdom to know the difference.
#+END_VERSE
cf. https://en.wikipedia.org/wiki/Serenity_Prayer
** Christ and culture
Richard Niebuhr: Christian ethicist: /Christ and Culture/

#+ATTR_REVEAL: :frag (appear)
- Christ against Culture :: For the exclusive Christian, history is the story of a rising church or - Christian culture and a dying pagan civilization.
- Christ of Culture :: For the cultural Christian, history is the story of the Spirit’s encounter with nature.
- Christ above Culture :: For the synthesist, history is a period of preparation under law, reason, gospel, and church for an ultimate communion of the soul with God.

#+REVEAL: split
- Christ and Culture in Paradox :: For the dualist, history is the time of struggle between faith and unbelief, a period between the giving of the promise of life and its fulfillment.

#+ATTR_REVEAL: :frag (appear)
- Christ Transforming Culture :: For the conversionist, history is the story of God’s mighty deeds and humanity’s response to them.

* Evangelical & Catholic?
** Evangelical

  - United States. Evangelical theology, with a renewed emphasis on the authority and often the literal inspiration of the Bible, also continues to be an important force in American theology, but it has generally reaffirmed the views Charles Hodge and Benjamin B. Warfield developed in the nineteenth century rather than producing new ideas.

** Roman Catholic response

- Rahner said that there is a fundamental mystery, a matter of religious faith, at the heart of all human understanding.
#+ATTR_REVEAL: :frag (appear)
- Vatican 2: Pilgrim people: define “the church” not as the hierarchy of pope and bishops but as the whole “pielgrim people of God.”
#+BEGIN_QUOTE
The joys and the hopes, the griefs and the anxieties of the men of this age, especially those who are poor or in any way afflicted, these are the joys and hopes, the griefs and anxieties of the followers of Christ. 
#+END_QUOTE
http://www.cctwincities.org/document.doc?id=62

* Engagement of Religion

** Theology engages Philosophy --again
*** Recent philosophies
*** THEOLOGY AND RECENT PHILOSOPHIES
- logical positivists demanded, “How can we design a scientific experiment to test whether or not God exists?
#+ATTR_REVEAL: :frag (appear)
- later writings of the philosopher Ludwig Wittgenstein, they have recognized how many different ways language can be used meaningfully.
- Language has also been a preoccupation for French philosophers like Jacques Derrida and François Lyotard, and theologians have recently used their ideas to develop a “postmodern” theology
*** deconstruction
- Two world wars, the Holocaust, and increasing globalization make such “modern” views impossible to hold in a postmodern world. Derrida advocated the need for a postmodern “deconstruction” of knowledge
*** American response


    - United States. Evangelical theology, with a renewed emphasis on the authority and often the literal inspiration of the Bible, also continues to be an important force in American theology, but it has generally reaffirmed the views Charles Hodge and Benjamin B. Warfield developed in the nineteenth century rather than producing new ideas.
*** Process theology
- “process theology,” has developed here under the influence of Alfred North Whitehead.
- Process theology describes a God who is perfect in that he is perfectly related to everything, who lures actions by love rather than forcing them by power. “He is the poet of the world, with tender patience leading it by his vision of truth, beauty, and goodness.
** Theology engages the world
*** Theology and the world
*** THEOLOGY AND THE SECULAR
- theology engaging: sciences, biology, anthropology, arts,
#+ATTR_REVEAL: :frag (appear)
- "Big enough God"
- Harvey Cox at Harvard saw a need for Christianity to engagement with secular disciplines as a real opportunity
- related to Bonhoeffer's "religionless Christianity"?

** Theology and Freedom
*** Liberation
*** LIBERATION THEOLOGY
- That very emphasis—liberating the captives—names the most important field of theology in the last half-century.
#+ATTR_REVEAL: :frag (appear)
- Liberation theology first drew wide attention in the United States in connection with “black liberation.”
- James Cone’s Black Theology and Black Power, published in 1969, made the blacks’ liberation from their white oppressors its central theological theme and addressed whites with warnings rather than pleas for help.
*** Feminist criticism / liberation
- Looking beyond that, Rosemary Radford Ruether (a prolific theologian committed both to feminism and to Christianity) has written, All theologies of liberation, whether done in a black or a feminist or a Third World perspective, will be abortive of the liberation they seek, unless they finally go beyond the … model of the oppressor and the oppressed.

** Theology and the Religions

- “Yes, I am a syncretist. But so are you. I know that I am a syncretist, but you don’t know you are a syncretist because you have hegemonic power.
#+ATTR_REVEAL: :frag (appear)
- Other theologians of pluralism have been less insistent that multiple religions are different ways of saying the same thing. A Roman Catholic priest named Raimundo Pannikar, for example, born in Spain to a Hindu father and a Spanish mother, advocates a more strictly comparative approach.
 
