#+Author: Dale Hathaway
#+Title: Calvinism 
#+Date: 2018-02-13 Tue 
#+Email: hathawayd@winthrop.edu
 #+OPTIONS: reveal_width:1000 reveal_height:800 
 #+REVEAL_MARGIN: 0.1
 #+REVEAL_MIN_SCALE: 0.5
 #+REVEAL_MAX_SCALE: 2
 #+REVEAL_HLEVEL: 1
 #+OPTIONS: toc:1 num:nil
 #+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
 #+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
 #+REVEAL_PLUGINS: (markdown notes)
 #+REVEAL_THEME: beige
#+REVEAL_ROOT: ../../reveal.js/


* Overview
**  questions/focus
    - "reform" as in "reformed life"
    - organizing society, community
    - what is community?
    - 39 articles
    - "Puritans" 
* Calvinism
** Calvinism
*** Discipline of the community
- (191) Community maintain discipline by regulating who come to communion
- (191) organization of community (Geneva) ministers, teachers, elders, deacons ... "presbytery"
** Calvinism
*** Church and State
- (192) Calvin allowing for working against civil authority when they betray the faith
- John Knox in Scotland "seized" on those principles in his energy opposing the English
- (193) France, Scotland, then England Calvinists thought about how to oppose an unjust society
- Scotland corrupt church 193, thus as in France political conditions drove Calvin's followers
** Calvinism
*** "Orthodoxy" 
- in Amsterdam with Arminius -- in move against him, the church solidified its "orthodoxy" and *thus froze positions that earlier had been nuanced*
- p. 194 table of *5 basic principles of Calvinist orthodoxy*
- reading Calvin elicits not an emotional response but a cumulative one from the systematic presentation p 188
** Calvinism
*** now reform of the person not of the church
- response to (free) grace is a *reformed* life (thus the name)
*** Predestination 
- clearly we are not saved by good works, therefore it has to be God's decision
- "Reflections on how we come to be saved led to the doctrine of predestination (189 ff.)
- single? double?
- https://en.wikipedia.org/wiki/The_Private_Memoirs_and_Confessions_of_a_Justified_Sinner

** epithoughts
- "Calvinist in polity" -- huge influence on English world
- Knox and Calvin and the "reformed" tradition 

* Beyond Geneva
** Bucer 
- centrale figure of Reformation? 190
- sought to avoid being explicit about sacraments (Luth/Zwingli)
- stands out in the figures for his tolerance
- theology of sacraments: cf. *Martin Bucer* (large influence)
  - sought position between Luther and Zwingli
** Knox
- connected the struggle of Scotland against England with Reformed theology
- what is the role of faithful viz a viz oppressive society?
- synod of Dort (5 principles) "uncompromising" 194
** England
- author disputes that Henry VIII "started" Anglican church
- tradition of reform went back a century or more
- Thomas Cranmer as Archbishop was the prime mover --
** 
- particularly in focus on worship and /The Book of Common Prayer/ (together with the later emerging /King James Bible/)
- /Lex orandi, lex credendi/ is a fundamental character of Anglicanism (relation between worship and belief)

- "Anglican (195) could hold any theology from near Catholic to Calvinist"

** From Puritans to Quakers
- Puritans to "purify" the church -- particularly with regard to worship (only scripture)
- "purifying" church, worked hard and saved their money
- as "character" working hard (capitalism, spirit of U.S.) -- cf. because of impact on US
- Puritans and Capitalism (Weber)
** 
- Anglicans who reacted to Puritans: John Donne, William Laud, Lancelot Andrewes, *Richard Hooker* and the /via media/
- (p. 197) "Hooker did not accept the Roman Catholic position that tradition has an authority independent of Scripture, but he did use it as a reliable guide to the interpretation of Scripture, while the Puritans wanted to read their Bibles unencumbered by traditional assumptions."
- Oliver Cromwell and again the mixing of politics and religion

- moderate and radical Puritans -- radical appealing to individual experience (of Spirit) cf. Quakers (George Fox)

** Compare Westminster & 39 articles
