#+Author: Dale Hathaway
#+Title: Age of Reason
#+Date: Spring 2021 
#+Email: hathawayd@winthrop.edu
 #+OPTIONS: reveal_width:1000 reveal_height:800 
 #+REVEAL_MARGIN: 0.1
 #+REVEAL_MIN_SCALE: 0.5
 #+REVEAL_MAX_SCALE: 2
 #+REVEAL_HLEVEL: 1
 #+OPTIONS: toc:2 num:nil
 #+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
 #+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
 #+REVEAL_PLUGINS: (markdown notes)
 #+REVEAL_THEME: beige
#+REVEAL_ROOT: ../../reveal.js/


* Religion and the Age of Reason
** 
file:./img/sf-quakes.jpg
** 
file:./img/sfeq06_01.jpg
** 
file:./img/lisbon-burning.jpeg
** 
file:./img/Lisbon-earthquake-1755.jpg
** Earthquakes and God's will
   - a tale of 2 earthquakes
   - he found the evidence for his belief in nature rather than in the Bible; he doubted a good bit of traditional doctrine—and he didn’t treat religion all that seriously.
   - Revivals but at heart a move from God to human beings

** From God-centered to Human-centered

   - 5 catalysts for change
   - at the very time of success in discovery and technology, reason seemed to reach its end of life
   - changing metaphor from Anselm to Descartes
** Religion of Reason
   - Cartesian coordinates
   - can a religion be built on Doubt?
   - No man shall ever be kept out of Heaven … if he had but an honest and good heart, that was ready to comply with Christ’s commandments
   - God is more inward to us than our very souls
** Descartes to Newton
   - Newton: God’s "immensity" stretching infinitely in all directions and unchanged for all eternity (cp. changing metaphor)
   - while retaining religion, it is no stripped of the "supernatural"
   - Church of England would keep its theology vague enough to include as many groups as possible and tolerate the presence of some dissenting groups like Anabaptists and Quakers, though not Catholics
** Locke and Deists
   - Nearly all the attitudes of the time came together in John Locke
   - https://www.youtube.com/watch?v=kItXvJLnTtk 
   - Many Deists brought to bear on the biblical miracle stories all the prestige of the scientific discovery of laws
   - Deists distrusted appeals to authority and the miraculous, but they also turned away from anything beyond natural religion in part for moral reasons.

** Pietists and Methodists

    - "*Enthusiasm*" was a dirty word in the eighteenth century.
    - story begins in Germany, where Lutheran orthodoxy had increasingly defined faith as assent to a set of doctrines
    - Lutherans suspect any call to moral improvement as a move toward works-righteousness.
    - Methodism with a "method" for holiness
    - Wesley and Whitefield changed the shape of popular religion in England and North America, but they made little impact on the attitudes among most intellectuals

** The end of Reason

   - Hume
   - Rousseau
   - Kant
