#+Author: Dale Hathaway
#+Title: City on a Hill 
#+Date: 2018-02-27 Tue
#+Email: hathawayd@winthrop.edu
#+OPTIONS: reveal_width:1000 reveal_height:800 
 #+REVEAL_MARGIN: 0.1
 #+REVEAL_MIN_SCALE: 0.5
 #+REVEAL_MAX_SCALE: 2
 #+REVEAL_HLEVEL: 1
 #+OPTIONS: toc:1 num:nil
 #+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
 #+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
 #+REVEAL_PLUGINS: (markdown notes)
 #+REVEAL_THEME: beige
#+REVEAL_ROOT: ../../reveal.js/


* Issues to wrestle with

** 5 basic tensions
- Humanity / Divinity of Christ
- Spirit and Structure
- Reason and Revelation
- Works and Grace
- Church and State
** 18th C. issues
- How do politics and science affect theology? (206)
- distrust of authority
- Reason vs. Enthusiasm
- Pietism -- Methodism
- baptismal regeneration (211 - Wesley rejected)
- "City on a hill" the dream (221)
- Edwards re. experience & theology (223)
- predestination for the Calvinists in America
- challenge of slavery to American experience

* From Enlightenment to a New world
p. 216: Ambivalence of these thinkers 

* City on a hill
** The city on a hill
 #+ATTR_REVEAL: :frag (appear)
- the *idea* of *denomination* really developed in the US
- bewildering variety of developments in US (219)
- /Indeed I tremble for my country when I reflect that God is just./ --Thomas Jefferson

#+BEGIN_NOTES
Notes:
- any story of church in America must acknowledge the denominationalism
- What does the epigraph mean?

 
#+END_NOTES
** 
:PROPERTIES:
:reveal_background: http://izquotes.com/quotes-pictures/quote-for-we-must-consider-that-we-shall-be-as-a-city-upon-a-hill-the-eyes-of-all-people-are-upon-us-so-john-winthrop-311908.jpg
:reveal_background_size: 1100px
:reveal_background_trans: slide
:END:

#+BEGIN_NOTES
note:
The vision of a light to the nations.

Quote from Bible. Identifying with a line from Ancient Israel. (Is 49.6)
#+END_NOTES
**  
:PROPERTIES:
:reveal_background: http://www.memorywebs.org/Winthrop_John_CityUponHillSpeech1630.jpg
:reveal_background_size: 1100px
:reveal_background_trans: slide
:END:

#+BEGIN_NOTES
Note:
Cartoon in faculty room: "Freedom of religion is my short term goal. My long term goal is to go into real estate."
#+END_NOTES
** 
:PROPERTIES:
:reveal_background: https://nahswingspan.com/wp-content/uploads/2016/01/calvin-hobbes-new-years-resolutions.jpg
:reveal_background_size: 1100px
:reveal_background_trans: slide
:END:

#+BEGIN_NOTES
Note:
Humor with re. "resolutions"
#+END_NOTES
** 
:PROPERTIES:
:reveal_background: http://www.quotehd.com/imagequotes/authors83/jonathan-edwards-clergyman-quote-resolution-one-i-will-live-for-god.jpg
:reveal_background_size: 1100px
:reveal_background_trans: slide
:END:

#+BEGIN_NOTES
Note:
Revival of "Great Awakening" *Fire and brimstone* and *heroic courage*
#+END_NOTES
** Sinners in the hands of an angry God (J. Edwards)
:PROPERTIES:
:reveal_background: https://img00.deviantart.net/513c/i/2012/341/5/6/sinners_in_the_hands_of_an_angry_god_drawing_by_9andrew5-d5ncxhc.jpg
:reveal_background_size: 1100px
:reveal_background_trans: slide
:END:

#+BEGIN_NOTES
Note:
We look back on the age with different eyes. How find a way to appreciate.
#+END_NOTES
** 
:PROPERTIES:
:reveal_background: https://upload.wikimedia.org/wikipedia/commons/3/3c/Masscolony.png
:reveal_background_size: 1100px
:reveal_background_trans: slide
:END:

#+BEGIN_NOTES
Note:
Mass Bay Colony. Established by *Puritans* (219) consciously seeking to make something new. Sharing a common *dream*. Quote JWinthrop p. 219). "Come for religious purity."
#+END_NOTES
* Covenant
** Territory & the Church faith within it
 #+ATTR_REVEAL: :frag (appear)
- Now to be understood as an individual's commitment (covenant) -- not a function of being born into a territory
- seen by some as a modification of strict Calvinist predetermination -- because keeping the covenant was freely entered into -- then becomes an obligation
#+BEGIN_NOTES
Note:
Federal theology: (220) God has entered into covenant and "if we fulfill our part of the agreement by believing in him, he will reward us with salvation."

John Cotton rejected the federal theology in favor of pure Calvinism.
#+END_NOTES
** Ann Hutchinson
 #+ATTR_REVEAL: :frag (appear)
- prophecies & visions -- her view that *grace* could come to anyone -- "*unpredictable grace seemed to threaten*" the discipline needed to make the "city on a hill" work (cf. quote 221)
- *conversion* came to be a requirement for inclusion in the civic community ... communion, baptism, etc.
#+BEGIN_NOTES
Note:
All of the *accomodations* required work-arounds etc.

"Puritanism seemed to be slowly yielding to *rationalism*" -- then *Great Awakening*

cp. the impact of *Billy Graham* -- ask about?

quote (222) re. his conversion
#+END_NOTES
** Jonathan Edwards
 #+ATTR_REVEAL: :frag (appear)
- science vs. traditional theology. For JE "orthodox Calvinism fit best with modern science. Accepting Locke's view that our knowledge begins with *experience*
- not necessarily *materialism* from scientific perspective
- JE saw correspondence between Newton's view of the universe and Calvin's predetestination (223) "...setting traditional doctrines in a new metaphysical context. He believed in a God so powerful he left no room for anything else."
- George Whitefield (1740) built on the outburst of conversion experiences -- JE defended the developments
#+BEGIN_NOTES
Note:
cf. the views of contemporary science?

Cf. hearing about *revival meetings* and *camp meetings* at church on Sunday
#+END_NOTES
** Rational religion
 #+ATTR_REVEAL: :frag (appear)
- Benjamin Franklin
- Thomas Jefferson
- And yet until the 1880's (223) "every state except Rhode Island still required some sort of religious affirmation from anyone seeking public office (Church & State)
- *Rationalism* "took institutional form in *Unitarianism* -- rejection of Trinity, original sin, predestination
#+BEGIN_NOTES
Note:
cf. the "gibe* about Unitarians (224)
#+END_NOTES
** Revivals on the Frontier
 #+ATTR_REVEAL: :frag (appear)
- Nathaniel W. Taylor & Lyman Beecher organizing frontier revivals
- Charles Finney carried revivals into New York -- priding himself on his lack of sophistication
- Mother Ann Lee experienced visions that led her to form a Quakerism for women (*the female aspect of divinity*)
- Oneida community -- eschatological communities
- Seventh Day Adventists -- incorporating Jewish elements into their communitarianism
- Joseph Smith: Latter Day Saints
#+BEGIN_NOTES
Cf. the opening of new communitarian experiments in the 1950's - 1970's
#+END_NOTES
** Romanticism in America
 #+ATTR_REVEAL: :frag (appear)
- reaction to *rationalism* ... a cluster of responses called *romanticism*
- Ralph W. Emerson ... appealing to *intuition* -- "transcendentalism"
- leading in a variety of paths
- Horace Bushnell (before Civil War) "attacking individualism and the emphasis on revivals and raising questions about rationalism in religion." (229)
#+BEGIN_NOTES
Note:
cf. New Age impulses going in many directions

Bushnell rejected both traditional Calvinism and Unitarianism. Literalism. Bible should be read as "poetic forms of life." Atonement in more corporate terms. -- *sounding very modern to my ears*
#+END_NOTES
** Slavery & Black religion
 #+ATTR_REVEAL: :frag (appear)
    - cf. opening p. 230 -- we must not ignore "full consequences of slavery and non-emancipation" in story of American church
    - race pecularly the criteria in American slavery
    - "In America ... only the Quakers (starting in the 1750s) really demanded" that the church reject slavery (230)
    - the unfulfilled dream of Puritan America
    - (231) ... are we a city on a hill? Inspiring the world?
#+BEGIN_NOTES
Note:
Anglicans only Protestant group not to divide over slavery and Civil War
#+END_NOTES
