#+Author: Dale Hathaway
#+Title: Enlightenment 
#+Date: 2018-02-20 Tue  
#+Email: hathawayd@winthrop.edu
 #+OPTIONS: reveal_width:1000 reveal_height:800 
 #+REVEAL_MARGIN: 0.1
 #+REVEAL_MIN_SCALE: 0.5
 #+REVEAL_MAX_SCALE: 2
 #+REVEAL_HLEVEL: 1
 #+OPTIONS: toc:1 num:nil
 #+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
 #+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
 #+REVEAL_PLUGINS: (markdown notes)
 #+REVEAL_THEME: beige
#+REVEAL_ROOT: ../../reveal.js/


* Religion and the Age of Reason
**  
   :PROPERTIES:
   :reveal_background: http://www.sciencephoto.com/image/167272/large/E3700104-1755_Lisbon_earthquake-SPL.jpg
   :reveal_background_size: 1100px
   :reveal_background_trans: slide
   :END:      



#+BEGIN_NOTES
http://www.sciencephoto.com/image/167272/large/E3700104-1755_Lisbon_earthquake-SPL.jpg
https://lifeafter40.net/wp-content/uploads/2014/12/lisbon-burning-768x518.jpeg

http://cdn.history.com/sites/2/2016/04/Post-and-Grant-Avenue.-Look-E.jpeg
San Francisco earthquake 1906
lead to the rise of Pentecostalism
preaching at Azusa, CA

https://lifeafter40.net/the-1755-lisbon-earthquake-the-start-of-atheism/
For an account of how this gave birth to "atheism" -- read to get a feel for it

file:./img/sf-quakes.jpg
file:./img/sfeq06_01.jpg
file:./img/lisbon-burning.jpeg
file:./img/Lisbon-earthquake-1755.jpg
#+END_NOTES

** 
    :PROPERTIES:
   :reveal_background: https://lifeafter40.net/wp-content/uploads/2014/12/lisbon-burning-768x518.jpeg
   :reveal_background_size: 1100px
   :reveal_background_trans: slide
   :END:      

** 
  :PROPERTIES:
   :reveal_background: http://cdn.history.com/sites/2/2016/04/Post-and-Grant-Avenue.-Look-E.jpeg
   :reveal_background_size: 1100px
   :reveal_background_trans: slide
   :END:      



** Earthquakes and God's will
Voltaire
#+ATTR_REVEAL: :frag (appear)
   - a tale of 2 earthquakes
   - he found the evidence for his belief in nature rather than in the Bible; he doubted a good bit of traditional doctrine—and he didn’t treat religion all that seriously.
   - Revivals but at heart a move from God to human beings
#+BEGIN_NOTES
Do we explain these by reference to God? No? We are inheritors of Enlightenment.

p. 203 it is the *shifting of place* re. God and world -- what is important
#+END_NOTES
** From God-centered to Human-centered
   - 5 catalysts for change (204)
#+ATTR_REVEAL: :frag (appear)
     1. wars of religion
     2. Europe divided
     3. philosophical attitudes encouraged questioning tradition
     4. science seemed to being moving from one accomplishment to another ...
     5. nationalism taking root, centralizing power
** 
   - at the very time of success in discovery and technology, reason seemed to reach its end of life
* Descartes to Newton
** Newton on religion
#+ATTR_REVEAL: :frag (appear)
   - Newton: God’s "immensity" stretching infinitely in all directions and unchanged for all eternity (cp. changing metaphor) (cp. Borges)
   - what was most important about religion was its morality  -- cf. Jefferson's approach (206)
   - while retaining religion, it is no stripped of the "supernatural"
   - "natural religion" (206)
   - Church of England would keep its theology vague enough to include as many groups as possible and tolerate the presence of some dissenting groups like Anabaptists and Quakers, though not Catholics
   #+BEGIN_NOTES
   cf. 3 parts of Anglican: hi, lo, broad
   #+END_NOTES
** Borges
 Universal history is the history of a handful of metaphors
    - changing metaphor from Anselm to Descartes

 #+BEGIN_NOTES
 read from /Labyrinths/ "The fearful sphere of Pascal"
 #+END_NOTES

*** Locke and Deists
#+ATTR_REVEAL: :frag (appear)
    - Nearly all the attitudes of the time came together in John Locke (207)
    - https://www.youtube.com/watch?v=kItXvJLnTtk 
    - Many Deists brought to bear on the biblical miracle stories all the prestige of the scientific discovery of laws (209)
    - Deists distrusted appeals to authority and the miraculous, but they also turned away from anything beyond natural religion in part for moral reasons.

*** Religion of Reason

 Descartes argued that knowledge would come only from doubting everything
#+ATTR_REVEAL: :frag (appear)
    - can a religion be built on Doubt?
    - No man shall ever be kept out of Heaven … if he had but an honest and good heart, that was ready to comply with Christ’s commandments (205)
    - God is more inward to us than our very souls (205)

*** Pietists and Methodists
#+ATTR_REVEAL: :frag (appear)
     - "*Enthusiasm*" was a dirty word in the eighteenth century. (210)
     - story begins in Germany, where Lutheran orthodoxy had increasingly defined faith as assent to a set of doctrines
     - Lutherans suspect any call to moral improvement as a move toward works-righteousness.
     - rise of *Pietism* (210)
     - Moravians and J. Wesley intersect (211)
     - Methodism with a "method" for holiness
     - Wesley and Whitefield changed the shape of popular religion in England and North America, but they made little impact on the attitudes among most intellectuals
     #+BEGIN_NOTES
     Read Wesley quote of his conversion p. 211

 nb. that for Wesley, too, morality was more important than doctrine
     #+END_NOTES

* The end of Age of Reason

** Hume
#+ATTR_REVEAL: :frag (appear)
- skeptic of scientific inference producing absolute knowledge
- apply skepticism to argument from order; miracles; and others ...

** Rousseau
#+ATTR_REVEAL: :frag (appear)
- doubting even *civilization* -- cf. /Emile/ raised as a *natural child*
- follow self & respect others (214)
- Lessing: story of 3 rings (214)

#+BEGIN_NOTES
see how we identify with the motto of Rousseau above
#+END_NOTES

** Kant
#+ATTR_REVEAL: :frag (appear)
- seeking necessity of religion apart from historical evidence
- Pietist upbringing
- his arguments *begin with ethics* -- /universal imperative/
- like much of enlightenment thinkers: accepting God but nothing to do with most *doctrine*
- summary (217)

#+BEGIN_NOTES
we ought to do the thing that we could make a universal law
#+END_NOTES
