#+Author: Dale Hathaway
#+Title: Judaism: 101
#+Date: Week of April 12, 2020
#+Email: hathawayd@winthrop.edu
#+OPTIONS: org-reveal-title-slide:"%t"
#+OPTIONS: reveal_width:1000 reveal_height:800 
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2
#+REVEAL_HLEVEL: 1
#+OPTIONS: toc:1 num:nil
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
#+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
#+REVEAL_PLUGINS: (markdown notes)
#+REVEAL_ROOT: ../../reveal.js
#+REVEAL_THEME: beige


** Abrahamic Religions

*** Names of God
- 'el :: Perhaps the oldest name for "god" in the Hebrew Bible, 'E:lohiym אלהים
- (God) "Elohim" :: is another name used for God. It is a plural form of the older name for God "el".
- yhwh יהןה :: (Yahweh or LORD) This is the holy name of God; cf. Exodus 3, where Moses learns about this name, although it had been used from the beginning of the text of Genesis. By the time of Jesus, it was no longer pronounced.

- adonai אדני :: (Lord) This is the ordinary hebrew word which would have referred to a person. The name "Jehovah" was mistakenly derived from combining the vowels of the word "adonai" with the consonants of the tetragrammaton "yhwh". *HaShem* is used when even saying "adonai" is too holy to speak.
- Allāh الله :: from ancient times the name for "God" by Arabic peoples. Allah recited to Muhammad the Quran. And a 3rd religion emerged, Islam.

#+begin_notes
Note:
- Hebrew is primarily written in consonants. Try reading a text with all the vowels removed. You can do pretty well. If you removed the consonants it is gibberish.
- It is clear that both El (Elohim) and Allah are linguistically related.
- the account of God revealing his name, YHWH, is found in Exodus ch. 3. The basis of the name is in some sense related to the verb "to be." 

#+end_notes
** Judaism 101

History of Jews in 10 min: https://youtu.be/KR9sWRzbdJw


*** What is Judaism?

-  a religion, or
-  a race, or
-  a culture, or 
-  a nation

*All of these descriptions have some validity.*

#+BEGIN_NOTES
    The Jewish people are perhaps best described as an **extended family**

    What is Judaism? What does it mean to be a Jew? Most people, both Jewish
    and gentile, would instinctively say that Judaism is a religion. And
    yet, there are militant atheists who insist that they are Jews! Is
    Judaism a race? If you were to say so, most Jews would think you were an
    antisemite! So what is Judaism?
#+END_NOTES


*** 1. Is Judaism a Religion?

-  In some senses anyway it is clearly a religion
-  However many Jews do *not* believe in religion at all
-  many don't believe in *G-d*


#+BEGIN_NOTES

Note:
    Clearly, there is a religion called Judaism, a set of ideas about
    the world and the way we should live our lives that is called "Judaism."
    It is studied in Religious Studies courses and taught to Jewish children
    in Hebrew schools. See What do Jews Believe? for details. There is a lot
    of flexibility about certain aspects of those beliefs, and a lot of
    disagreement about specifics, but that flexibility is built into the
    organized system of belief that is Judaism.

    However, many people who call themselves Jews do not believe in that
    religion at all! More than half of all Jews in Israel today call
    themselves "secular," and don't believe in G-d or any of the religious
    beliefs of Judaism. Half of all Jews in the United States don't belong
    to any synagogue. They may practice some of the rituals of Judaism and
    celebrate some of the holidays, but they don't think of these actions as
    religious activities.

    The most traditional Jews and the most liberal Jews and everyone in
    between would agree that these secular people are still Jews, regardless
    of their disbelief. See Who is a Jew? Clearly, then, there is more to
    being Jewish than just a religion.
#+END_NOTES


*** 2. Are Jews a Race?

-  US Supreme Court in 1980's -- "Yes"
-  reasoning: "Jewish Race" -- "Negro Race"


#+BEGIN_NOTES

Note:
    - In the 1980s, the United States Supreme Court ruled that Jews are a
    race, at least for purposes of certain anti-discrimination laws.
    - Their reasoning: at the time these laws were passed, people routinely
    spoke of the "Jewish race" or the "Italian race" as well as the "Negro
    race," so that is what the legislators intended to protect.

    But many Jews were deeply offended by that decision, offended by any
    hint that Jews could be considered a race. The idea of Jews as a race
    brings to mind nightmarish visions of Nazi Germany, where Jews were
    declared to be not just a race, but an inferior race that had to be
    rounded up into ghettos and exterminated like vermin.

    But setting aside the emotional issues, Jews are clearly not a race.

    Race is a genetic distinction, and refers to people with shared ancestry
    and shared genetic traits. You can't change your race; it's in your DNA.
    I could never become black or Asian no matter how much I might want to.

    Common ancestry is not required to be a Jew. Many Jews worldwide share
    common ancestry, as shown by genetic research; however, you can be a Jew
    without sharing this common ancestry, for example, by converting. Thus,
    although I could never become black or Asian, blacks and Asians have
    become Jews (Sammy Davis Jr. and Connie Chung).
#+END_NOTES


*** 3. Is It a Culture or Ethnic Group?

-  secular American Jews think of their *Jewishness* as a matter of culture or ethnicity
-  e.g. food, Yiddish, holidays, values like emphasis on education


#+BEGIN_NOTES

Note:
    - Most secular American Jews think of their Jewishness as a matter

    of culture or ethnicity. - When they think of Jewish culture, they think
    of - the food, - of the Yiddish language, - of some limited holiday
    observances, and - of cultural values like the emphasis on education.

    Those secular American Jews would probably be surprised to learn that
    much of what they think of as Jewish culture is really just Ashkenazic
    Jewish culture, the culture of Jews whose ancestors come from one part
    of the world. Jews have lived in many parts of the world and have
    developed many different traditions. As a Sephardic friend likes to
    remind me, Yiddish is not part of his culture, nor are bagels and lox,
    chopped liver, latkes, gefilte fish or matzah ball soup. His idea of
    Jewish cooking includes bourekas, phyllo dough pastries filled with
    cheese or spinach. His ancestors probably wouldn't know what to do with
    a dreidel. There are certainly cultural traits and behaviors that are
    shared by many Jews, that make us feel more comfortable with other Jews.
    Jews in many parts of the world share many of those cultural aspects.
    However, that culture is not shared by all Jews all over the world, and
    people who do not share that culture are no less Jews because of it.
    Thus, Judaism must be something more than a culture or an ethnic group.
#+END_NOTES


*** 4. Are the Jews a Nation?

-  The traditional explanation, and the one given in the Torah, is that the Jews are a nation.
-  The Hebrew word for "nation" is "goy."
-  ancient sense meaning a *group of people with a common history, a common destiny, and a sense that we are all connected to each other*.


#+BEGIN_NOTES

Note:
    Unfortunately, in modern times, the term "nation" has become too
    contaminated by ugly, jingoistic notions of a country obsessed with its
    own superiority and bent on world domination. Because of this notion of
    "nationhood," Jews are often falsely accused of being disloyal to their
    own country in favor of
    their loyalty to the Jewish "nation," of being
    more loyal to Israel than to their home country. Some have gone so far
    as to use this distorted interpretation of "nationhood" to prove that
    Jews do, or seek to, control the world. In fact, a surprising number of
    antisemitic websites and newsgroup postings linked to this page (in an
    earlier form) as proof of their antisemitic delusions that Jews are
    nationalistic, that Israel is a colonial power and so forth. Because of
    the inaccurate connotations that have attached themselves to the term
    "nation," the term can no longer be used to accurately describe the
    Jewish people.

    - The Torah and the rabbis used this term not in the modern sense
        meaning a territorial and political entity, but in the ancient sense
        meaning a **group of people with a common history, a common destiny,
        and a sense that we are all connected to each other**.
#+END_NOTES


** Who Is a Jew?

-  A Jew is any person whose mother was a Jew or any person who has gone through the formal process of conversion to Judaism.
-  there are perhaps about 13 million Jews in the world. (ca. 6 mill. in US and 5 mill in Israel)
-  2 major traditions *Sephardic* (Spanish/Middle Eastern) and *Ashkenazic* (German/Eastern European) Jews, and other cultural subgroups of Judaism.
-  Judaism does not maintain that Jews are better than other people.


#+BEGIN_NOTES

Note:
    - A Jew is any person whose mother was a Jew or any person who has gone
    through the formal process of conversion to Judaism.
    - Most estimates suggest that there are about 13 million Jews in the
    world. The vast majority of these Jews live in either the United
    States (about 6 million) and Israel (about 5 million).
    - the differences between **Sephardic** (Spanish/Middle Eastern) and
    **Ashkenazic** (German/Eastern European) Jews, and other cultural
    subgroups of Judaism.
    - Judaism does not maintain that Jews are better than other people.
        
#+END_NOTES


*** Traditional beliefs

a short list of the traditional beliefs of Judaism would include the
following:

-  God is creator *all*.
-  He is *one*
-  He alone is to be worshipped
-  first 5 books of Hebrew Bible were revealed to Moses by God
-  God rewards and punishes for good and evil deeds


#+BEGIN_NOTES

Note:
    - God is the creator of all that exists; He is one, incorporeal

    (without a body), and He alone is to be worshipped as absolute ruler of
    the universe. - The first five books of the Hebrew Bible were revealed
    to Moses by God. They will not be changed or augmented in the future. -
    God has communicated to the Jewish people through prophets. - God
    monitors the activities of humans; He rewards individuals for good deeds
    and punishes evil.
#+END_NOTES


** Major differences from Christianity:

-  consider *actions and behavior to be of primary importance*;
-  no concept of *original sin*
-  *affirms the inherent goodness of the world and its people as creations of God*


#+BEGIN_NOTES

Note:
    Although Christians base much of their faith on the same Hebrew
    Scriptures as Jews do, there are major differences in belief:

    - Jews generally consider **actions and behavior to be of primary
        importance**; beliefs come out of actions. This conflicts with
        conservative Christians for whom belief is of primary importance and
        actions are a result of that belief.
    - Jewish belief does not accept the Christian concept of **original sin**
        (the belief that all people have inherited Adam and Eve's sin when
        they disobeyed God's instructions in the Garden of Eden).
    - Judaism **affirms the inherent goodness of the world and its people as
        creations of God**.
#+END_NOTES

** Historical origins?
*** Development of Scripture

*** What is? Who is?

*** Belief and Practice
