#+Author: Dale Hathaway
#+Title: Toward Definition of Religion
#+Date: 2018-01-17 Wed
#+Email: hathawayd@winthrop.edu
#+OPTIONS: org-reveal-title-slide:"%t"
#+OPTIONS: reveal_width:1000 reveal_height:800 
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2
#+REVEAL_HLEVEL: 1
#+OPTIONS: toc:1 num:nil
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
#+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
#+REVEAL_PLUGINS: (markdown notes)
#+REVEAL_THEME: beige
* Assessing our Spirituality


*Reflect on your own Spirituality*

Tell us about your spiritual life. Do you belong to an organized religion? Would you describe yourself as "spiritually thirsty"? Is being "close to God" a life goal for you? Why or why not?

Your assignment will be graded an "A" if it meets the following criteria: 1) Your reflection demonstrates that you read and thought about the questions, 2) that you come to the next class and 3) share your insights. A "B" response will be missing 1 of the criteria. A "C" response will be missing 2 of the criteria.
** COMMENT Process
#+ATTR_REVEAL: :frag (appear)
- Count off to 9
- Gather and give each person a chance to share their results of the assignment
- One person report to the class, summarizing each of the responses.
* Studying Religion
**  Tools Used in the Study Religion
Religious studies is the attempt to study these things, taking *homo religiosus* seriously

#+ATTR_REVEAL: :frag (appear)
- Textual: study sacred texts 
- Historical: describe origin and development of specific religions 
- Comparative: compare specific types of religious behaviors, beliefs 
- Philosophical: philosophical analysis of religious language and arguments 
- Intellectual & Social History: trace development of religious ideas and institutions over time 

** "What is required is perspective" (p. 8)

*** A North American touring the highlands of New Guinea for a visit to one of the tribes living in the outback might well witness men decorated in bird-of-paradise feathers, nude (save for a penis sheath), covered in ashes, and dancing before a fire at the side of which are pigs bound in vines and banana leaves. His or her first reaction might well be to take some photographs in order to show “the folks back home” some  of the exotic aspects of life among primitive peoples. But this picture can be reversed. 

*** Suppose the tribesmen of the outback visit a downtown church on Sunday morning. They observe rows of oddly dressed people (what, after all, is the purpose of a necktie?), notice that some sit while others sing, listen to one person speak at length, and see still others pass plates onto which paper and metal disks are placed. What are these tribesmen to think? Where, after all, are the pigs? The fire? The sacred feathers? In both cases, the observer lacks a sense of perspective and context. 
 
*** The lesson is a simple one. It is impossible to get at the intention that lies behind religious behavior unless we have a willingness to *enter sympathetically into the cultural worldview of another person*, at least for a moment.




*  Possible Definitions of Religion

**  1
| (*James Martineau*)          | Religion is the belief in an ever living God, that is, in a *Divine Mind and Will* ruling the Universe and holding moral relations with mankind.     |
| (*Friedrich Schleiermacher*) | Religion is the *feeling of absolute dependence* or the consciousness that the whole of our spontaneous activity comes from a source outside of us . |

#+BEGIN_NOTES
 Note:
 21 April 1805 – 11 January 1900) was an English religious philosopher influential in the history of Unitarianism.

 For 45 years he was Professor of Mental and Moral Philosophy and Political Economy in Manchester New College, the principal training college for British Unitarianism.

Note: 
November 21, 1768 – February 12, 1834) was a German theologian, philosopher, and biblical scholar known for his attempt to reconcile the criticisms of the Enlightenment with traditional Protestant Christianity. He also became influential in the evolution of Higher Criticism, and his work forms part of the foundation of the modern field of hermeneutics. Because of his profound effect on subsequent Christian thought, he is often called the "Father of Modern Liberal Theology" and is considered an early leader in liberal Christianity. The Neo-Orthodoxy movement of the twentieth century, typically (though not without challenge) seen to be spearheaded by Karl Barth, was in many ways an attempt to challenge his influence.

#+END_NOTES

** 2
| (*Karl Marx*)       | Religious suffering is, at one and the same time, the expression of real suffering and a protest against real suffering. Religion is the sigh of the oppressed creature, the heart of a heartless world, and the soul of soulless conditions. It is the opium of the people. |
| (*Anthony Wallace*) | Religion is a *set of rituals, rationalized by myth*, which mobilizes supernatural powers for the purpose of achieving or preventing transformations of state in man or nature .                                                                                               |


#+BEGIN_NOTES
The nineteenth-century German thinker Karl Marx, the founder and primary theorist of Marxism, had an antithetical and complex attitude to religion,[1] viewing it primarily as "the soul of soulless conditions", the "opium of the people" that had been useful to the ruling classes since it gave the working classes false hope for millennia. At the same time Marx saw religion as a form of protest by the working classes against their poor economic conditions and their alienation.[2]

 Note:
 (April 15, 1923 - October 5, 2015) was a Canadian-American anthropologist who specialized in Native American cultures, especially the Iroquois. His research expressed an interest in the intersection of cultural anthropology and psychology. He was famous for the theory of revitalization movements.[1]

#+END_NOTES

**  3
| (*Emile Durkheim*) | Religion is only  *sentiment inspired by the group in its members*, but projected outside of the consciousness that experiences them, and objectified .                                                                                                                                                                                                                                                                    |
| (*Signmund Freud*) | Freud refers to religion as an illusion which is "perhaps the most important item in the psychical inventory of a civilization". In his estimation, religion provides for defense against "the crushingly superior force of nature" and "the urge to rectify the shortcomings of civilization which made themselves painfully felt". He concludes that all religious beliefs are "illusions and insusceptible of proof." |


#+BEGIN_NOTES
Note:
April 15, 1858 – November 15, 1917) was a French sociologist, social psychologist and philosopher. He formally established the academic discipline and—with Karl Marx and Max Weber—is commonly cited as the principal architect of modern social science and father of sociology.[2][3]

Sigmund Freud's views on religion are described in several of his books and essays. Freud regarded God as an illusion, based on the infantile need for a powerful father figure; religion, necessary to help us restrain violent impulses earlier in the development of civilization, can now be set aside in favor of reason and science.[1]
#+END_NOTES
**  4
| (James G. *Frazer*) | Religion is a propitiation or conciliation of powers superior to man which are believed to direct and control the course of Nature and of human life .                                           |
| (*William James*)   | The very fact that there are so many (definitions of religion) … is enough to prove that the word “religion” cannot stand for any single principle or essence, but is rather a collective name … |



#+BEGIN_NOTES

 Note:
 1 January 1854 – 7 May 1941), was a Scottish social anthropologist influential in the early stages of the modern studies of mythology and comparative religion.[2] He is often considered one of the founding fathers of modern anthropology.

 His most famous work, The Golden Bough (1890), documents and details the similarities among magical and religious beliefs around the globe. Frazer posited that human belief progressed through three stages: primitive magic, replaced by religion, in turn replaced by science

#+END_NOTES

**  A Definition of Religion

*cautious, recognizing that we cannot escape our own perspective* ... 

The very attempt to define religion, to find some distinctive or possibly unique essence or set of qualities that distinguish the "religious" from the remainder of human life, is primarily a Western concern. The attempt is a natural consequence of the Western speculative, intellectualistic, and scientific disposition. It is also the product of the dominant Western religious mode, what is called the Judeo-Christian climate or, more accurately, the theistic inheritance from Judaism, Christianity, and Islam. 

** COMMENT
The theistic form of belief in this tradition, even when downgraded culturally, is formative of the dichotomous Western view of religion. That is, the basic structure of theism is essentially a distinction between a transcendent deity and all else, between the creator and his creation, between God and man. (<http://en.m.wikipedia.org/wiki/Religion#Definitions>)

*  Elements of Religion

#+ATTR_REVEAL: :frag (appear)
 - Human thought
 - Feeling
 - Action
 - Social interconnectedness
 - Values


**  Religion and Human Thought
Religion is intimately connected with human thought.

Even those who focus on practice have beliefs, develop doctrines, and emphasize the importance of certain teachings in the religious life essential to their way of life.




**  Religion and Feeling
To some extent, all religious experience is an emotional experience.

Friedrich Schleiermacher characterized religion as a *feeling of absolute dependence*. 

Rudolf Otto, characterized religion as the *experience of the holy*. And this experience is one that inspires feelings of fear, awe, terror, and love. 




**  Religion and Action
 While the form and place of religious action vary, the importance of action to an understanding of religion is evident.

  Examples of religious action:

#+ATTR_REVEAL: :frag (appear)
 1. Islam = the duty of prayer and *salat*
 2. Shinto = approach the shrine of kami by washing, ringing a bell, and clapping their hands
 3. Roman Catholicism =  attend mass
 4. Methodism = outer holiness, inner holiness, spreading holiness

**  Individual and Social Existence
#+ATTR_REVEAL: :frag (appear)
- Most of the great religions make a place for *individual devotion* and encourage persons to search for *union with the ultimate reality*.
- But we must be careful not to overstress the individual dimension of religion.
 - One of the most elementary components of religion is some emphasis on the idea of society. 
 - Thus, the essence of religion is the ways in which it enables individual persons to identify with the values associated with a particular group. 

**  Values and Religion
 In most times and places, religion has been closely connected with morality.

#+ATTR_REVEAL: :frag (appear)
 - To some, religion confirms the moral law and gives one power to perform one's duty. 
 - Religion is a way of expressing important societal values. 
   - For example, when believers in various settings pray or offer sacrifices to honor God, or to ward off spirits that threaten tribal unity, they express their sense of what is important in life.

*  What kind of stuff? : Substance or Function?

**  Functionalist Definition of Religion
#+ATTR_REVEAL: :frag (appear)
 - Focuses on the role religion plays in the lives of persons and groups.
 - Might focus on the ways religion enables people to sustain hope in the face of difficult circumstances.
 - “Functionalist” understands *religion* to have to with the role it plays ordering, making sense, of human existence



**  Substantive Definition of Religion
#+ATTR_REVEAL: :frag (appear)
 - Attempts to limit the phenomena that may be characterized as religious.
 - Seeks to identify what it is that makes certain responses to death and suffering religious and others not.
 - “Substantive” recognizes that *religion* to be contrasted with the many other … isms or ways of thought etc. that function to make life bearable, ordered, etc. (cf. Martineau's definition above)



**  Definition must be both

#+ATTR_REVEAL: :frag (appear)
 - Considerations of function are necessary but not sufficient to the task of defining religion.
 - But an adequate definition of religion must include a substantive component.
 - Thus, *any adequate definition of religion must account for both the function and substance of religion.*

#+ATTR_REVEAL: :frag (appear)
 1. Religion and politics overlap but are not the same
 2. Religion and morality overlap but are not the same
 3. religion and science overlap but are not the same
 4. … history?



*  A Proposed Definition


**  Religion signifies those ways of viewing the world that refer to:

#+ATTR_REVEAL: :frag (appear)
 1. a notion of sacred reality
 2. made manifest in human experience
 3. in such a way as to produce long-lasting ways of thinking, feeling, and acting
 4. with respect to problems of ordering and understanding existence

*  A Notion of Sacred Reality

#+ATTR_REVEAL: :frag (appear)
 - A *notion of sacred reality establishes a boundary between religion and non-religion.*
 - *Sacred* indicates a reality that is somehow distinct, set apart, other than *ordinary*.
 - Sacred reality includes the God of the *Bible*, the *Qur'anic Allah*, the *Brahman* of Hinduism, Buddhism's *Nirvana*, the *kami* of Shinto.




**  Manifest in Human Experience

#+ATTR_REVEAL: :frag (appear)
- Although the sacred is set apart from the ordinary, it nevertheless may be experienced, thought about, and acted upon.
- Thus, all religion has to do with the element of the *sacred manifesting itself in various ways*: in rituals, persons, and natural phenomena. 
#+ATTR_REVEAL: :frag (appear)
  1. Muslims = the sacred reality (**Allah**) is made manifest through prophecy
  2. Buddhists = the goal of *Nirvana* comes to life in the life and teaching of the Buddha
  3. Navaho = the story of the Navaho people makes wisdom available for those who seek harmony between all things.




**  Long-Lasting Ways of Thinking and Feeling

#+ATTR_REVEAL: :frag (appear)
 - Religious ways develop over time.  And they come to constitute traditions that may be identified with the history of particular communities.
 - For example, the prophecy of Muhammad is the beginning of the tradition of Islam.
 - Islam's message and the story of its revelation in seventh-century Arabia have produced characteristic modes of thought, feeling, and action among a large percentage of the world's population.




**  Ordering and Understanding Existence

#+ATTR_REVEAL: :frag (appear)
 - Stresses the way in which notions of sacred reality are related to problems of suffering and death.
 - Also stresses the way in which notions of sacred reality are related to other problems; such as the ordering of political or economic life.
