#+Author: Dale Hathaway
#+Title: Hesse's Siddhartha 
#+Date:2018-02-14 Wed  
#+Email: hathawayd@winthrop.edu
#+OPTIONS: org-reveal-title-slide:"%t"
#+OPTIONS: reveal_width:1000 reveal_height:800 
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2
#+REVEAL_HLEVEL: 1
#+OPTIONS: toc:2  num:nil
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
#+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
#+REVEAL_PLUGINS: (markdown notes)

*  Hesse Introduction
**  Hesse overview
 <https://www.hermann-hesse.de/en/biography>
#+ATTR_REVEAL: :frag (appear)
- Religion
    - Father Christian minister
    - living in a world of a diversity of religions
    - life-long *search*
#+ATTR_REVEAL: :frag (appear)
- Life crisis (“author of crisis”)
    - influence of Freud & psychoanalysis
    - we saw in Sacred Quest that psychoanalysis can be seen to function something like a religion
#+ATTR_REVEAL: :frag (appear)
- Travel to India
**  Hearing his "voice"
"For many years, I have been convinced that the European spirit is on the wane, and is in need of a return to its Asian roots. I have admired Buddha for many years, and have been reading Indian literature since my earliest youth. Later, I became more familiar with Lao Tsu and the other Chinese philosophers“
#+ATTR_REVEAL: :frag (appear)
- We can hear his voice in an excerpt from this essay on language:  https://www.hermann-hesse.de/node/2586
**  Setting of the novel
cf. translator's preface
#+ATTR_REVEAL: :frag (appear)
- On the one hand, set in imagined India of 5-6th c. BCE
- On the other hand, written in "Machine Age Europe"
*  Kinds of Stories 
**  Booker's 7 basic types of story plots
<https://tobedwithatrollope.wordpress.com/2007/12/11/the-seven-basic-plots-wh-we-tell-stories-by-christopher-booker/>
***  1-2
#+ATTR_REVEAL: :frag (appear)
- *Overcoming the Monster* — Stories like Beowulf, ‘Little Red Riding Hood’, Jaws, and many of the James Bond films, where a hero must defeat a monster and restore order to a world that has been threatened by the monster’s presence.
- *Rags to Riches* — These stories feature modest, generally virtuous but downtrodden characters, who achieve a happy ending when their special talents or true beauty is revealed to the world at large. Includes any number of classics such as ‘Cinderella’, David Copperfield, and the Horatio Alger novels.
***  3-4
#+ATTR_REVEAL: :frag (appear)
- *The Quest* — A hero, often accompanied by sidekicks, travels in search of a priceless treasure and fights against evil and overpowering odds, and ends when he gets both the treasure and the girl. The Odyssey is a classic example of this kind of story.
- *Voyage and Return* — Alice in Wonderland, Robinson Crusoe on his desert island, other stories of normal protagonists who are suddenly thrust into strange and alien worlds and must make their way back to normal life once more.
***  5-7
#+ATTR_REVEAL: :frag (appear)
- *Comedy* — Not always synonymous with humour. Instead, the plot of a comedy involves some kind of confusion that must be resolved before the hero and heroine can be united in love. Think of Shakespeare’s comedies, The Marriage of Figaro, the plays of Oscar Wilde and Gilbert and Sullivan, and even War and Peace.
- *Tragedy* — As a rule, the terrible consequences of human overreaching and egotism. The Picture of Dorian Gray, Julius Caesar, Anna Karenina…this category is usually self-evident.
- *Rebirth* — The stories of Ebeneezer Scrooge and Mary Lennox would fall into this basic plot type, which focuses on a threatening shadow that seems nearly victorious until a sequence of fortuitous (or even miraculous) events lead to redemption and rebirth, and the restoration of a happier world.
*  Hesse (2)
**  Religion is/is not
** first, religion is *not*:
#+ATTR_REVEAL: :frag (appear)
-   necessarily monotheistic,
-   necessarily a body of moral rules
-   necessarily a belief in the supernatural, heaven, hell, or even life after death
-   necessarily an explanation of the origins of creation.
** Religion *is*:
#+ATTR_REVEAL: :frag (appear)
-   notion of sacred reality
-   orders and brings understanding to human existence
-   has lasting effect on thinking, feeling, acting
**  5 Themes of Siddhartha
 Write on a piece of  paper an example from text of:
1. Self-realization
2. Personal experience vs. Formal training
3. Persistence
4. Folly of materialism or less is more
5. paradox of unreal reality (reality is an illusion)
**  With a partner discuss:
1. most important illustration of the theme from the text
2. How important was that theme in the context of the whole work
3. What does the theme tell us about religion?
