#+Author: Dale Hathaway
#+Title: Sacred Texts
#+Date: March 4, 2020
#+Email: hathawayd@winthrop.edu
#+OPTIONS: org-reveal-title-slide:"%t"
#+OPTIONS: reveal_width:1000 reveal_height:800 
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2
#+REVEAL_HLEVEL: 1
#+OPTIONS: toc:1 num:nil
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
#+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
#+REVEAL_PLUGINS: (markdown notes)
#+REVEAL_ROOT: ../../reveal.js
#+REVEAL_THEME: beige

*** Sacred texts
    :PROPERTIES:
    :CUSTOM_ID: sacred-texts
    :END:
**** hermeneutics / interpretation
     :PROPERTIES:
     :reveal_background: https://drive.google.com/uc?export=view&id=11KtvsOR4wCkztxg1FVlut6nXWhYtFBKs
     :reveal_background_trans: slide
    :reveal_background_size: 800px
     :END:

**** 4 functions of Sacred Stories (including scriptures): 

  1. connect with sacred,
  2. order cosmos,
  3. pass on the *traditio*, and
  4. instill ethical expectations and norms

  #+BEGIN_NOTES
  Perhaps leave this overview without going into detail of the functions

  - *Connect us to the sacred*:
    - reveal the sacred and provide a vehicle for (or mediate) encounter with the sacred through the imaginative experience and ritual re-enacting of the story;
    - reveal a path to the sacred (e.g. Buddha's journey to enlightenment);
    - provide insight/wisdom re: ultimate truth. 
  - *Order the cosmos*:
    - give an account of the nature, purpose, order, and destiny of the universe,
    - explain how things are related, where things belong, what they mean, how it all fits together ultimately;
    - relate the transcendent reality to the ordinary reality.  
  - *Traditio*:
    - "hand over" a way of life, worldview, set of practices, values, and stories that constitute a community over time from one generation to the next.
    - Remember truth handed on from the past and bring it to life in the present by helping people to apply it and live it out today.
    - Continue a way of life and teach it to the next generation.
    - Tradition—an extended conversation about the meaning of life of a community over time.
  - *Convey an Ethic*:
    - present patterns, models (saints, prophets), and standards of behavior for living in harmony with the sacred order.
    - E.g. Sunna = the beaten path of the prophet Mohammed.

  #+END_NOTES

*** Familiar Texts
**** Bible 
     :PROPERTIES:
     :CUSTOM_ID: nt-obey-the-government
     :END:
 Let every person be subject to the governing authorities; for there is no authority except from God, and those authorities that exist have been instituted by God.  Therefore whoever resists authority resists what God has appointed, and those who resist will incur judgment.  For rulers are not a terror to good conduct, but to bad. Do you wish to have no fear of the authority? Then do what is good, and you will receive its approval;  for it is God’s servant for your good. But if you do what is wrong, you should be afraid, for the authority[a] does not bear the sword in vain! It is the servant of God to execute wrath on the wrongdoer.  Therefore one must be subject, not only because of wrath but also because of conscience.  For the same reason you also pay taxes, for the authorities are God’s servants, busy with this very thing.  Pay to all what is due them—taxes to whom taxes are due, revenue to whom revenue is due, respect to whom respect is due, honor to whom honor is due.
#+begin_notes
verses not in original

Rom 13: 1-7
#+end_notes
**** Bible 
     :PROPERTIES:
     :CUSTOM_ID: ot-dont-touch-a-football
     :END:
From among all the land animals, these are the creatures that you may eat.  Any animal that has divided hoofs and is cleft-footed and chews the cud—such you may eat.  But among those that chew the cud or have divided hoofs, you shall not eat the following: the camel, for even though it chews the cud, it does not have divided hoofs; it is unclean for you.  The rock badger, for even though it chews the cud, it does not have divided hoofs; it is unclean for you.  The hare, for even though it chews the cud, it does not have divided hoofs; it is unclean for you.  The pig, for even though it has divided hoofs and is cleft-footed, it does not chew the cud; it is unclean for you. 8 Of their flesh you shall not eat, and their carcasses you shall not touch; they are unclean for you.
#+begin_notes
 Leviticus 11:1-8
#+end_notes

**** Bible 
     :PROPERTIES:
     :CUSTOM_ID: psalm-137
     :END:
 By the rivers of Babylon— there we sat down and there we wept when we remembered Zion.
 On the willows there we hung up our harps.
 For there our captors asked us for songs, and our tormentors asked for mirth, saying, “Sing us one of the songs of Zion!”
 How could we sing the Lord’s song in a foreign land?

...

8 O daughter Babylon, you devastator! Happy shall they be who pay you back what you have done to us!
9 Happy shall they be who take your little ones and dash them against the rock!

#+begin_notes
Psalm 137 1-4, 8-9
#+end_notes
*** Non-verbal
    :PROPERTIES:
    :reveal_background: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Altamira_bisons.jpg/1280px-Altamira_bisons.jpg
    :reveal_background_size: 800px
    :END:

    #+begin_notes
     
cave painting

Altamira
The Cave of Altamira (/ˌæltəˈmɪərə/; Spanish: Cueva de Altamira [ˈkweβa ðe altaˈmiɾa]) is located near the historic town of Santillana del Mar in Cantabria, Spain. It is renowned for prehistoric parietal cave art featuring charcoal drawings and polychrome paintings of contemporary local fauna and human hands. The earliest paintings were applied during the Upper Paleolithic, around 36,000 years ago.[1] The site was only discovered in 1868 by Modesto Cubillas.
- https://en.wikipedia.org/wiki/Cave_painting

new discoveries re. Neanderthals

pictographs

    #+end_notes
*** Texts (Other)
**** Quran 
     :PROPERTIES:
     :CUSTOM_ID: praise-piece-in-quran
     :END:
 In the name of God, the Gracious, the Merciful.
 Praise be to God, Lord of the Worlds.
 The Most Gracious, the Most Merciful.
 Master of the Day of Judgment.
 It is You we worship, and upon You we call for help.
 Guide us to the straight path.
 The path of those You have blessed, not of those against whom there is anger, nor of those who are misguided.
     #+begin_notes
  https://www.clearquran.com/

 sura 1

    
     #+end_notes
**** Quran 
     :PROPERTIES:
     :CUSTOM_ID: abraham-piece-in-quran
     :END:

 The Jews and the Christians will not approve of you, unless you follow their creed. Say, "God's guidance is the guidance." Should you follow their desires, after the knowledge that has come to you, you will have in God neither guardian nor helper.

 Those to whom We have given the Scripture follow it, as it ought to be followed---these believe in it. But as for those who reject it---these are the losers.

 O Children of Israel! Remember My blessing which I bestowed upon you, and that I have favored you over all people.

 And beware of a Day when no soul will avail another soul in any way, and no ransom will be accepted from it, and no intercession will benefit it, and they will not be helped.

#+REVEAL: split

 And when his Lord tested Abraham with certain words, and he fulfilled them. He said, "I am making you a leader of humanity." He said, "And my descendants?" He said, "My pledge does not include the wrongdoers."

 And We made the House a focal point for the people, and a sanctuary. Use the shrine of Abraham as a place of prayer. And We commissioned Abraham and Ishmael, "Sanctify My House for those who circle around it, and those who seclude themselves in it, and those who kneel and prostrate."

 When Abraham said, "O My Lord, make this a peaceful land, and provide its people with fruits---whoever of them believes in God and the Last Day." He said, "And whoever disbelieves, I will give him a little enjoyment, then I will consign him to the punishment of the Fire; how miserable the destiny!"

 As Abraham raises the foundations of the House, together with Ishmael, “Our Lord, accept it from us, You are the Hearer, the Knower.

 #+begin_notes
2:120-127 
 #+end_notes
**** Baghavadgita
     :PROPERTIES:
     :CUSTOM_ID: baghavadgita
     :END:
Mother Earth, unable to bear the burden of the sins committed by evil kings and rulers, appealed to Brahma, the Creator, for help. Brahma prayed to Supreme Lord Vishnu, who assured Brahma that Vishnu himself would soon be born on earth to annihilate tyrannical forces.

One such evil force was Kansa, the ruler of Mathura (a city in the northern India state of Uttar Pradesh). Kansa's people were utterly terrified of him. On the day that Kansa's sister Devaki was married off to Vasudeva, a voice from the sky was heard prophesying that Devaki's eighth son would be the destroyer of Kansa. The frightened Kansa immediately unsheathed his sword to kill his sister, but Vasudeva intervened. Vasudeva implored Kansa to spare his beloved Devaki, and promised to hand over every one of their newborn children to him. Kansa relented but imprisoned both Devaki and her husband, Vasudeva.


#+REVEAL: split

When Devaki gave birth to her first child, Kansa came to the prison cell and slaughtered the newborn. In the same way, he killed Devaki's next six children. Even before her eighth child was born, Devaki and Vasudeva started lamenting its fate and theirs. Suddenly, Lord Vishnu appeared before them and said that he himself would be born to them and would rescue them and the people of Mathura. Vishnu asked Vasudeva to carry him right after his birth to the house of Vasudeva's friend, the chief cowherd Nanda in Gokula. There, Nanda's wife Yashoda had given birth to a daughter. Vasudeva was to exchange his boy and bring Yashoda's baby daughter back to the prison. Vishnu assured them, "Nothing shall bar your path."

At midnight, the divine baby was born in Kansa's prison. Following Lord Vishnu's instructions, Vasudeva clasped the child to his bosom and started for Gokula, but he found that his legs were in chains. He jerked his legs and was unfettered! The massive, iron-barred doors unlocked and opened by themselves.

#+REVEAL: split

While crossing the River Yamuna, Vasudeva held the baby high over his head. The rain fell in torrents, and the river was flooded. But the water parted for Vasudeva, and miraculously a five-mouthed snake followed him from behind and provided shelter over the baby.

When Vasudeva reached Gokula, he found the door of Nanda's house open. He exchanged the babies and hurried back to Kansa's prison with the baby girl. As Vasudeva entered, the doors of the prison closed and barred themselves behind him.

When Kansa heard about the birth of the baby girl, he rushed inside the prison and tried to kill the infant. But this time the baby slipped from his hands and flew into the air, reaching toward the sky. The baby was transformed into the goddess Yogamaya, who spoke to Kansa: "O foolish one! The one who was born to kill you still lives and is elsewhere!" Then she disappeared.

#+REVEAL: split

Krishna grew to be a very mischievous child, who constantly annoyed his adoptive mother, Devaki, and his nanny with jokes and miraculous tricks. Demons frequently tried to kill him and his adoptive family, but even as a baby he vanquished them all.

As a young adult, Krishna killed the tyrannical ruler Kansa, along with all his cruel associates. Krishna then at long last liberated his parents from prison and reinstated Ugrasen, the true King of Mathura.

     #+begin_notes
    The birth of Krishna 

is a major deity in Hinduism. He is worshipped as the eighth avatar of the god Vishnu and also as the supreme God in his own right.[7]He is considered as the supreme god in the Gaudiya Vaishnavism and by ISKCON devotees.[8]He is the god of compassion, tenderness, and love in Hinduism,[9][10][11] and is one of the most popular and widely revered among Indian divinities

The Bhagavad Gita (/ˌbʌɡəvəd ˈɡiːtɑː, -tə/; Sanskrit: भगवद् गीता, IAST: bhagavad-gītā, lit. "The Song of God"),[1] often referred to as the Gita, is a 700-verse Sanskrit scripture that is part of the Hindu epic Mahabharata (chapters 23–40 of Bhishma Parva).

The Gita is set in a narrative framework of a dialogue between Pandava prince Arjuna and his guide and charioteer Krishna. At the start of the Dharma Yudhha (righteous war) between Pandavas and Kauravas, Arjuna is filled with moral dilemma and despair about the violence and death the war will cause for the war he'll battle against his own kin.[2] He wonders if he should renounce and seeks Krishna's counsel, whose answers and discourse constitute the Bhagavad Gita. Krishna counsels Arjuna to "fulfill his Kshatriya (warrior) duty to uphold the Dharma" through "selfless action".[web 1][3][note 1] The Krishna–Arjuna dialogue cover a broad range of spiritual topics, touching upon ethical dilemmas and philosophical issues that go far beyond the war Arjuna faces
     #+end_notes
**** Rig Veda
     :PROPERTIES:
     :CUSTOM_ID: veda-praise-song
     :END:
The non-existent was not; the existent was not at that time. The atmosphere was not nor the heavens which are beyond. What was concealed? Where? In whose protection? Was it water? An unfathomable abyss?There was neither death nor immortality then. 

There was not distinction of day or night. That alone breathed windless by its own power. Other than that there was not anything else. 

Darkness was hidden by darkness in the beginning. All this was an indistinguishable sea. That which becomes, that which was enveloped by the void, that alone was born through the power of heat. 

Upon that desire arose in the beginning. This was the first discharge of thought. Sages discovered this link of the existent to the nonexistent, having searched in the heart with wisdom. 

#+REVEAL: split

Their line [of vision] was extended across; what was below, what was above? There were impregnators, there were powers: inherent power below, impulses above.

Who knows truly? Who here will declare whence it arose, whence this creation?The gods are subsequent to the creation of this. Who, then, knows whence it has come into being?

Whence this creation has come into being; whether it was made or not; he in the highest heaven is its surveyor. Surely he knows, or perhaps he knows not.

#+begin_notes
Hymn of creation
Translated by Michael Myers
http://www.wsu.edu:8080/~wldciv/world_civ_reader/world_civ_reader_1/rig_veda.html
The Hymn of Creation
This hymn explores the issue of the creation of the universe, which is depicted as a mysterious and perhaps ultimately unknowable process.  There is a familiar reference to a dark watery chaos enlivened by wind.  Particular importance is placed on the role of desire, while the existence of a creator is questioned.
http://www.columbia.edu/itc/religion/f2001/docs/rigveda.pdf

The Rigveda (Sanskrit: ऋग्वेद ṛgveda, from ṛc "praise"[1] and veda "knowledge") is an ancient Indian collection of Vedic Sanskrit hymns. It is one of the four sacred canonical texts (śruti) of Hinduism known as the Vedas.[2][3]

The text is layered consisting of the Samhita, Brahmanas, Aranyakas and Upanishads.[note 1] The Rigveda Samhita is the core text, and is a collection of 10 books (maṇḍalas) with 1,028 hymns (sūktas) in about 10,600 verses (called ṛc, eponymous of the name Rigveda). In the eight books – Books 2 through 9 – that were composed the earliest, the hymns predominantly discuss cosmology and praise deities.[4][5] The younger books (Books 1 and 10) in part also deal with philosophical or speculative questions,[5] virtues such as dāna (charity) in society,[6] questions about the origin of the universe and the nature of god,[7][8] and other metaphysical issues in their hymns.[9]

The Rigveda is the oldest known Vedic Sanskrit text.[10] Its early layers are one of the oldest extant texts in any Indo-European language.[11][note 2] The Philological and linguistic evidence indicates that the bulk of the Rigveda Samhita was composed in the northwestern region (Punjab) of the Indian subcontinent, most likely between c. 1500 and 1200 BC,[13][14][15] although a wider approximation of c. 1700–1100 BC has also been given.[16][17][note 3]

Some of its verses continue to be recited during Hindu rites of passage celebrations (such as weddings) and prayers, making it probably the world's oldest religious text in continued use.[22][23]
#+end_notes
**** Lotus sutra
     :PROPERTIES:
     :CUSTOM_ID: lotus-sutra
     :END:
The Bodhisattva Who Listens to the Sounds of All the World, with his magnifcent spiritual power, confers such abundant benefits as these. And so, living beings should always keep him in their hearts and hold his name in mind. If women seeking sons bow to and make offerings to the Bodhisattva Gwan Shr Yin, they will give birth to sons happy, virtuous, and wise. If instead, they wish for daughters, they will bear gifted daughters with deep-rooted, wholesome characters, beloved and respected by all.

#+begin_notes
	
8077 |  Saddharma Pundarika Sutra (Sk) The Lotus Sutra, Buddhism
Source : Universal Door Chapter of the Lotus Sutra, translated by the Buddhist Text Translation Society.  

https://www.onelittleangel.com/wisdom/quotes/book.asp?mc=1720

The Lotus Sūtra (Sanskrit: Saddharma Puṇḍarīka Sūtra, literally "Sūtra on the White Lotus of the Sublime Dharma"[1]) is one of the most popular and influential Mahayana sutras, and the basis on which the Tiantai, Tendai, Cheontae, and Nichiren schools of Buddhism were established.

According to British professor Paul Williams, "For many East Asian Buddhists since early times, the Lotus Sutra contains the final teaching of the Buddha, complete and sufficient for salvation."[2]
#+end_notes
