#+Author: Dale Hathaway
#+Title: Appearance of the Sacred
#+Date: 2018-01-29 Mon
#+Email: hathawayd@winthrop.edu
#+OPTIONS: org-reveal-title-slide:"%t"
#+OPTIONS: reveal_width:1000 reveal_height:800 
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2
#+REVEAL_HLEVEL: 1
#+OPTIONS: toc:0 num:nil
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
#+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
#+REVEAL_PLUGINS: (markdown notes)
* An example of the sacred

| http://2.bp.blogspot.com/-aKZNli_hyHU/UMB4wJCWKQI/AAAAAAAANGw/0hor-KYYji0/s1600/Oahu_from_air2.jpg |


 https://youtu.be/nrG5Yuwpapc


* Religious language 
 Joseph Campbell:  https://youtu.be/R7xuLN8WIkI


 Most often *poetic* in the sense that, like poetry, it *seeks to use ordinary words to convey extraordinary meanings*. 
| http://baumwollarchives.com/wp-content/uploads/2012/10/101-3-J-CAMPBELL-top3.jpg                                   |

#+BEGIN_NOTES
missing? https://youtu.be/L_Hcoru77Gs?list=PL66bRS2DhVi-6gDUTfbHh_-dsuXZ_BGio     

star wars:  https://youtu.be/GicWZl9HmU4
#+END_NOTES

** Religious Myth: 
- A story that *sets up a world by describing ultimate reality and its relationship to humanity*.
#+ATTR_REVEAL: :frag (appear)
  - Myths seek to explain the ultimate meaning of the universe (cosmos) and our existence, its ultimate origins, destiny, order (or disorder) and relationships.
  - Purpose = revelation of the nature of the sacred, the universe, and human nature.
  - In short, “How does reality makes sense in light of the sacred?" 
***                                                                                                
#+ATTR_REVEAL: :frag (appear)
- Myths seek to *narrate or reveal a transcendent reality* and its relation to ordinary reality.
#+ATTR_REVEAL: :frag (appear)
  - Mythic time transcends ordinary time.
  - Mythic events transcend “empirically observable" events.
#+ATTR_REVEAL: :frag (appear)
- They *do not seek to record simply what happened* in ordinary reality.  They do not aim at empirical or scientific truth (that can be tested via experiments). 

*** 
#+ATTR_REVEAL: :frag (appear)
- Rather myths *represent the collective experience and wisdom of a community over time* concerning the deepest meaning of reality
#+ATTR_REVEAL: :frag (appear)
  - and the ultimate frame of reference for understanding it expressed in the most powerful and fundamental forms of human language—stories conveyed via imaginative, poetic language
  - (exaggeration = frequent vehicle because ordinary language inadequate).
  - A myth is like a pair of glasses or framework through which people “image" or see the world.
#+ATTR_REVEAL: :frag (appear)
- *Note Well*: For one who believes that there is no ultimate meaning to our world, no transcendent reality, or that there is only our immediate experience as known empirically, myth are false or do not exist.


** Examples of contemporary myths: 
#+ATTR_REVEAL: :frag (appear)
- The Matrix,
- Star Wars,
- Western Movies,
- Rags to Riches stories,
- Joe Millionaire (or the one for Mary Millionaire),
- Extreme Makeover,
- Desperate Housewives,
- Car commercials—if you drive this car you will have friends, lovers, wealth, etc. . . .


** Parable:
#+ATTR_REVEAL: :frag (appear)
- A story that *upsets an existing world or turns it upside down*;
#+ATTR_REVEAL: :frag (appear)
  - makes a point by violating our expectations and calling into questions our assumptions.
  - It seeks to shock the hearer into seeing ordinary things in a new way, i.e., in light of the sacred reality which is totally “other" than the ordinary and customary.
  - A parable seeks to move people into a deeper engagement with sacred reality.
#+ATTR_REVEAL: :frag (appear)
- *Sacred figures often perform “parabolic actions"* or actions that upset the way things are and open our eyes to a new reality.

** Examples of Parables/Parabolic Actions
#+ATTR_REVEAL: :frag (appear)
- Zen koan: "What is the sound of one hand clapping?"
- A seeker to the Buddha "Are you a god or a magician?"
- Buddha: "I am not a god or a magician.  I am awake."
- Awake seems ordinary but it is not.  Greatness can't lie in it.

*** 

- Jesus seeks to open people's eyes to the kingdom of God when he reads from /Isaiah 61:1-2/ in Luke 
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_QUOTE
"The Spirit of the Lord Yahweh is upon me, for he has anointed me to bring glad tidings to the poor.  He has sent me to proclaim liberty to captives and recovery of sight to the blind, to let the oppressed go free, and to proclaim a year of favor from Yahweh [a jubilee year]" . . . and a day of vengeance for our God . .  /Luke 4:18-19/
#+END_QUOTE
#+ATTR_REVEAL: :frag (appear)
- *Good Samaritan* = like the good Al Qaeda terrorist. Our social status does not determine our holiness; but our compassion—even a compassion that violates social customs re: ritual purity.  That is what God wants. 
*** 

- *Matthew 25*: Whenever you did it to the least of my brothers and sisters you did it to me—Christ is encountered in the needy.  

#+ATTR_REVEAL: :frag (appear)
- *Prodigal Son* (Who is lost, the younger or the older son?) or Workers in the Vineyard—those who worked a little get paid the same as those who worked a lot; or Unforgiving debtor. (Luke 15-16)

* Sacred Stories

** 4 functions of Sacred Stories (including scriptures): 

#+ATTR_REVEAL: :frag (appear)
- connect with sacred,
- order cosmos,
- *traditio*, and
- ethical
** 4 functions (64)
#+ATTR_REVEAL: :frag (appear)
- *Connect us to the sacred*:
#+ATTR_REVEAL: :frag (appear)
  - reveal the sacred and provide a vehicle for (or mediate) encounter with the sacred through the imaginative experience and ritual re-enacting of the story;
  - reveal a path to the sacred (e.g. Buddha's journey to enlightenment);
  - provide insight/wisdom re: ultimate truth. 
#+ATTR_REVEAL: :frag (appear)
- *Order the cosmos*:
#+ATTR_REVEAL: :frag (appear)
  - give an account of the nature, purpose, order, and destiny of the universe,
  - explain how things are related, where things belong, what they mean, how it all fits together ultimately;
  - relate the transcendent reality to the ordinary reality.  

*** 
#+ATTR_REVEAL: :frag (appear)
- *Traditio*:
#+ATTR_REVEAL: :frag (appear)
  - "hand over" a way of life, worldview, set of practices, values, and stories that constitute a community over time from one generation to the next.
  - Remember truth handed on from the past and bring it to life in the present by helping people to apply it and live it out today.
  - Continue a way of life and teach it to the next generation.
  - Tradition—an extended conversation about the meaning of life of a community over time.
#+ATTR_REVEAL: :frag (appear)
- *Convey an Ethic*:
#+ATTR_REVEAL: :frag (appear)
  - present patterns, models (saints, prophets), and standards of behavior for living in harmony with the sacred order.
  - E.g. Sunna = the beaten path of the prophet Mohammed.

    
* Canon:
A *measuring reed or stick, ruler, standard*; list of authoritative texts/scriptures in a tradition
** Scriptures:
- Literally "*writings*" (scripture -- "that which is written"), writings considered sacred and authoritative in a particular community.
- Example: The "*sutra*" (or Pali "sutta"), i.e., a short exposition on a particular teaching of the Buddha, is the basic form of the scriptures in Theravada and Mahayana Buddhism 
 
** Theology:
- Understanding of *reflection on God/sacred/faith*; 
- "*faith seeking understanding*"
- Systematic explanation of the meaning of sacred stories and their conceptual relations as well as translation of this meaning in contemporary language.  *Transform story into doctrine that speaks to today's world*.


