#+Author: Dale Hathaway
#+Title: Religious Language
#+Date: 2018-02-05 Mon
#+Email: hathawayd@winthrop.edu
#+OPTIONS: org-reveal-title-slide:"%t"
#+OPTIONS: reveal_width:1000 reveal_height:800 
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2
#+REVEAL_HLEVEL: 1
#+OPTIONS: toc:1 num:nil
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
#+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
#+REVEAL_PLUGINS: (markdown notes)

* Religious language 

** Religious Myth: 
- A story that *sets up a world by describing ultimate reality and its relationship to humanity*.
  - Myths seek to explain the ultimate meaning of the universe (cosmos) and our existence, its ultimate origins, destiny, order (or disorder) and relationships.
  - Purpose = revelation of the nature of the sacred, the universe, and human nature.
  - In short, “How does reality makes sense in light of the sacred?" 
** Religious stories
- "Religion is /my/ story being shaped by another (religious) story."
- religious stories not told to hold onto a historical truth but to *disclose a notion of the sacred to people.*

*** Functions

- Functions include:
  - passes on the traditions of a people
  - recall/retell "paradigmatic moments and/or persons"
  - vehicle for *revelation*
** Parable:
#+ATTR_REVEAL: :frag (appear)
- A story that *upsets an existing world or turns it upside down*;
#+ATTR_REVEAL: :frag (appear)
  - makes a point by violating our expectations and calling into questions our assumptions.
  - It seeks to shock the hearer into seeing ordinary things in a new way, i.e., in light of the sacred reality which is totally “other" than the ordinary and customary.
  - A parable seeks to move people into a deeper engagement with sacred reality.
#+ATTR_REVEAL: :frag (appear)
- *Sacred figures often perform “parabolic actions"* or actions that upset the way things are and open our eyes to a new reality.

#+BEGIN_NOTES
Parables are short stories that are told in order to get a point across and occur in both testaments of the Bible. The word "parable" (Gk. parabole) was generally used in reference to any short narrative that had symbolic meaning (Louw & Nida 1989, p. 391). There are many stories and saying of Jesus in the New Testament that are identified as parables, but not all of these are parables in the true sense. *The Good Samaritan (Luke 10:30-35) may be regarded as a true parable* because it is a complete story with a beginning, ending and plot, but the Leaven in the Meal is a similitude, "You are the salt of the earth" is a metaphor and "Do people pick grapes from thorn bushes" is an epigram (Fee & Stuart 1993, p. 136-137). When "parable" is used in this section it refers to the true parables.

A true parable then may be regarded as an extended simile (Blomberg 1990, p. 32). It is a story that resembles real-life natural situations and does not contain any mythical or supernatural elements (Kuske 1995, p. 97). *These stories were told in order to catch the listener's attention and provoke a response*. C. H. Dodd (1961, p.16) defines a parable as: "a metaphor or simile drawn from nature or common life, arresting the hearer by its vividness or strangeness, and leaving the mind in sufficient doubt about its precise application to tease it into active thought." They often embody a message that may not be communicated in any other way (Marshall & Tasker, in New Bible Dictionary:Parables).

*An allegory, however, is quite different. It is essentially an extended metaphor (Kuske 1995, p. 94*) and uses a story or event (often mythical and supernatural) to illustrate a point (Marshall & Tasker, in New Bible Dictionary:Parables). *They are stories with 2 levels of meaning: human activity and spiritual reality (Blomberg 1990, p. 15*). Allegories encode relatively static series of comparisons that the author wishes to communicate and always need to be interpreted (Blomberg 1990, p. 35).

Allegories are much less common in the New Testament but are more frequent in the Old Testament. *In an allegory virtually every person, thing, place and event has a symbolic meaning (Fee & Stuart 1993, p. 140*). Examples of allegories are the visions in Daniel 8:1-11 (which is interpreted in Daniel 8:20-26), and Ezekiel 1. In the New Testament, nearly every chapter of Revelation contains allegorical visions. http://hermeneutics.kulikovskyonline.net/hermeneutics/parab.htm (this a strict, even radical, creationist who argues that the truth of scripture extends to natural world issues (science)
#+END_NOTES

** Allegory
- ... are stories in which the various characters and incidents actually represent figures and events not a part of the story as such.
- cp. George Orwell's /Animcal Farm/

** Examples of Parables/Parabolic Actions
#+ATTR_REVEAL: :frag (appear)
- Zen koan: "What is the sound of one hand clapping?"
- A seeker to the Buddha "Are you a god or a magician?"
- Buddha: "I am not a god or a magician.  I am awake."
- Awake seems ordinary but it is not.  Greatness can't lie in it.

*** #1

- Jesus seeks to open people's eyes to the kingdom of God when he reads from /Isaiah 61:1-2/ in Luke 
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_QUOTE
"The Spirit of the Lord Yahweh is upon me, for he has anointed me to bring glad tidings to the poor.  He has sent me to proclaim liberty to captives and recovery of sight to the blind, to let the oppressed go free, and to proclaim a year of favor from Yahweh [a jubilee year]" . . . and a day of vengeance for our God . .  /Luke 4:18-19/
#+END_QUOTE
#+ATTR_REVEAL: :frag (appear)
- *Good Samaritan* = like the good Al Qaeda terrorist. Our social status does not determine our holiness; but our compassion—even a compassion that violates social customs re: ritual purity.  That is what God wants. 
*** #2

- *Matthew 25*: Whenever you did it to the least of my brothers and sisters you did it to me—Christ is encountered in the needy.  

#+ATTR_REVEAL: :frag (appear)
- *Prodigal Son* (Who is lost, the younger or the older son?) or Workers in the Vineyard—those who worked a little get paid the same as those who worked a lot; or Unforgiving debtor. (Luke 15-16)

* Sacred Stories

** 4 functions of Sacred Stories (including scriptures): 

#+ATTR_REVEAL: :frag (appear)
- connect with sacred,
- order cosmos,
- pass on the *traditio*, and
- instill ethical expectations and norms

#+BEGIN_NOTES
Perhaps leave this overview without going into detail of the functions
#+END_NOTES

** 4 functions (64)
#+ATTR_REVEAL: :frag (appear)
- *Connect us to the sacred*:
#+ATTR_REVEAL: :frag (appear)
  - reveal the sacred and provide a vehicle for (or mediate) encounter with the sacred through the imaginative experience and ritual re-enacting of the story;
  - reveal a path to the sacred (e.g. Buddha's journey to enlightenment);
  - provide insight/wisdom re: ultimate truth. 
#+ATTR_REVEAL: :frag (appear)
- *Order the cosmos*:
#+ATTR_REVEAL: :frag (appear)
  - give an account of the nature, purpose, order, and destiny of the universe,
  - explain how things are related, where things belong, what they mean, how it all fits together ultimately;
  - relate the transcendent reality to the ordinary reality.  

*** (cont) 
#+ATTR_REVEAL: :frag (appear)
- *Traditio*:
#+ATTR_REVEAL: :frag (appear)
  - "hand over" a way of life, worldview, set of practices, values, and stories that constitute a community over time from one generation to the next.
  - Remember truth handed on from the past and bring it to life in the present by helping people to apply it and live it out today.
  - Continue a way of life and teach it to the next generation.
  - Tradition—an extended conversation about the meaning of life of a community over time.
#+ATTR_REVEAL: :frag (appear)
- *Convey an Ethic*:
#+ATTR_REVEAL: :frag (appear)
  - present patterns, models (saints, prophets), and standards of behavior for living in harmony with the sacred order.
  - E.g. Sunna = the beaten path of the prophet Mohammed.

* Other Religious Language
- Oral & Written cultures :: religious stories and traditions transmitted through different media
- Scripture  :: Literally "*writings*" (scripture -- "that which is written"), writings considered sacred and authoritative in a particular community.

- Canon :: A *measuring reed or stick, ruler, standard*; list of authoritative texts/scriptures in a tradition

** 

- Theology :: Understanding of *reflection on God/sacred/faith*; 
  - "*faith seeking understanding*"
  - Systematic explanation of the meaning of sacred stories and their conceptual relations as well as translation of this meaning in contemporary language.  *Transform story into doctrine that speaks to today's world*.



#+BEGIN_NOTES
- Example: The "*sutra*" (or Pali "sutta"), i.e., a short exposition on a particular teaching of the Buddha, is the basic form of the scriptures in Theravada and Mahayana Buddhism 

#+END_NOTES
 


