#+Author: Dale Hathaway
#+Title: The Nature of the Sacred
#+Date: Jan. 27, 2020
#+Email: hathawayd@winthrop.edu
#+OPTIONS: org-reveal-title-slide:"%t"
#+OPTIONS: reveal_width:1000 reveal_height:800 
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2
#+REVEAL_HLEVEL: 1
#+OPTIONS: toc:1 num:nil
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
#+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
#+REVEAL_PLUGINS: (markdown notes)
#+REVEAL_THEME: beige
#+REVEAL_ROOT: ../../reveal.js
* What is Sacred
** Complex character of the Sacred?
#+ATTR_REVEAL: :frag (appear)
- wide range of phenomena
- sacred | profane -- "other than ordinary"
- sacred as *extraordinary*
- important that *sacred* is not tied to a particular religious tradition

#+begin_notes
- Many have the experience or can imagine the difference between sacred and not-sacred. I think of my experience one Christmas midnight. We walked out of Grace Cathedral in  San Francisco after midnight mass. We got in our car and drove 2 blocks and there was a bustling street advertising "Live Sex" shows. The contrast was stark.
- Biblical Hebrew for “Sacred” indicates a reality that is somehow distinct, “set apart,” “other” than ordinary.
--------------
- “Sacred” is a complex word because it is used for a wide range of phenomena: places, time, persons, events, and deities.
- But, generally, when people speak of something as sacred, they mean to designate the thing in question as “other than ordinary.” 
- In the broadest sense of the term, the sacred is the “extraordinary.” 
- The value of using the term “sacred” is that it is not tradition specific.

#+end_notes
** The Sacred and The Holy
#+ATTR_REVEAL: :frag (appear)
- Often the words “sacred” and “holy” are used as equivalents.  
- Thus, the best way to identify the sacred is to identify that which is designated holy.
#+ATTR_REVEAL: :frag (appear)
    - The early Israelites were instructed: “Observe the sabbath day and keep it holy.”
    - A popular Christian hymn begins “Holy, holy, holy, Lord God almighty!” 
    - Islamic tradition refers to Jerusalem as /al-quds—the holy city, or the city set apart/.

#+begin_notes
The *Sabbath* as holy. Keeping a "hedge" about it. What is *holy* in your life? How do you show that it's holy?

Is the *flag* "holy"
#+end_notes
* Examples
** Sacred in Bible
#+BEGIN_QUOTE
O God, you are my God, I seek you, my soul thirsts for you; my flesh faints for you, as in a dry and weary land where there is no water. So I have looked upon you in the sanctuary, beholding your power and glory. Because your steadfast love is better than life,my lips will praise You. (Psalm 63:1–3)
#+END_QUOTE
** Sacred in Hinduism 
#+BEGIN_QUOTE
Thou [God] art the Imperishable, the supreme Object of Knowledge, Thou art the ultimate resting-place of this universe; Thou art the immortal guardian of the eternal right; Thou art the everlasting Spirit. . . . Without beginning, middle, or end, of infinite power, Of infinite arms, whose eyes are the moon and sun, I see Thee, whose face is flaming fire, Burning this whole universe with Thy radiance. (11:18–20)  (*Bhagavad Gita*)
#+END_QUOTE


** Sacred in Buddhism 
#+BEGIN_QUOTE
“Its form, O king, cannot be elucidated by similes, but its qualities can. . . . As the lotus is unstained by water, so is Nirvana unstained by all the defilements. . . . As cool water allays feverish heat, so also Nirvana is cool and allays the fever of all the passions. . . . As medicine protects from the torments of poison, so Nirvana protects from the torments of the poisonous passions. . . . Nirvana and medicine both give security. . . . As a mountain peak is unshakeable, so is Nirvana. . . . ”  *Buddhism*: "The Nature of Nirvana"
#+END_QUOTE


* The Concept in various cultures
** The Concept of Sacred Reality
#+ATTR_REVEAL: :frag (appear)
  - Derived from the Latin “sanctus”.
  - “Sanctus” means “holy” and refers to something separated or set apart from other things.
  - The related terms from the Hebrew (/kadosh  קדוש ) and the Greek (/hagios, 'αγιος/) mean the same.
  - At minimum, the sacred is distinct from the profane.
** Sacred Reality in Various Cultures
 - Biblical witness is that *God* is only truly *holy* -- all else is holy because it is connected to God

 - Ancient Rome *sanctus* applied to the temples where rituals were dedicated to gods. /Fanum/ was the name of the temple. Ritual was performed "before" the /fanum/ -- and were thus *pro* (before) the *fanum*.

   #+begin_notes
   - In the Bible, *God is preeminently sacred or holy, and everyone else and everything else is holy or sacred only in relation to God. 
  - In ancient Rome, sanctus applied as much to the place of certain activities as to the activities themselves. 
    - Those acts that were sanctified were performed in the /fanum or temple; other acts were pro fanum/, that is, performed in front of or outside the temple.
 
   #+end_notes
** Sacred Reality in the Hebrew Bible

- in Hebrew Bible /kadosh/ is used of those things God has chosen:
  - the people of Israel
  - the land of the people
  - certain foods (*kosher*)
  - certain human relations
- nothing is special except in relation to God

   #+begin_notes
   
  - By contrast, the Hebrew Bible uses /kadosh/ to describe God and things set apart by God’s choice: the people of Israel, the land they live in, types of food, modes of human relations.
  - There is nothing special about such things except that they are chosen by God or are in some kind of relation to God.


   #+end_notes
* Sacred and Profane
** The Sacred and The Ordinary
 - *sacred* can be described as *really, real* -- everything else somehow pales

 - *sacred* provides authority and truth where everywhere else is relativity and subjective experience

 - *sacred* is other than *ordinary* but is made *manifest through ordinary existence.*

    - examples of the *holy* can include stones, trees, sky, bodies of water, various people
   #+begin_notes
   
  - The sacred can further be characterized in terms of “the real.”
  - The sacred stands for that which provides absolute and objective authority to an otherwise relative and subjective existence. 
  - The sacred consists of an entirely different order than the ordinary life of human beings, but is manifest through ordinary existence.
  - Stones, trees, the sky, bodies of water, various people—all these may be the vehicles of the sacred and thus share in its distinctive reality.
 
   #+end_notes
** General Concept of the Sacred
#+ATTR_REVEAL: :frag (appear)
  - Sacred reality is present wherever something is *real* by 4 criteria:
#+ATTR_REVEAL: :frag (appear)
    - it is "set apart" from everything else in the world
    - it is in some sense beyond human control
    - it is in some sense vital for the well-being of humans
    - it orders human existence

