#+Author: Dale Hathaway
#+Title:Religion & Morality
#+Date: 2018-04-18 Wed
#+Email: hathawayd@winthrop.edu
#+OPTIONS: org-reveal-title-slide:"%t"
#+OPTIONS: reveal_width:1000 reveal_height:800 
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2
#+REVEAL_HLEVEL: 1
#+OPTIONS: toc:1 num:nil
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
#+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
#+REVEAL_PLUGINS: (markdown notes)

* Definitions
** The Foundation for Morality
   :PROPERTIES:
   :CUSTOM_ID: the-foundation-for-morality
   :END:

-  Many people claim that religion is the *foundation for all morality*.
-  In this way, it is religion that teaches people what is good or right or praiseworthy.
-  For some religious traditions, the phrase "obey the commands of God" expresses the highest standard of the moral life.
-  But this claim raises the key questions (first posed by Socrates): "*Do the gods love the good because it is good, or is it good because the gods love it?*"



** Defining Morality

| Religion                                                                        | Morality                                                                                                                |
|---------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------|
| "Religion" refers to ways of thinking that refer to a notion of sacred reality. | "Morality" may be taken to refer to ways of thinking, feeling, and acting that address considerations of human welfare. |


#+BEGIN_NOTES
Note:

==================================================

As some scholars put it, religious considerations lead one to think in
"sacred-regarding" terms, moral considerations in "other-regarding"
terms.

#+END_NOTES

** Priority of Religion or Morality?
   :PROPERTIES:
   :CUSTOM_ID: priority-of-religion-or-morality
   :END:

-  Religion and morality are interconnected, but *religion and morality can also conflict*.
-  If such conflicts occur, which is to have priority?



** Abraham
:PROPERTIES:
:reveal_background: https://upload.wikimedia.org/wikipedia/commons/7/7b/Abraham.jpg
:reveal_background_size: 1100px
:reveal_background_trans: slide
:END:

#+BEGIN_NOTES

Note:

*Consider the moral problems raised by the biblical story of Abraham.
Common to all 3 Religions of Abraham*

Note: In the story, God commands Abraham to sacrifice his son, Isaac, as
a way of testing Abraham's faith.
#+END_NOTES


** Soren Kiekegaard
   :PROPERTIES:
   :CUSTOM_ID: soren-kiekegaard
   :END:

-  Kierkegaard analyzed the story of Abraham as a *paradox between Abraham's two "loves" -- his son and God*.
-  Abraham was (evidently) willing to sacrifice his son at God's command, which indicates that his love of God took priority.
-  Thus, Abraham was a true "*knight of faith*."
-  Abraham's love for God is an example of the *religious point of view taking priority over the moral*.



** Immanuel Kant
   :PROPERTIES:
   :CUSTOM_ID: immanuel-kant
   :END:

-  Kant takes the opposite position of Kierkegaard.
-  Kant argued that if anyone thinks he or she hears a command like that of Abraham's, it is *obligatory to ignore or renounce that directive*.
-  Thus, the positions of Kant and Kierkegaard present two sides of the questions about which should take priority, religion or morality, in cases of conflict.
-  [[http://www.csus.edu/indiv/g/gaskilld/ethics/kantian%20ethics.htm][Overview of Categorical Imperative]] 1st formulation of which is: "*Act only in such a way that one can at the same time will that it should become a universal law*."

#+BEGIN_NOTES
Note: 

This could be an exercise:
Consider the discussion question from SQ (130)                                                                                                                                                       
 The Muslim theologian al-Ash'ari (d. 935 CE) argued that the only sure basis for moral knowledge was the command of God made known in revealed texts such as the Qur'an. He argued that God was the Supreme Lord of the worlds, whose commands were always to be obeyed; and he went on to say that if God commanded human beings to lie, then lying would be obligatory. Does this seem right to you? Why or why not? What view of the religion--morality relation is suggested by al-Ash'ari's comment?   
#+END_NOTES
* Ethics

- What does it mean to live well?
- Is a given course of action right or wrong?
- What standards should be used in evaluating particular acts or the persons who engage in them?
- [[http://www.cnn.com/2017/04/13/politics/syria-religious-justified/index.html][Discussion of moral justification for bombing Syria]]

#+BEGIN_NOTES
Note:

-  The discussion of the relations between religion and morality is a
   part of the general study of ethics or the inquiry into the nature of
   the good life.
-  The study of ethics focuses on such questions and involves an attempt
   to develop theories of the nature and foundation of human judgment.

#+END_NOTES

** Justification

 - *justification* -- or reasons for action
 - *practical justification* = advancing reasons in support of a particular action
 - *religious reasons* may or may not be advanced 

 #+BEGIN_NOTES
 Note:

 -  Underlying all of these issues is the problem of practical justification, or the question of reasons for action.
 -  Practical justification involves the process of *advancing reasons in support of a particular action*.
 -  Religious reasons may or may not be advanced as a part of the practical justification.
 -  Consider, for example, the practical justifications that might be advanced on each side of the abortion debate.


 Justification - In any given case of action or judgment about
 the rightness of action, then, it is possible to ask for reasons. - The
 attempt to provide reasons for actions and judgments involves persons
 and groups in the process of practical justification. - The example of
 the arguments surrounding abortion presents one illustration of such a
 process.
 #+END_NOTES


** Deontological Approach to Opposing legal and safe abortions
- δεοn  = "necessary, or duty"
-  An appeal to *duty*.
- one ought to do something *regardless of the consequences*

#+BEGIN_NOTES
Note:

- consider the 10 commandments:

-  The issue is one of formal adherence to a given standard of action,
   *regardless of the good or bad consequences* that follow.
-  Examples:

   -  Abortion is wrong because it violates the rule "Thou shalt not
      kill."

 Abortion is wrong because it violates the command of God.

 On the other hand

 Deontological approach to Favoring legal and safe abortions

-  a person has an inherent right to control over his/her own body
-  another person does not have a right to make decisions for another over control of his/her own body
-  even as one grants full status as a "human person" to the unborn fetus, the mother also has a full status as a "human person", i.e. "*no one human being may be reduced to the status of a mere instrument in order to serve the needs of another human being*"


"A defense of abortion" by Judith Jarvis Thomson
#+END_NOTES

** 10 c's
:PROPERTIES:
:reveal_background: https://jamesbishopblog.files.wordpress.com/2016/04/10.jpg
:reveal_background_size: 1100px
:reveal_background_trans: slide
:END:

** Conditional Commandments Deuteronomy
Deuteronomy 8:1
#+BEGIN_QUOTE
Be careful to follow every command I am giving you today, so that you may live and increase and may enter and possess the land the LORD promised on oath to your ancestors.
#+END_QUOTE
** Teleological Approach to Opposing legal and safe abortions
- τελος = "end" or "goal"
-  An appeal to *consequences*.


#+BEGIN_NOTES
Note:

-  Examples:

   -  If we say that some abortions are justified, we will open the door to many wrongful killings.
   -  If we permit abortion, it will make us less sensitive to the killing of innocents in other areas of action---abortion leads to euthanasia, which leads to doing away with 'surplus people,' which leads to the Holocaust.



On the other hand

 Teleogical issues to Favoring legal and safe abortions

Granting the sanctity of life, the following consequences are not
negligible:

-  pregnancy resulting from rape
-  pregnancy that threatens the life of the mother
-  an unwanted pregnancy may result in a serious detriment to the child's future well-being
#+END_NOTES


** Motivations

-  The problem of justification must also deal with motivations.
-  The ideal of many religious traditions is that one should do the right because it is right.
-  Yet many religious traditions promise that there will, at some time in the future, be *rewards for good conduct and punishments for wrongdoing*.
-  We must therefore ask what the role of appeals to rewards and punishments is in various instances of practical justification.



** Justifying and Exciting Reasons

-  Justifying reasons
   -  Arguments about the rightness or wrongness of particular actions or judgments.
-  Exciting reasons
   -  Promises of rewards and threats of punishments, the purpose being to motivate persons to do what is right.



** Rule-Deontological Approach

-  A rule-deontological approach measures acts in terms of appeals to
   duty.
-  Also indicates that duty can be known through guidelines that have a
   general form:

   -  Do not kill
   -  Do no harm
   -  Love your neighbor



** Rule-Teleological Approach

Makes reference to similar sorts of action guides but understands them
to be general statements concerning those types of behavior that, over
the long course of personal or social experience, make for good
consequences.



** Acts vs. Rules

-  Both act-deontological and act-teleological approaches to justification emphasize the importance of individual acts or situations in which judgments must be made.
-  For these approaches, there are no generally valid guidelines by which human beings may know their duty or that can be said to yield good results.

   -  Rules, principles, or other norms are just "rules of thumb"
   -  They provide assistance but have little or no authority in justifying particular judgments



** Schema
|-----------------------+------------|
| *Kind of Justification* | *Variations* |
|-----------------------+------------|
| Deontological         | Rule       |
|                       | Act        |
|-----------------------+------------|
| Teleological          | Rule       |
|                       | Act        |
|-----------------------+------------|
* Case Studies

-  Hindu
-  Islamic
-  Christian



** Hindu Caste System

-  Caste is a way of institutionalizing certain forms of labor necessary to social life.
-  The four major castes represent the priestly, warrior, merchant, and laboring classes.
-  A fifth group, the "outcastes," is in effect outside the system and does the tasks that are beneath the other classes.
-  The caste system thus represents an institution that serves to order society and that can be justified in religious terms.



** Hindu Caste System

-  But the religious ideals of Hinduism and the ordinary morality of Indian society are in conflict.
-  At the heart of Hinduism is the principle of renunciation.
-  One who renounces becomes a wandering ascetic, no longer fulfilling the vocation of his caste but rather living off the largesse of others.
-  But Indian society demands, as a matter of right action, fulfillment of the vocation of the caste.



** Religion  and War

- In Islam, discussion of the religious and moral dimensions of war appears very early, in connection with the life and work of Muhammad
- Early Christianity was largely pacifist -- with the establishment of Christendom it became necessary to establish rules for "Just War" -- St. Augustine was the first major Christian figure to formulate such a theory




* For Discussion
** Thought Experiment (130)

The pacifist scholar Roland Bainton argued in his study of /Christian
ATttitudes Toward War and Peace/ that holy wars -- wars fought for
religious reasons -- tend to become crusades -- wars in which the enemy
is counted as demonic and worthy of total extermination. As you think of
wars in the 20th c. and 21st c. Is this true?



** Christianity and Prayer

-  Prayer can be seen as an obligation or duty of Christians.
-  Prayer is, therefore, justified by the command of God.
-  But, prayer might also be seen as an activity that is justified by the command of God.
-  Thus, prayer is justified in deontological terms and it is also an act justified by certain ends.



** Religion and Morality: Patterns

-  In the case of Hinduism and the caste system, there is evidence of *religion and morality in tension*.
-  Because the ideal of renunciation indicates the priority of sacred-regarding over other-regarding concerns, religion and morality appear to be in competition.
-  The same tension is evident in the biblical *story of Abraham*.



** Religion and Morality: Patterns

- In the case of Islam, one finds *evidence of religion complementing and filling out morality*.
- Ordinary moral concern suggests that war is an act in need of justification.
- Religion in service to secular demands?



** Religion and Morality: Patterns

-  Christian discussion of the question "why pray?" provides evidence of religion animating the moral life, that is, providing reinforcement to the will to do what is good.
-  One could cite other examples of religion animating the moral life in the teaching of Christianity, Judaism, and Islam on martyrdom, and again, in Buddhist emphasis on meditation, or in the Confucian approach to ritual.

