#+Author: Dale Hathaway
#+Title: Wiesel's Night (2)
#+Date: Oct. 25, 2017
#+Email: hathawayd@winthrop.edu
#+OPTIONS: org-reveal-title-slide:"%t"
#+OPTIONS: reveal_width:1000 reveal_height:800 
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2
#+REVEAL_HLEVEL: 1
#+OPTIONS: toc:0 num:nil
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
#+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
#+REVEAL_PLUGINS: (markdown notes)

* Night an introduction
* Places of Night

| Sighet (See-get)   | Buna        |
| Birkenau           | Auschwitz   |
| Buchenwald         | Gleiwitz    |

** Organization


- gradual loss of the illusion of hope
- loss of faith in the God of his childhood
- gradual loss of his relationship with his father

#+BEGIN_NOTES
Note: The book's nine chapters demarcate key events for Wiesel,
detailing the gradual loss of the illusion of hope as the grim realities
become paramount. Two interrelated concerns are woven throughout the
narrative: Wiesel's agonizing loss of faith in the God of his childhood
and his excruciating relationship with his weakening father. The latter
is marked by filial love and concern, but also by his own devastating
guilt as his father slips inexorably toward death and Wiesel anticipates
freedom from his burden of devotion.

--------------

#+END_NOTES

** Never shall I forget

#+BEGIN_QUOTE
  ... Never shall I forget that night, the first night in camp, which
  has turned my life into one long night, seven times cursed and seven
  times sealed. Never shall I forget that smoke. Never shall I forget
  the little faces of the children. . . . Never shall I forget those
  flames which consumed my faith forever ...
#+END_QUOTE

** 

#+BEGIN_QUOTE
  ... Never shall I forget those moments which murdered my God and my
  soul and turned my dreams to dust. Never shall I forget these things,
  even if I am condemned to live as long as God Himself. Never.
#+END_QUOTE

#+BEGIN_NOTES
Note: Night reveals the destruction of all aspects of the accepted
universe---the shtetl (the Jewish enclave) of Sighet, family life, the
training of a deeply religious child, and the illusion of a caring
humanity. Yet above all, it sets forth a sequence of experiences that
results in Wiesel's becoming “the accuser, God the accused.” A universe
is revealed in Night in which “anything is allowed.” After seeing a
truck dump babies into a burning pit, Wiesel cries,

--------------

#+END_NOTES

** God is on the gallows
   :PROPERTIES:
   :CUSTOM_ID: god-is-on-the-gallows
   :END:

Following the execution of a child possessing “the face of a sad angel,”
a voice asserts that God “is hanging here on this gallows.”

/Wiesel is deliberately ambiguous about the source of this assertion./

#+BEGIN_NOTES
Note: The nine chapters in Night are devoted to specific aspects of
Wiesel's Holocaust experience: the warnings and illusion-filled prelude
before deportation, the terrifying train ride to Auschwitz, the arrival
at the gates of the SS hell, the loss of family members, and the early
signs of a shattering faith. Wiesel recalls the slave labor at the Buna
works adjacent to the central Auschwitz complex, the promise of the
approaching Russian army's liberation destroyed by the SS evacuation of
camp inmates, the march away from Auschwitz toward Germany, the train
ride to Buchenwald, the death of his father, and his own liberation. The
book's tone varies from irony to bitterness to terrible despair, with
the latter perhaps being dominant. As its Yiddish title suggests
(literally, “and the world remained silent”), Wiesel's book is addressed
to the world that did nothing, but it also challenges a God who did
nothing.

Wiesel is acutely conscious of the duty of the survivor and writer
following the Holocaust to educate that apathetic world and to provide a
voice for the six million murdered Jewish victims. In an interview
published in the Journal of Education (1980), he noted, “I do not write
to please the reader. . . . I write for the dead.” Wiesel himself calls
Night the literature of testimony.

--------------

#+END_NOTES

* “Holocaust”
** Shoah: a long history

-  The mass murder of European Jews and others under Nazi rule during
   World War II has come to be known simply as the *Holocaust*.(/see
   below/)
-  Timeline of a long history of anti-semitism:

   -  https://en.wikipedia.org/wiki/Timeline\_of\_antisemitism
   -  http://www.simpletoremember.com/articles/a/HistoryJewishPersecution/
   -  http://www.zionism-israel.com/his/Anti-semitism\_timeline.htm

#+BEGIN_QUOTE
  /As noted in an earlier discussion, an alternate name/ *Shoah* /is often
  used to distinguish from a word that could be used of sacrifice to God/
#+END_QUOTE
#+BEGIN_NOTES
Note: "Holocaust" literally means "massive destruction by fire." It is
thought that as many as eleven million people were killed by the Nazis.

/Christianity vs. Judaism has a long history/: timeline:
[[https://www.preceden.com/timelines/253106-religions]]

These included political opponents (particularly Communists), Slavs,
gypsies, mentally and/or physically disabled, homosexuals, and other
"undesirables." An estimated six million men, women, and children were
killed merely because they were Jews. The destruction of the Jews in
Europe stands as the archetype of genocide in human history.

--------------

#+END_NOTES

** Jews and anti-semitism

- Jews had long been victims of persecution
- Hitler rose to prominence as a charismatic demagogue in 1920's
- He lost an election for president in 1932
- in 1933 he became chancellor and set in motion the
  destruction of democracy in Germany

#+BEGIN_NOTES
Note: Jews had been the subjects of persecution in Europe at least since
the seventeenth century. When Adolph Hitler, the charismatic,
Austrian-born demagogue, rose to power in Germany during the 1920s and
early 1930s, he rallied the German people with a message that included
notions of "Aryan," or white, superiority and the inferiority of other
races. The Jews were a special target of his hatred, and they were
incorrectly represented during this time of social, political, and
economic upheaval as being wealthy and in control of the country's
economy. In 1932, Hitler ran for president of Germany. He did not win,
but he did well, and when the party in power was unable to end the
depression, its leaders turned to Hitler for help. He became chancellor,
or prime minister, of Germany in 1933. Within weeks, he set into motion
a series of laws that destroyed the nation's democratic government. He
eliminated all opposition and launched a program of world domination and
extermination of the Jews. His government, like all totalitarian
regimes, established complete political, social, and cultural control
over its subjects.

--------------

#+END_NOTES

** Gradual progression

- In Hitler's program for the "Aryanization" of Germany and world conquest, Jews were subjected first to discrimination, then persecution, and then state-condoned terrorism.
- the "night of the broken glass" also known as *Kristallnacht*, which took place in Munich, Germany, in November 1938
- By the outbreak of war in September 1939, half of Germany's five hundred thousand Jews had fled, as had many Jews from other German-occupied areas.

#+BEGIN_NOTES
Note: In Hitler's program for the "Aryanization" of Germany and world
conquest, Jews were subjected first to discrimination, then persecution,
and then state-condoned terrorism. This had as a turning point, the
"night of the broken glass" also known as Kristallnacht, which took
place in Munich, Germany, in November 1938. Nazi storm troopers burned
down synagogues and broke into Jewish homes, terrorizing men, women, and
children. Over twenty thousand people were arrested and taken to
concentration camps. After Kristallnacht, Jewish businesses were
expropriated, employers were urged to fire Jewish employees, and offices
were set up to expedite emigration. Jews could buy their freedom and
leave the country, but they had to abandon their assets when they left.
By the outbreak of war in September 1939, half of Germany's five hundred
thousand Jews had fled, as had many Jews from other German-occupied
areas.

--------------

#+END_NOTES

** Final Solution


-  Hitler's Nazi government planned a "Final Solution" to the "Jewish
   question." After experimenting with different methods of mass
   extermination, Nazis settled on the gas chamber as the most efficient
-  Death camp operations began in December 1941 at Semlin in Serbia and
   at Chelmno in Poland
-  More camps opened in the spring and summer of 1942

#+BEGIN_NOTES
Note: Hitler's Nazi government planned a "Final Solution" to the "Jewish
question." After experimenting with different methods of mass
extermination, Nazis settled on the gas chamber as the most efficient.
Death camp operations began in December 1941 at Semlin in Serbia and at
Chelmno in Poland, where people were killed by exhaust fumes in
specially modified vans that were driven to nearby sites where bodies
were plundered and burnt. At Chelmno and Semlin, 265,000 Jews were
killed in this way. - The largest of the death camps was at Auschwitz.
It was originally a concentration camp for Polish political prisoners
but was expanded in 1941 with the addition of a larger camp at nearby
Birkenau. - The extermination of European Jews reached a new peak in the
summer of 1944, after Germany invaded Hungary - The Final Solution moved
into its last stages as Allied forces closed in on Germany in 1944. The
camps were closed and burned down - When the war ended and the
concentration camps were liberated by Allied troops, thousands of
unburied corpses and tens of thousands of sick and dying prisoners were
found crammed into overcrowded barracks without food or water.

More camps opened in the spring and summer of 1942, when the Nazis began
clearing the ghettos in Poland and rounding up Jews in western Europe
for deportation to labor and concentration camps such as those at
Treblinka, Belzec, and Sobibor. The largest of the death camps was at
Auschwitz. It was originally a concentration camp for Polish political
prisoners but was expanded in 1941 with the addition of a larger camp at
nearby Birkenau. Auschwitz-Birkenau and its subcamps held 400,000
prisoners, including 205,000 Jews. In the spring of 1942, gas chambers
were built at Birkenau, and mass transports of Jews began to arrive
there. Some were held as registered prisoners, but the great majority
was gassed. These gassing operations were expanded in 1943, and four gas
chamber and crematorium complexes were built. Before they were killed,
the victims' valuables were stripped from them. Their hair was used to
stuff mattresses, and any gold in their teeth was melted down. In total,
about one million Jews died at Auschwitz-Birkenau.

The extermination of European Jews reached a new peak in the summer of
1944, after Germany invaded Hungary, and the new (but not yet fully
fascist) Hungarian government fully cooperated in the deportation of
430,000 Jews to Auschwitz in only seven weeks, from May 15 to July 9.
About 100,000 of the Hungarian Jews were selected for forced
labor---they were assigned to work in the construction of factories for
German fighter planes and other tasks. Another 80,000 Jews were exempted
from deportation and consigned instead to the Hungarian Army's forced
Labor Service.

The Final Solution moved into its last stages as Allied forces closed in
on Germany in 1944. The camps were closed and burned down. Prisoners
remaining at concentration camps in the occupied lands were transported
or force-marched to camps in Germany. Thousands of prisoners on these
death marches died of starvation, exhaustion, and cold, or they were
shot. When the war ended and the concentration camps were liberated by
Allied troops, thousands of unburied corpses and tens of thousands of
sick and dying prisoners were found crammed into overcrowded barracks
without food or water.

Much of Europe was destroyed in the war. Survivors of the camps were in
terrible condition, both physically and psychologically. Many lost their
faith, committed suicide, or were otherwise unable to resume normal
lives. Trials were held in Nuremberg in 1945 at which top surviving Nazi
leaders were tried for war crimes. Similar trials followed, but
thousands of war criminals eluded justice. Millions of people were
displaced, feeling unwelcome or unable to return to their former homes.
Israel was established as a state in 1948 and opened its doors to all
Jews, and many of them who survived the Holocaust migrated there, as
well as to the United States, Australia, and elsewhere.

--------------

#+END_NOTES

* Night as Literature
** Literary style
|*Narrative:* |short narrative piece, novella|
|*Semantics:*| The problem of capturing the unrepresentable,|
|*Allusion:*| Night is full of scriptural allusions|
|*Anti-bildungsroman:* |Wiesel's novella turns the tradition on its head.|
|*Hasidic tales:*| do not follow western notions but *develop their own time* according to the message of the story. "Time," ... "is represented as a creative force, a bridge sinking man to eternity."|

#+BEGIN_NOTES
Note: The novella is a short piece of fiction that is based on the
author's eight hundred-page memoir of his time in the Nazi death camps.
The shortened tale is told from a first person point of view. There is
no attempt to enter other minds and little attempt to explain what is on
the narrator's mind.

or sublime, into an art product has not been impossible since the Roman
treatise on the topic by Longinus. Using examples from the Old Testament
(particularly Genesis and Job), the Iliad, and poetry, he displayed the
successful methods for capturing nature in verse, ecstasy in poetry, the
abyss in myth, and supreme beings in mere names.

, or hints of reference to biblical npassages. In fact, the very
timelessness of the constant night is reminiscent of supernatural tales.

Traditionally, the bildungsroman in German literature is the story of a
young, naive man entering the world to seek adventure. He finds his
adventure, but it provides him with an important lesson. The denouement
finds him happy, wiser, and ready for a productive life. The classic
example is J. W. von Goethe's Wilhelm Meister's Apprenticeship.

-  The sole purpose of the book is to relate briefly and succinctly what
   happened. The reader's conclusions are meant to be independent,
   although they have been lead, quite consciously, toward an abhorrence
   of the moral vacuum presented in the camps.
-  As a result, Occidental aesthetics views nothing as beyond the
   ability of the well-trained artist to present it in a packaged form.

Nevertheless, the moral chaos and utter hell that was the Holocaust
surpassed any previously recorded human abyss. For some, even fifty
years later, it has broken the aesthetic mold of Longinus; how is it
possible to comprehend, let alone represent, this most awful of all
events? Not easily, yet Wiesel's methods resemble those humans who
preceded him in the effort to understand the horrible and sublime by
representing their experience in one form or other. It is through that
artistic effort that comprehension comes.

The means of representing the unrepresentable are the techniques of the
sparse and staccato. In this case, those techniques are used to keep the
reader, as much as possible, in mind of how precious is the breath of
air the death camp inmates survive on. Words are used sparingly and,
when possible, blank space is used instead.

The terse sentences remind the reader of the necessity of conserving
energy: one is meant to be bothered by the apparent waste of Eliezer's
run across the camp (at the end of a workday) to check on his father.
Generally, scenes are made up of few words yet loom large; the
storyteller relies on the imagination of the audience, rather than on
his ability. He places the dots and hints at the color, but the reader
creates the image. Sentences like: "An open tomb," "Never," "The gate to
the camp opened." They are fragments, scraps of evidence that remain
until they are sown together into a narrative which makes sense of what
happened. The narrative replaces the useless pictures the GIs took when
they liberated the camps. The struggle of representing the
unrepresentable horror, as Wiesel discovered, is best accomplished in
the same way that Longinus felt the writers of the Talmud did---with few
words and plenty of space for digestion. - Hasidic tales especially do
not follow Occidental notions but develop their own time according to
the message of the story. "Time," says Sibelman, "is represented as a
creative force, a bridge sinking man to eternity." Within the story time
are more direct allusions to particular stories. Two of the most
memorable examples will suffice to demonstrate.

Immediately after realizing that the group is not marching into the
death pit, there is the incantation, "Never shall I forget that night,
the first night in camp ... " etc. This passage is a pastiche of Psalm
150. In French (and Wiesel writes in French or Yiddish), the start of
each line begins with Jamais (meaning never). Psalm 150 praises God for
his works and deeds while the "Never" passage commits just the opposite
reality to memory.

Another example of allusion is the execution of the three prisoners. One
of these doomed prisoners is an *innocent child, a pipel*. This scene
recalls the moment in the Christian Gospel when Christ is crucified. In
the Gospel according to Matthew, he is accompanied by two thieves. At
the point of expiration, Christ asks God why he has been forsaken. At
death, the sky darkens and the onlookers murmur that this was definitely
the Son of God. In contradistinction, the death of the pipel bothers the
onlookers in the opposite way. There is still a look for God but this
time, "[w]here is he? Here He is---He is hanging here on the
gallows...."

( says Sibelman)

He presents an educated, young man forced into a hell made by human
hands. There he learns more wisdom than he asked for, even when he
dreamed of learning the mystical tradition. What he learns about human
behavior he would rather not apply. In the end, he sees himself in the
mirror, for the first time in several years, as a corpse. The result is
not that he will think about being a productive worker, but about
healing humanity.

--------------

#+END_NOTES

** Vocabulary


| Vocabulary    | /Night/               |                 |
|---------------+-----------------------+-----------------|
| revelation    | ghetto                | delusion        |
| phylactery    | beadle                | /hasidism/      |
| synagogue     | anti-semitism         | conflagration   |
| deportation   | crematorium           | Aryan           |
| apathy        | Kabbalah (cabalist)   | Zionism         |
| Talmud        | Kaddish               |                 |

#+BEGIN_NOTES
Note: - *penury:* extreme poverty - *waiflike:* neglected; uncared for -
*mysticism:* a system of contemplative prayer and spirituality aimed at
achieving direct intuitive experience of the divine - *fraught:* full
of; involving - *indulge:* to satisfy or gratify - *revelation:*
something revealed - *insinuate:* to suggest or imply - *annihilate:*
destroy completely - *anguish:* extreme distress, suffering, or pain -
*sublime:* supreme or outstanding - *edict:* command given by an
authority - *decree:* formal order or command - *ghetto:* a section of a
city in which all Jews were required to live - *delusion:* a false
belief or opinion - *anecdote:* short story about an event -
*antechamber:* waiting room - *relic:* something kept in remembrance; a
surviving memorial of something past - *phylactery:* either of two
small, black, leather cubes containing a piece of parchment inscribed
with verses 4::9 of Deut. 6, 13::21 of Deut. 11, and 1::16 of Ex. 13:
one is attached with straps to the left arm and the other to the
forehead during weekday morning prayers by Orthodox and conservative
Jewish men.

--------------

#+END_NOTES

** Characters

| *Characters*         | *Night*              |                  |
|----------------------+----------------------+------------------|
| Akiba Drummer      | Franek             | Hersch Genud   |
| Idek               | Juliek             | Meir Katz      |
| Louis              | Moshe the Beadle   | the pipel      |
| Madame Schächter   | Stein              | Tibi           |
| Chlomo Wiesel      | Eliezer Wiesel     | Yossi          |

* Group work on Night

** Teaching "Theme" with Night
#+BEGIN_NOTES
In this lesson, students will identify, discuss, and write about themes in Elie Wiesel’s Night.  Theme is sometimes a difficult concept for students to grasp, but it is essential to their development in literary analysis.  Repeatedly remind your students that the theme of a story is the central message or idea.  It says something about life, or about being human.  Theme is what makes literature compelling and significant to readers.

#+END_NOTES

** Topics in Night
#+BEGIN_NOTES
Ask students to list topics from the text.  
Make a master list on the board with student input.  You will end with a list that looks something like the following:  
- the Holocaust  
- faith  
- suffering  
- identity  
- survival instinct  
- human nature  
- civility vs. savagery

#+END_NOTES

** Theme Formula
#+BEGIN_NOTES
Explain that these are not themes – they are merely topics.  A theme is what the story says about a topic.  
  
Write the following formula on the board: Topic + Insight = Theme  
  
Students should copy this formula into their notes.  Stress that theme is more than just topic.  
Explain that theme is different from a moral.  It doesn’t state what people should or should not do.   Instead, it says something about what it means to be alive.  A moral might be as follows: look before you leap.  While the theme from the same story might be as follows: people are often impulsive and hedonistic.  
  
Ask your students what the story says about faith.  What is the authors message concerning faith?    
  
Discuss.

#+END_NOTES

** Theme Statements

#+BEGIN_NOTES
Write the following on the board: Elie Wiesel’s Night shows that faith…  
  
Ask your students to copy it down and finish the sentence.  
  
The finished product is a theme statement.  Tell your students to use this structure when writing theme statements.  
  
Students must now select three other topics to write theme statements for.  
When they are finished, call on students to share their statements with the class and check for understanding.  
  
Students must now add two reasons or examples to each of their three theme statements.  This can be done in point form.  
  
**Example:**  
  
Elie Wiesel’s Night shows that people often question their faith in God when faced with inexplicably suffering.  
  
- When the young boy is hanged, several prisoners ask “where is God?”.  
- Elie frequently comments on his dimishing faith.  He cannot understand why a supreme and benevolent being would allow such horror to exist.

#+END_NOTES

** Topics in *Night*

 *topic + insight = theme*

1. Death
2. Loss of faith:
3. Fire
4. Symbols
5. Night
6. Fathers and sons
7. Silence
8. God and religion
9. Sanity / Insanity
