#+Author: Dale Hathaway
#+Title:Theodicy
#+Date: Week of March 23, 2020
#+Email: hathawayd@winthrop.edu
#+OPTIONS: org-reveal-title-slide:"%t"
#+OPTIONS: reveal_width:1000 reveal_height:800 
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2
#+REVEAL_HLEVEL: 1
#+OPTIONS: toc:1 num:nil
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
#+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
#+REVEAL_PLUGINS: (markdown notes menu)
#+REVEAL_ROOT: ../../reveal.js
#+REVEAL_THEME: beige


* The Problem of Evil
  :PROPERTIES:
  :CUSTOM_ID: the-problem-of-evil
  :END:

- The word theodicy derives from the Greek words

*** Θεός Τheos and δίκη dikē.
  :PROPERTIES:
  :CUSTOM_ID: θεός-τheos-and-δίκη-dikē.
  :END:

- "God" + "Justice"
- http://youtu.be/qqzF2aRVJAc Elie Wiesel
- we must remember
- the challenge

** What is the Problem of Evil?*

- actually a cluster of "problems" related to understanding *Sacred reality*
- Why does good fortune turn to bad? (*Psalms*)
- Why do the righteous suffer and the wicked flourish? (*Hindu*)

#+BEGIN_NOTES
Note: - The problem of evil actually represents not a single problem but a cluster of issues arising from the attempt to relate a diverse set of experiences to notions of sacred reality. - Drawing on the tradition of his faith community, for example, the psalmist asks, in effect, Why does good fortune turn to bad? - In a very different context, a critic of Hindu beliefs asks a different sort of question: Why do the righteous suffer and the wicked flourish?


#+END_NOTES 


** Logical dilemma
  :PROPERTIES:
  :CUSTOM_ID: logical-dilemma
  :END:

- In religious traditions that stress the power and goodness of one God who rules over all creation, the existence of evil presents a logical dilemma.

  - If God is good and powerful, what is the nature of evil?
  - If God could prevent evil but does not, can God be good?
  - On the other hand, if God is good but cannot prevent evil, can God be powerful?


** Problem of Evil (Christianity)
  :PROPERTIES:
  :CUSTOM_ID: problem-of-evil-christianity
  :END:

/We have heard with our ears, O God, our ancestors have told us, what deeds you performed in their days, in the days of old; you with your own hand drove out the nations. . . . Yet you have rejected us and abased us, and have not gone out with our armies. You made us turn back from the foe, and our enemies have gotten spoil/. (Psalm 44:12a, 910)

--

** Problem of Evil Hinduism
  :PROPERTIES:
  :CUSTOM_ID: problem-of-evil-hinduism
  :END:

/The world is so confused and out of joint, why does Brahma not set it straight? If he is master of the whole world, Brahma, lord of the many beings born, why in the whole world did he ordain misfortune? Why did he not make the whole world happy? . . .Why did he make the world with deception, lies, and excess, with injustice?/

--------------

* Theodicy
  :PROPERTIES:
  :CUSTOM_ID: theodicy
  :END:

- God is all-merciful. God is all-powerful. God is perfect-justice.
- Any 2 of these can be held at the same time - but not all 3
- even non-theists must explain the presence of evil & suffering (cf. e.g. a psychologists perspective: [[http://www.gurteen.com/gurteen/gurteen.nsf/id/X0038E2E2/][Scott Peck]])

#+BEGIN_NOTES
Chart:

https://drive.google.com/file/d/11T6s_u4aGNTnf-HqkxtawUtMg3ISKYhL/view?usp=sharing

cf. slideshare: https://www.slideshare.net/Mrs-B/apologetics-101-wk6-evil-suffering

trilemma: https://drive.google.com/file/d/11VhSFh6zD1P_nheRi0nhD9Hcc_c7BKd8/view?usp=sharing

Note: - When the problem of evil is raised in connection with belief in God or gods, we may describe them as issues of *theodicy*, or divine justice. - However, even those religious traditions that stress the impersonal nature of the sacred, must seek to explain the existence of evil or suffering in the world. 

The Holocaust: These were highly educated people - The people of
Beethoven - The people of Luther
@@html:<!-- .element: style="float: right; width: 40%" -->@@

[[http://drive.google.com/uc?export=download&id=0B8ezT0-tUjVZNWFRQlRKOXM3WnM]]
@@html:<!-- .element: style="width: 40%" -->@@


For Jews the challenge of a God of history, with a plan -- for
Christians: Where was Christ?
@@html:<!-- .element: style="float: right; width: 40%" -->@@

[[http://drive.google.com/uc?export=download&id=0B8ezT0-tUjVZTUFNYjJ5VmtBTU0]]
@@html:<!-- .element: style="width: 40%" -->@@

Note: - For Jews, the challenge of the Holocaust involves the relationship of the destruction of Europe's Jews to the notion that there is a God who governs history according to a plan and that all the events of Jewish history have a meaning in the plan of God. - For Christians, the problem is slightly different and involves the following question: In the death camps, where was Christ?


#+END_NOTES
** 
    :PROPERTIES:
    :reveal_background: https://drive.google.com/uc?export=view&id=11T6s_u4aGNTnf-HqkxtawUtMg3ISKYhL
    :reveal_background_trans: slide
    :reveal_background_size: 1200px
    :END:

** 
    :PROPERTIES:
    :reveal_background: https://drive.google.com/uc?export=view&id=11VhSFh6zD1P_nheRi0nhD9Hcc_c7BKd8
    :reveal_background_trans: slide
    :reveal_background_size: 1200px
    :END:

 
** The Holocaust (Shoah)
  :PROPERTIES:
  :CUSTOM_ID: the-holocaust-shoah
  :END:

- In the modern West, no single experience raises the questions associated with the problem of evil with greater power than the *Holocaust*.
- The *Holocaust* illustrates the general point of how religious people identify evil in terms of a contradiction between the facts of experience and the reality of the sacred.
- The *Holocaust* challenges some of the central affirmations of Jewish and Christian faith.


#+BEGIN_NOTES

Note: - For Jews, the challenge of the Holocaust involves the relationship of the destruction of Europes Jews to the notion that there is a God who governs history according to a plan and that all the events of Jewish history have a meaning in the plan of God. - For Christians, the problem is slightly different and involves the following question: In the death camps, where was Christ?

#+END_NOTES

** Slavery
- For our country the effects of slavery are still affected by racism 
** Genocide e.g. Native American
- the genocide perpetrated on Native Americans by Europeans colonizing North America 
** Extinction Environmental Catastrophe
- many would argue that the mounting catastrophe of the abuse of the environment may be the largest of all
** Some bibliography 

* 4 Responses to the Problem of Evil
  :PROPERTIES:
  :CUSTOM_ID: responses-to-the-problem-of-evil
  :END:

1. *Karma*
2. *Consolation of Promise*
3. *Appeal to Sovereignty*
4. *Dualism*


** Karma & the Indian Context
  :PROPERTIES:
  :CUSTOM_ID: responses-to-the-problem-of-evil-1
  :END:



- *Karma*, signifies the moral weight of one's actions
- people get what they deserve (at least over the long haul)


#+BEGIN_NOTES

Note: - *Karma*, signifies the moral weight of one's actions. Good or proper action results in good karma and in progress toward the goal of enlightenment. - In connection with the problem of evil, *karma* is a kind of inexorable reality that explains the destiny of human beings. People get what they deserve at least, over the long cycle of time. - The inexorability of *karma* is the problem addressed in the Buddhist story of The Death of Moggallana.

--

#+END_NOTES
** Karma & the Buddhist Perspective
   :PROPERTIES:
   :CUSTOM_ID: buddhist-perspective-on-evil
  :END:

- *Evil is located in the self*, with its passions and desires.
- cruelty & pain are not simply luck of the draw
- not the *will of God*
- solution to the problem of evil *depends on each individual*


#+BEGIN_NOTES

Note: - The brute facts of cruelty and pain are not simply the luck of the draw, nor are they connected with the will of God. - One who attains enlightenment knows that the resolution of the experiences associated with evil does not depend on gods or goddesses, nor does it depend on other human beings. - In the fundamental sense, the solution to the problem of evil depends on each individual person.

--------------

#+END_NOTES

* The Consolation of Promise
  :PROPERTIES:
  :CUSTOM_ID: reponses-to-the-problem-of-evil
  :END:


- At some future time, evil will be overcome, justice will be satisfied, and the point of suffering will be made clear.
- Such a response uses the language of promise, offering consolation and hope to those currently suffering.
- Just how or when the promise will be fulfilled is a matter on which there is a variety of opinions.


** Consolation of Promise: Jewish
  :PROPERTIES:
  :CUSTOM_ID: jewish-perspective-on-evil
  :END:

- Jews wait for a *Messiah who is yet to come*.
- When the anointed one arrives, he will reestablish the nation of Israel and will rule the other nations with a rod of iron.
- some Orthodox groups oppose the nation of Israel *because the Messiah has not yet come.*


#+BEGIN_NOTES

Note: - It is significant that a number of Orthodox groups hold that the contemporary state of Israel is not a fulfillment of this promise. - Rather, they view the Jewish state as a violation of the Torah, a manifestation of the impatience and disobedience of humanity rather than the work of God.

--

#+END_NOTES

** Consolation of Promise: Christian 
  :PROPERTIES:
  :CUSTOM_ID: christian-response-to-evil
  :END:

- Christianity holds that the *Messiah has come*: Jesus of Nazareth is the Messiah.
- His life, death, and resurrection manifest the promise of God to bring about a peaceable kingdom.
- The work of Jesus is not yet complete, however. For, he will come again in glory to judge the living and the dead; and his reign will have no end.
- The doctrine of the *parousia* or the second coming of Christ indicates that the fulfillment of the promise is yet to come.

  
** Consolation of Promise: Muslim 
  :PROPERTIES:
  :CUSTOM_ID: muslim-response-to-evil
  :END:

- Islam also embodies the promise theme common to Judaism and Christianity.
- An idea appears in the Islamic tradition that the *mahdi* will come or appear at the time God decides and will establish the rule of justice and equity on earth.
- Islam also refers to an afterlife in which *good will be rewarded, evil punished, and suffering explained.*
- Through a *Day of Resurrection and Judgment, God will resolve the problem of evil.*


* Appeal to Sovereignty
  :PROPERTIES:
  :CUSTOM_ID: reponses-to-the-problem-of-evil-1
  :END:


- The sovereignty appeal finds its power in affirming that, at least from the human standpoint, there are no solutions to the problem of evil.
-  The book of *Job* may be taken as the archetype of the sovereignty response. As such, it has both baffled and comforted believers throughout generations of Jewish and Christian faith.


** Appeal to Sovereignty: Story of Job
  :PROPERTIES:
  :CUSTOM_ID: the-story-of-job
  :END:

- God tests Jobs faith to see if his obedience to God is motivated by his own integrity or desire for personal gain.
- Job rejects the idea that his suffering is for his education or to make him better
- Job also rejects the idea that his suffering is in proportion to some sin he has committed.
- In the end, God claims the wisdom of the creator of all things and Job accepts the finitude of human understanding and the sovereignty of the maker of heaven and earth. 

* Dualism
  :PROPERTIES:
  :CUSTOM_ID: responses-to-the-problem-of-evil-2
  :END:


- Evil is the result of a conflict between good and evil powers, *both of which share some of the characteristics of sacred reality.*
- From the perspective of dualism, *God is good but God's sovereignty faces a severe challenge from those powers that do evil in the world.*
- Many religious traditions embody elements of dualism, but the best example is in *Zoroastrianism.*

** Dualism: Zoroastrian 
  :PROPERTIES:
  :CUSTOM_ID: zoroastrian-response-to-evil
  :END:

- Struggle between *Spenta Mainyu* (beneficent spirit) and *Angra Mainyu* (hostile spirit), whose conflict stems from the beginning of all things and continues to the end of time.
- *Spenta Mainyu* and *Angra Mainyu* are twins, offspring of the wise lord *Ahura Mazda*, the creator of all things.
- *Ahura Mazdas* twins represent the moral choice set before all creatures. Evil comes into the world as a result of wrongful choice, and the proper response is thus to fight against it.


* Evaluating Responses to the Problem of Evil
  :PROPERTIES:
  :CUSTOM_ID: evaluating-responses-to-the-problem-of-evil
  :END:

- Are the answers adequate?
- Are the answers logical?
- Are the answers coherent?
- Are the answers psychologically satisfying?
- What are the moral consequences?
