#+Author: Dale Hathaway
#+Title:Theodicy pt. 2: 4 responses to Problem of Evil
#+Date: Week of March 23, 2020
#+Email: hathawayd@winthrop.edu
#+OPTIONS: org-reveal-title-slide:"%t" "%s"
#+OPTIONS: reveal_width:1000 reveal_height:800 
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2
#+REVEAL_HLEVEL: 1
#+OPTIONS: toc:1 num:nil
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal">
#+REVEAL_POSTAMBLE: <p> Created by Dale Hathaway. </p>
#+REVEAL_PLUGINS: (markdown notes menu)
#+REVEAL_ROOT: ../../reveal.js
#+REVEAL_THEME: beige

* Guide to app usage 
| Key stroke  | Effect                    |
|-------------+--------------|
| n, space    | next slide                |
| p           | previous slide            |
| f           | fullscreen                |
| esc, o      | overview slide            |
| m           | toggle menu               |
|------------ +--------------------|
|------------ +--------------------|
| audio inlay | start/stop audio playback |

* 4 Responses to the Problem of Evil
  :PROPERTIES:
  :CUSTOM_ID: responses-to-the-problem-of-evil
  :END:

1. *Karma*
2. *Consolation of Promise*
3. *Appeal to Sovereignty*
4. *Dualism*

#+begin_notes
- Our textbook identifies 4 basic responses that religions around the world and throughout time have made to the problem of evil.
- When we say *problem* we don't mean it so much as a *problem to be solved* but a *tension to be lived with.*
- Over the course of many centuries religious cultures have found 4 general patterns of living with the tension  created by the "problem of evil."
#+end_notes
* Karma
- Karma presumes a close relationship between cause and effect in human decision-making
- Karma balances the sum total of a human's actions and decisions
- Cause and effect is understood as a part of a cosmic cycle
- With *Karma*, what happens to a person, happens because they caused it with their actions
- This response emphasizes *justice* -- perhaps at the expense of *mercy*?
** Karma & the Indian Context
  :PROPERTIES:
  :CUSTOM_ID: responses-to-the-problem-of-evil-1
  :END:

- *Karma*, signifies the moral weight of one's actions
- people get what they deserve (at least over the long haul)


#+BEGIN_NOTES

Note: - *Karma*, signifies the moral weight of one's actions. Good or proper action results in good karma and in progress toward the goal of enlightenment. - In connection with the problem of evil, *karma* is a kind of inexorable reality that explains the destiny of human beings. People get what they deserve at least, over the long cycle of time. - The inexorability of *karma* is the problem addressed in the Buddhist story of The Death of Moggallana.

*Karma* allows us to live with a keen sense of justice and accountability.

#+END_NOTES
** Karma & the Buddhist Perspective
   :PROPERTIES:
   :CUSTOM_ID: buddhist-perspective-on-evil
  :END:

- *Evil is located in the self*, with its passions and desires.
- cruelty & pain are not simply luck of the draw
- not the *will of God*
- solution to the problem of evil *depends on each individual*


#+BEGIN_NOTES

Note: - The brute facts of cruelty and pain are not simply the luck of the draw, nor are they connected with the will of God. - One who attains enlightenment knows that the resolution of the experiences associated with evil does not depend on gods or goddesses, nor does it depend on other human beings. - In the fundamental sense, the solution to the problem of evil depends on each individual person.

The Buddhist perspective is directly contrary to the familiar *original sin* that has been a part of much Christian life over the centuries. Each individual has the choice and has the power to choose what is good and right -- to choose to act in accordance with the *dharma*.


#+END_NOTES

* The Consolation of Promise
  :PROPERTIES:
  :CUSTOM_ID: reponses-to-the-problem-of-evil
  :END:
The Promise of this response to evil:

- the point of suffering will be made clear in the future
- evil will be overcome in the future
- justice will prevail in the future
- this response delays *justice* perhaps for the sake of *mercy*


#+begin_notes
- At some future time, evil will be overcome, justice will be satisfied, and the point of suffering will be made clear.
- Such a response uses the language of promise, offering consolation and hope to those currently suffering.
- Just how or when the promise will be fulfilled is a matter on which there is a variety of opinions.
 
#+end_notes



** Consolation of Promise: Jewish
  :PROPERTIES:
  :CUSTOM_ID: jewish-perspective-on-evil
  :END:

- Jews wait for a *Messiah who is yet to come*.
- When the anointed one arrives, he will reestablish the nation of Israel and will rule the other nations with a rod of iron.
- some Orthodox groups oppose the nation of Israel *because the Messiah has not yet come.*


#+BEGIN_NOTES

Note: 
- It is significant that a number of Orthodox groups hold that the contemporary state of Israel is not a fulfillment of this promise. 
- Rather, they view the Jewish state as a violation of the Torah, a manifestation of the impatience and disobedience of humanity rather than the work of God.
- Many Christians imagine that there is no sense of the *Messiah* in Judaism, but it is in fact not *absent* but understood differently than in Christianity.


#+END_NOTES

** Consolation of Promise: Christian 
  :PROPERTIES:
  :CUSTOM_ID: christian-response-to-evil
  :END:

- Christianity holds that the *Messiah has come*: Jesus of Nazareth is the Messiah.
- His life, death, and resurrection manifest the promise of God to bring about a peaceable kingdom.
- The work of Jesus is not yet complete, however. For, he will come again in glory to judge the living and the dead; and his reign will have no end.
- The doctrine of the *parousia* or the second coming of Christ indicates that the fulfillment of the promise is yet to come.

#+begin_notes
Note:
- In Christianity there has always been a sense of fulfillment alongside a hope and expectation of a future grand fulfillment.
- One of the phrases associated with this two-sided experience is that the *Promised fulfillment* is "already / but not yet."
- The experience of *justice* can be weakened if accountability is completely pushed to the *end of time*. 
- The poor and suffering must *wait* for justice to prevail.
#+end_notes


  
** Consolation of Promise: Muslim 
  :PROPERTIES:
  :CUSTOM_ID: muslim-response-to-evil
  :END:
- Islam shares a sense of the Consolation of Promise with both Judaism and Christianity
- the figure of *mahdi* bears similarities with the expectation of a *messiah* to come
- each of the 3 religions share a conception of *afterlife* and a *Day of Resurrection & Judgment*


#+begin_notes
- Islam also embodies the promise theme common to Judaism and Christianity.
- An idea appears in the Islamic tradition that the *mahdi* will come or appear at the time God decides and will establish the rule of justice and equity on earth.
- Islam also refers to an afterlife in which *good will be rewarded, evil punished, and suffering explained.*
- Through a *Day of Resurrection and Judgment, God will resolve the problem of evil.*


#+end_notes



* Appeal to Sovereignty
  :PROPERTIES:
  :CUSTOM_ID: reponses-to-the-problem-of-evil-1
  :END:
- the appeal to sovereignty proclaims that for human beings there is not resolution to the tension of the *problem of evil*
- The book of *Job* in the Hebrew Scriptures is the epitome of the appeal to sovereignty
- this response emphasizes *transcendence* but perhaps *minimizes* human accountability



#+begin_notes
- The sovereignty appeal finds its power in affirming that, at least from the human standpoint, there are no solutions to the problem of evil.
-  The book of *Job* may be taken as the archetype of the sovereignty response. As such, it has both baffled and comforted believers throughout generations of Jewish and Christian faith.


#+end_notes

** Job 38
#+Begin_verse
And now, finally, God answered Job from the eye of a violent storm. He said:

2-11 “Why do you confuse the issue?
    Why do you talk without knowing what you’re talking about?
Pull yourself together, Job!
    Up on your feet! Stand tall!
I have some questions for you,
    and I want some straight answers.
Where were you when I created the earth?

#+End_verse
And now, finally, God answered Job from the eye of a violent storm. He said:

“Why do you confuse the issue?
    Why do you talk without knowing what you’re talking about?
Pull yourself together, Job!
    Up on your feet! Stand tall!
I have some questions for you,
    and I want some straight answers.
Where were you when I created the earth?


#+begin_notes

#+end_notes
** Appeal to Sovereignty: Story of Job
  :PROPERTIES:
  :CUSTOM_ID: the-story-of-job
  :END:

- God tests Jobs faith to see if his obedience to God is motivated by his own integrity or desire for personal gain.
- Job rejects the idea that his suffering is for his education or to make him better
- Job also rejects the idea that his suffering is in proportion to some sin he has committed.
- In the end, God claims the wisdom of the creator of all things and Job accepts the finitude of human understanding and the sovereignty of the maker of heaven and earth. 
#+begin_notes

#+end_notes


* Dualism
  :PROPERTIES:
  :CUSTOM_ID: responses-to-the-problem-of-evil-2
  :END:
- personification of *dualism*: God vs. Satan
- in Dualism both good and evil share characteristics of the *sacred*
- in Dualism God's *power* is not absolute
- this response reduces the *power* of good by shifting some of it to evil

#+begin_notes
- the response of *Dualism* is familiar to many in the personification of the combat between God and the Devil
- Evil is the result of a conflict between good and evil powers, *both of which share some of the characteristics of sacred reality.*
- From the perspective of dualism, *God is good but God's sovereignty faces a severe challenge from those powers that do evil in the world.*
- Many religious traditions embody elements of dualism, but the best example is in *Zoroastrianism.*

#+end_notes


** Dualism: Zoroastrian 
  :PROPERTIES:
  :CUSTOM_ID: zoroastrian-response-to-evil
  :END:
- Zoroastrianism began in what is today Iran under the leadership of the teacher Zarathustra
- historically it began ca. 5th c. BCE, though its roots may go back much further
- the conflict between good (*Spenta Mainyu*) and evil (*Angra Mainyu*) is built into the foundation of the religion
- evil comes into the world as a result of wrong choices
#+begin_notes
- Struggle between *Spenta Mainyu* (beneficent spirit) and *Angra Mainyu* (hostile spirit), whose conflict stems from the beginning of all things and continues to the end of time.
- *Spenta Mainyu* and *Angra Mainyu* are twins, offspring of the wise lord *Ahura Mazda*, the creator of all things.
- *Ahura Mazdas* twins represent the moral choice set before all creatures. Evil comes into the world as a result of wrongful choice, and the proper response is thus to fight against it.
- Zoroastrianism influenced the development of much of western religion and philosophy


#+end_notes

* Free will
- some have developed another response to the problem of evil based on our experience of *free will*
- usually this "solution" requires separate treatment of *human-caused evil* and *natural-caused evil*
- this response emphasizes the virtue of *freedom* perhaps at the expense of *mercy* and *justice* 

#+begin_notes
The problem of evil is sometimes explained as a consequence of free will, an ability granted by God. Free will is both a source of good and of evil, and with free will also comes the potential for abuse, as when individuals act immorally. People with free will "decide to cause suffering and act in other evil ways", states Boyd, and it is they who make that choice, not God. Further, the free will argument asserts that it would be logically inconsistent for God to prevent evil by coercion and curtailing free will, because that would no longer be free will. [Wiki.]

While our experience of free will does explain some -- or even much -- of our experience of evil, it is by no means exhaustive. The depth of the evil we see and know about argues against the adequacy of *free will*, even while it satisfies many.

#+end_notes
* Evaluating Responses to the Problem of Evil
  :PROPERTIES:
  :CUSTOM_ID: evaluating-responses-to-the-problem-of-evil
  :END:

- Are the answers adequate?
- Are the answers logical?
- Are the answers coherent?
- Are the answers psychologically satisfying?
- What are the moral consequences?
